export interface Component {
  selector: string;
  variables: string[];
  variant: boolean;
}

export const components: Component[] = [
  {
    selector: 'sr-only',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-accordion',
    variables: ['--z-accordion-border', '--z-accordion-border-o'],
    variant: false,
  },
  {
    selector: 'z-accordion-content',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-accordion-icon',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-accordion-title',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-active',
    variables: [
      '--z-nav-item-bg',
      '--z-nav-item-bg-o',
      '--z-nav-item-color',
      '--z-nav-item-color-o',
      '--z-nav-item-font-weight',
      '--z-pagination-item-hover-bg',
      '--z-pagination-item-hover-bg-o',
      '--z-pagination-item-hover-color',
      '--z-pagination-item-hover-color-o',
      '--z-table-active-bg',
      '--z-table-active-bg-o',
    ],
    variant: false,
  },
  {
    selector: 'z-alert',
    variables: [
      '--z-alert-bg',
      '--z-alert-bg-o',
      '--z-alert-border',
      '--z-alert-border-o',
      '--z-alert-color',
      '--z-alert-color-o',
    ],
    variant: false,
  },
  {
    selector: 'z-alert-close',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-alert-danger',
    variables: ['--z-alert-bg', '--z-alert-bg-o', '--z-alert-border', '--z-alert-border-o'],
    variant: true,
  },
  {
    selector: 'z-alert-info',
    variables: ['--z-alert-bg', '--z-alert-bg-o', '--z-alert-border', '--z-alert-border-o'],
    variant: true,
  },
  {
    selector: 'z-alert-success',
    variables: ['--z-alert-bg', '--z-alert-bg-o', '--z-alert-border', '--z-alert-border-o'],
    variant: true,
  },
  {
    selector: 'z-alert-warning',
    variables: ['--z-alert-bg', '--z-alert-bg-o', '--z-alert-border', '--z-alert-border-o'],
    variant: true,
  },
  {
    selector: 'z-animation-fade',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-animation-fast',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-animation-kenburns',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-animation-reverse',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-animation-scale-down',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-animation-scale-up',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-animation-shake',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-animation-slide-bottom',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-animation-slide-bottom-medium',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-animation-slide-bottom-small',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-animation-slide-left',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-animation-slide-left-medium',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-animation-slide-left-small',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-animation-slide-right',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-animation-slide-right-medium',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-animation-slide-right-small',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-animation-slide-top',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-animation-slide-top-medium',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-animation-slide-top-small',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-animation-stroke',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-avatar',
    variables: [
      '--z-avatar-bg',
      '--z-avatar-border',
      '--z-avatar-border-o',
      '--z-avatar-radius',
      '--z-avatar-size',
    ],
    variant: false,
  },
  {
    selector: 'z-avatar-bordered',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-avatar-dot',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-avatar-dot-bottom',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-avatar-dot-bottom-left',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-avatar-dot-bottom-right',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-avatar-dot-danger',
    variables: ['--z-avatar-dot-bg'],
    variant: true,
  },
  {
    selector: 'z-avatar-dot-info',
    variables: ['--z-avatar-dot-bg'],
    variant: true,
  },
  {
    selector: 'z-avatar-dot-left',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-avatar-dot-muted',
    variables: ['--z-avatar-dot-bg'],
    variant: true,
  },
  {
    selector: 'z-avatar-dot-right',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-avatar-dot-success',
    variables: ['--z-avatar-dot-bg'],
    variant: true,
  },
  {
    selector: 'z-avatar-dot-top',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-avatar-dot-top-left',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-avatar-dot-top-right',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-avatar-dot-warning',
    variables: ['--z-avatar-dot-bg'],
    variant: true,
  },
  {
    selector: 'z-avatar-rounded',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-avatar-text',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-badge',
    variables: [
      '--z-badge-bg',
      '--z-badge-bg-o',
      '--z-badge-border',
      '--z-badge-border-o',
      '--z-badge-color',
      '--z-badge-color-o',
    ],
    variant: false,
  },
  {
    selector: 'z-badge-danger',
    variables: [
      '--z-badge-bg',
      '--z-badge-bg-o',
      '--z-badge-border',
      '--z-badge-border-o',
      '--z-badge-color',
    ],
    variant: true,
  },
  {
    selector: 'z-badge-info',
    variables: [
      '--z-badge-bg',
      '--z-badge-bg-o',
      '--z-badge-border',
      '--z-badge-border-o',
      '--z-badge-color',
    ],
    variant: true,
  },
  {
    selector: 'z-badge-success',
    variables: [
      '--z-badge-bg',
      '--z-badge-bg-o',
      '--z-badge-border',
      '--z-badge-border-o',
      '--z-badge-color',
    ],
    variant: true,
  },
  {
    selector: 'z-badge-warning',
    variables: [
      '--z-badge-bg',
      '--z-badge-bg-o',
      '--z-badge-border',
      '--z-badge-border-o',
      '--z-badge-color',
    ],
    variant: true,
  },
  {
    selector: 'z-blockquote',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-breadcrumb',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-button',
    variables: [
      '--z-button-bg',
      '--z-button-bg-o',
      '--z-button-border',
      '--z-button-border-o',
      '--z-button-color',
      '--z-button-disabled-o',
      '--z-button-font-size',
      '--z-button-font-weight',
      '--z-button-height',
      '--z-button-hover-bg',
      '--z-button-hover-bg-o',
      '--z-button-hover-color',
      '--z-button-icon-size',
      '--z-button-line-height',
      '--z-button-padding',
      '--z-button-padding-block',
      '--z-button-padding-inline',
      '--z-button-radius',
      '--z-button-shadow',
    ],
    variant: false,
  },
  {
    selector: 'z-button-danger',
    variables: [
      '--z-button-bg',
      '--z-button-bg-o',
      '--z-button-border',
      '--z-button-border-o',
      '--z-button-color',
      '--z-button-hover-bg',
      '--z-button-hover-bg-o',
      '--z-button-hover-color',
    ],
    variant: true,
  },
  {
    selector: 'z-button-default',
    variables: [
      '--z-button-bg',
      '--z-button-bg-o',
      '--z-button-border',
      '--z-button-border-o',
      '--z-button-color',
      '--z-button-hover-bg',
      '--z-button-hover-bg-o',
      '--z-button-hover-color',
    ],
    variant: true,
  },
  {
    selector: 'z-button-ghost',
    variables: [
      '--z-button-bg',
      '--z-button-bg-o',
      '--z-button-border',
      '--z-button-border-o',
      '--z-button-hover-bg',
      '--z-button-hover-bg-o',
      '--z-button-hover-color',
      '--z-button-shadow',
    ],
    variant: true,
  },
  {
    selector: 'z-button-group',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-button-icon',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-button-info',
    variables: [
      '--z-button-bg',
      '--z-button-bg-o',
      '--z-button-border',
      '--z-button-border-o',
      '--z-button-color',
      '--z-button-hover-bg',
      '--z-button-hover-bg-o',
      '--z-button-hover-color',
    ],
    variant: true,
  },
  {
    selector: 'z-button-large',
    variables: [
      '--z-interactive-height-multiplier',
      '--z-interactive-padding-block-multiplier',
      '--z-interactive-padding-inline-multiplier',
    ],
    variant: true,
  },
  {
    selector: 'z-button-medium',
    variables: [
      '--z-interactive-height-multiplier',
      '--z-interactive-padding-block-multiplier',
      '--z-interactive-padding-inline-multiplier',
    ],
    variant: true,
  },
  {
    selector: 'z-button-outline',
    variables: [
      '--z-button-bg',
      '--z-button-bg-o',
      '--z-button-border',
      '--z-button-border-o',
      '--z-button-color',
      '--z-button-hover-bg',
      '--z-button-hover-bg-o',
      '--z-button-hover-color',
    ],
    variant: true,
  },
  {
    selector: 'z-button-primary',
    variables: [
      '--z-button-bg',
      '--z-button-bg-o',
      '--z-button-border',
      '--z-button-border-o',
      '--z-button-color',
      '--z-button-hover-bg',
      '--z-button-hover-bg-o',
      '--z-button-hover-color',
    ],
    variant: true,
  },
  {
    selector: 'z-button-secondary',
    variables: [
      '--z-button-bg',
      '--z-button-bg-o',
      '--z-button-border',
      '--z-button-border-o',
      '--z-button-color',
      '--z-button-hover-bg',
      '--z-button-hover-bg-o',
      '--z-button-hover-color',
    ],
    variant: true,
  },
  {
    selector: 'z-button-small',
    variables: [
      '--z-interactive-height-multiplier',
      '--z-interactive-padding-block-multiplier',
      '--z-interactive-padding-inline-multiplier',
    ],
    variant: false,
  },
  {
    selector: 'z-button-success',
    variables: [
      '--z-button-bg',
      '--z-button-bg-o',
      '--z-button-border',
      '--z-button-border-o',
      '--z-button-color',
      '--z-button-hover-bg',
      '--z-button-hover-bg-o',
      '--z-button-hover-color',
    ],
    variant: true,
  },
  {
    selector: 'z-button-text',
    variables: [
      '--z-button-bg',
      '--z-button-bg-o',
      '--z-button-border',
      '--z-button-border-o',
      '--z-button-hover-bg',
      '--z-button-hover-bg-o',
      '--z-button-radius',
      '--z-button-shadow',
    ],
    variant: false,
  },
  {
    selector: 'z-button-warning',
    variables: [
      '--z-button-bg',
      '--z-button-bg-o',
      '--z-button-border',
      '--z-button-border-o',
      '--z-button-color',
      '--z-button-hover-bg',
      '--z-button-hover-bg-o',
      '--z-button-hover-color',
    ],
    variant: true,
  },
  {
    selector: 'z-button-xsmall',
    variables: [
      '--z-interactive-height-multiplier',
      '--z-interactive-padding-block-multiplier',
      '--z-interactive-padding-inline-multiplier',
    ],
    variant: false,
  },
  {
    selector: 'z-cal',
    variables: ['--z-cal-cell-size'],
    variant: false,
  },
  {
    selector: 'z-cal-header',
    variables: ['--z-cal-header-column-gap'],
    variant: false,
  },
  {
    selector: 'z-cal-header-l',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-cal-header-r',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-cal-jumper',
    variables: ['--z-cal-jumper-column-gap', '--z-cal-jumper-input-width'],
    variant: false,
  },
  {
    selector: 'z-cal-jumper-month',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-cal-jumper-year',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-cal-marked',
    variables: [
      '--z-cal-marked-bg',
      '--z-cal-marked-bg-o',
      '--z-cal-marked-border-color',
      '--z-cal-marked-border-color-o',
      '--z-cal-marked-dot-color',
      '--z-cal-marked-dot-color-o',
      '--z-cal-marked-dot-offset',
      '--z-cal-marked-dot-size',
    ],
    variant: false,
  },
  {
    selector: 'z-cal-title',
    variables: ['--z-cal-title-font-weight'],
    variant: false,
  },
  {
    selector: 'z-card',
    variables: [
      '--z-card-adjacent-padding',
      '--z-card-bg',
      '--z-card-bg-o',
      '--z-card-border-color',
      '--z-card-border-color-o',
      '--z-card-border-width',
      '--z-card-color',
      '--z-card-color-o',
      '--z-card-header-footer-padding',
      '--z-card-padding',
      '--z-card-radius',
      '--z-card-shadow',
    ],
    variant: false,
  },
  {
    selector: 'z-card-body',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-card-danger',
    variables: [
      '--z-card-bg',
      '--z-card-bg-o',
      '--z-card-border-color',
      '--z-card-border-color-o',
      '--z-card-border-width',
      '--z-card-color',
      '--z-card-color-o',
    ],
    variant: true,
  },
  {
    selector: 'z-card-footer',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-card-header',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-card-info',
    variables: [
      '--z-card-bg',
      '--z-card-bg-o',
      '--z-card-border-color',
      '--z-card-border-color-o',
      '--z-card-border-width',
      '--z-card-color',
      '--z-card-color-o',
    ],
    variant: true,
  },
  {
    selector: 'z-card-muted',
    variables: [
      '--z-card-bg',
      '--z-card-bg-o',
      '--z-card-border-color',
      '--z-card-border-color-o',
      '--z-card-border-width',
      '--z-card-color',
      '--z-card-color-o',
    ],
    variant: true,
  },
  {
    selector: 'z-card-primary',
    variables: [
      '--z-card-bg',
      '--z-card-bg-o',
      '--z-card-border-color',
      '--z-card-border-color-o',
      '--z-card-border-width',
      '--z-card-color',
      '--z-card-color-o',
    ],
    variant: true,
  },
  {
    selector: 'z-card-secondary',
    variables: [
      '--z-card-bg',
      '--z-card-bg-o',
      '--z-card-border-color',
      '--z-card-border-color-o',
      '--z-card-border-width',
      '--z-card-color',
      '--z-card-color-o',
    ],
    variant: true,
  },
  {
    selector: 'z-card-success',
    variables: [
      '--z-card-bg',
      '--z-card-bg-o',
      '--z-card-border-color',
      '--z-card-border-color-o',
      '--z-card-border-width',
      '--z-card-color',
      '--z-card-color-o',
    ],
    variant: true,
  },
  {
    selector: 'z-card-title',
    variables: [
      '--z-card-title-font-size',
      '--z-card-title-height',
      '--z-card-title-tracking',
      '--z-card-title-weight',
    ],
    variant: false,
  },
  {
    selector: 'z-card-warning',
    variables: [
      '--z-card-bg',
      '--z-card-bg-o',
      '--z-card-border-color',
      '--z-card-border-color-o',
      '--z-card-border-width',
      '--z-card-color',
      '--z-card-color-o',
    ],
    variant: true,
  },
  {
    selector: 'z-checkbox',
    variables: [
      '--z-form-radio-border-color',
      '--z-form-radio-border-color-o',
      '--z-form-radio-checked-bg',
      '--z-form-radio-checked-bg-o',
      '--z-form-radio-checked-border-color',
      '--z-form-radio-checked-border-color-o',
      '--z-form-radio-focus-ring-color',
      '--z-form-radio-focus-ring-color-o',
      '--z-form-radio-indeterminate-bg',
      '--z-form-radio-indeterminate-bg-o',
      '--z-form-radio-indeterminate-border-color',
      '--z-form-radio-indeterminate-border-color-o',
    ],
    variant: false,
  },
  {
    selector: 'z-close',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-codespan',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-comment',
    variables: ['--z-comment-padding'],
    variant: false,
  },
  {
    selector: 'z-comment-avatar',
    variables: [
      '--z-comment-avatar-bg',
      '--z-comment-avatar-bg-o',
      '--z-comment-avatar-radius',
      '--z-comment-avatar-size',
    ],
    variant: false,
  },
  {
    selector: 'z-comment-body',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-comment-header',
    variables: ['--z-comment-header-margin'],
    variant: false,
  },
  {
    selector: 'z-comment-list',
    variables: [
      '--z-comment-list-gap',
      '--z-comment-nested-border-color',
      '--z-comment-nested-border-color-o',
      '--z-comment-nested-border-width',
      '--z-comment-nested-item-gap',
      '--z-comment-nested-item-margin',
      '--z-comment-nested-margin',
      '--z-comment-nested-margin-top',
    ],
    variant: false,
  },
  {
    selector: 'z-comment-meta',
    variables: [
      '--z-comment-meta-font-size',
      '--z-comment-meta-line-height',
      '--z-comment-meta-margin-top',
    ],
    variant: false,
  },
  {
    selector: 'z-comment-primary',
    variables: [
      '--z-comment-primary-bg',
      '--z-comment-primary-bg-o',
      '--z-comment-primary-color',
      '--z-comment-primary-color-o',
      '--z-comment-primary-radius',
    ],
    variant: false,
  },
  {
    selector: 'z-comment-title',
    variables: ['--z-comment-title-font-size', '--z-comment-title-font-weight'],
    variant: false,
  },
  {
    selector: 'z-container',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-container-expand',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-container-expand-left',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-container-expand-right',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-container-item-padding-remove-left',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-container-item-padding-remove-right',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-container-large',
    variables: [],
    variant: true,
  },
  {
    selector: 'z-container-small',
    variables: [],
    variant: true,
  },
  {
    selector: 'z-container-xlarge',
    variables: [],
    variant: true,
  },
  {
    selector: 'z-container-xsmall',
    variables: [],
    variant: true,
  },
  {
    selector: 'z-custom-select-item-check',
    variables: ['--z-custom-select-item-check-margin'],
    variant: false,
  },
  {
    selector: 'z-custom-select-item-icon',
    variables: ['--z-custom-select-item-icon-margin'],
    variant: false,
  },
  {
    selector: 'z-custom-select-item-text',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-custom-select-item-wrapper',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-custom-select-list',
    variables: ['--z-custom-select-list-max-height', '--z-nav-item-color'],
    variant: false,
  },
  {
    selector: 'z-custom-select-search',
    variables: [
      '--z-custom-select-search-icon-margin',
      '--z-custom-select-search-icon-opacity',
      '--z-custom-select-search-input-padding',
      '--z-custom-select-search-padding',
    ],
    variant: false,
  },
  {
    selector: 'z-datepicker-dropdown',
    variables: ['--z-datepicker-spacing'],
    variant: false,
  },
  {
    selector: 'z-datepicker-time',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-disabled',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-divider-small',
    variables: [
      '--z-divider-small-border-color',
      '--z-divider-small-border-color-o',
      '--z-divider-small-width',
    ],
    variant: false,
  },
  {
    selector: 'z-divider-vertical',
    variables: [
      '--z-divider-vertical-border-color',
      '--z-divider-vertical-border-color-o',
      '--z-divider-vertical-height',
    ],
    variant: false,
  },
  {
    selector: 'z-dotnav',
    variables: ['--z-dotnav-item-padding'],
    variant: false,
  },
  {
    selector: 'z-dotnav-vertical',
    variables: ['--z-dotnav-vertical-item-padding-top'],
    variant: false,
  },
  {
    selector: 'z-drop',
    variables: [
      '--z-drop-width',
      '--z-drop-z-index',
      '--z-position-offset',
      '--z-position-viewport-offset',
    ],
    variant: false,
  },
  {
    selector: 'z-drop-parent-icon',
    variables: ['--z-drop-icon-margin', '--z-drop-icon-transition'],
    variant: false,
  },
  {
    selector: 'z-dropbar',
    variables: ['--z-position-offset', '--z-position-shift-offset', '--z-position-viewport-offset'],
    variant: false,
  },
  {
    selector: 'z-dropbar-lg',
    variables: ['--z-dropbar-lg-padding'],
    variant: false,
  },
  {
    selector: 'z-dropcap',
    variables: [
      '--z-dropcap-font-size',
      '--z-dropcap-line-height',
      '--z-dropcap-margin-block-end',
      '--z-dropcap-margin-inline-end',
      '--z-dropcap-moz-margin-block-start',
    ],
    variant: false,
  },
  {
    selector: 'z-dropdown',
    variables: [
      '--z-dropdown-bg',
      '--z-dropdown-bg-o',
      '--z-dropdown-border-color',
      '--z-dropdown-border-color-o',
      '--z-dropdown-border-width',
      '--z-dropdown-color',
      '--z-dropdown-color-o',
      '--z-dropdown-radius',
      '--z-dropdown-shadow',
      '--z-dropdown-width',
      '--z-position-offset',
      '--z-position-viewport-offset',
    ],
    variant: false,
  },
  {
    selector: 'z-dropdown-dropbar',
    variables: [
      '--z-dropdown-dropbar-bg',
      '--z-dropdown-dropbar-bg-o',
      '--z-dropdown-dropbar-shadow',
      '--z-dropdown-dropbar-width',
      '--z-position-viewport-offset',
    ],
    variant: false,
  },
  {
    selector: 'z-dropdown-nav',
    variables: [
      '--z-dropdown-nav-divider-border-color',
      '--z-dropdown-nav-divider-border-color-o',
      '--z-dropdown-nav-divider-border-width',
      '--z-dropdown-nav-divider-margin',
      '--z-dropdown-nav-header-margin',
      '--z-dropdown-nav-header-padding',
      '--z-dropdown-nav-header-weight',
      '--z-dropdown-nav-item-hover-bg',
      '--z-dropdown-nav-item-hover-bg-o',
      '--z-dropdown-nav-item-hover-color',
      '--z-dropdown-nav-item-hover-color-o',
      '--z-dropdown-nav-item-margin',
      '--z-dropdown-nav-item-padding',
      '--z-nav-divider-color',
      '--z-nav-divider-color-o',
      '--z-nav-divider-margin',
      '--z-nav-divider-style',
      '--z-nav-divider-width',
      '--z-nav-header-font-weight',
      '--z-nav-header-margin',
      '--z-nav-header-padding',
      '--z-nav-item-color',
      '--z-nav-item-hover-bg',
      '--z-nav-item-hover-bg-o',
      '--z-nav-item-hover-color',
      '--z-nav-item-hover-color-o',
      '--z-nav-item-margin',
      '--z-nav-item-padding',
      '--z-nav-radius',
    ],
    variant: false,
  },
  {
    selector: 'z-dropnav-dropbar',
    variables: ['--z-dropnav-z'],
    variant: false,
  },
  {
    selector: 'z-fieldset',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-first-column',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-flex',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-flex-top',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-flex-wrap-top',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-focus-visible',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-form-blank',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-form-custom',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-form-danger',
    variables: [
      '--z-form-danger-ring-color',
      '--z-form-danger-ring-color-o',
      '--z-input-pin-focus-ring-color',
      '--z-input-tag-focus-ring-color',
    ],
    variant: false,
  },
  {
    selector: 'z-form-help',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-form-icon',
    variables: ['--z-form-icon-width'],
    variant: false,
  },
  {
    selector: 'z-form-icon-flip',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-form-label',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-form-label-required',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-form-large',
    variables: [
      '--z-interactive-height-multiplier',
      '--z-interactive-padding-block-multiplier',
      '--z-interactive-padding-inline-multiplier',
    ],
    variant: true,
  },
  {
    selector: 'z-form-medium',
    variables: [
      '--z-interactive-height-multiplier',
      '--z-interactive-padding-block-multiplier',
      '--z-interactive-padding-inline-multiplier',
    ],
    variant: true,
  },
  {
    selector: 'z-form-small',
    variables: [
      '--z-form-input-font-size',
      '--z-form-input-line-height',
      '--z-interactive-height-multiplier',
      '--z-interactive-padding-block-multiplier',
      '--z-interactive-padding-inline-multiplier',
    ],
    variant: true,
  },
  {
    selector: 'z-form-xsmall',
    variables: [
      '--z-form-input-font-size',
      '--z-form-input-line-height',
      '--z-interactive-height-multiplier',
      '--z-interactive-padding-block-multiplier',
      '--z-interactive-padding-inline-multiplier',
    ],
    variant: true,
  },
  {
    selector: 'z-h1',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-h2',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-h3',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-h4',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-h5',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-h6',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-heading-bullet',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-heading-divider',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-heading-line',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-hero-2xlarge',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-hero-3xlarge',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-hero-large',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-hero-medium',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-hero-small',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-hero-xlarge',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-hr',
    variables: ['--z-hr-color', '--z-hr-color-o'],
    variant: false,
  },
  {
    selector: 'z-icon',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-icon-image',
    variables: ['--z-icon-image-size'],
    variant: false,
  },
  {
    selector: 'z-inline-clip',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-input',
    variables: [
      '--z-form-focus-ring-color',
      '--z-form-focus-ring-color-o',
      '--z-form-icon-width',
      '--z-form-input-bg',
      '--z-form-input-border-color',
      '--z-form-input-border-color-o',
      '--z-form-input-color',
      '--z-form-input-color-o',
      '--z-form-input-height',
      '--z-form-input-padding',
      '--z-form-input-padding-block',
      '--z-form-input-padding-inline',
    ],
    variant: false,
  },
  {
    selector: 'z-input-fake',
    variables: [
      '--z-form-focus-ring-color',
      '--z-form-focus-ring-color-o',
      '--z-form-input-bg',
      '--z-form-input-border-color',
      '--z-form-input-border-color-o',
      '--z-form-input-color',
      '--z-form-input-color-o',
      '--z-form-input-height',
      '--z-form-input-padding',
      '--z-form-input-padding-block',
      '--z-form-input-padding-inline',
    ],
    variant: false,
  },
  {
    selector: 'z-input-pin',
    variables: [
      '--z-form-input-height',
      '--z-input-pin-focus-ring-color',
      '--z-input-pin-focus-ring-color-o',
      '--z-input-pin-radius',
      '--z-input-pin-separated-gap',
      '--z-input-pin-separated-input-shadow',
      '--z-input-pin-shadow',
    ],
    variant: false,
  },
  {
    selector: 'z-input-pin-separated',
    variables: ['--z-input-pin-separated-gap', '--z-input-pin-separated-input-shadow'],
    variant: false,
  },
  {
    selector: 'z-input-range',
    variables: [
      '--z-input-range-label-offset-y',
      '--z-input-range-track-height',
      '--z-input-range-track-radius',
    ],
    variant: false,
  },
  {
    selector: 'z-input-range-fill',
    variables: ['--z-input-range-fill-bg', '--z-input-range-fill-bg-o'],
    variant: false,
  },
  {
    selector: 'z-input-range-knob',
    variables: [
      '--z-input-range-knob-bg',
      '--z-input-range-knob-bg-o',
      '--z-input-range-knob-border-color',
      '--z-input-range-knob-border-color-o',
      '--z-input-range-knob-radius',
      '--z-input-range-knob-shadow',
      '--z-input-range-knob-size',
    ],
    variant: false,
  },
  {
    selector: 'z-input-range-label',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-input-range-label-bottom',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-input-range-label-top',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-input-range-runnable',
    variables: ['--z-input-range-track-bg', '--z-input-range-track-bg-o'],
    variant: false,
  },
  {
    selector: 'z-input-tag',
    variables: [
      '--z-input-tag-border-color',
      '--z-input-tag-border-color-o',
      '--z-input-tag-border-width',
      '--z-input-tag-focus-ring-color',
      '--z-input-tag-focus-ring-color-o',
      '--z-input-tag-gap',
      '--z-input-tag-min-height',
      '--z-input-tag-padding',
      '--z-input-tag-radius',
      '--z-input-tag-shadow',
    ],
    variant: false,
  },
  {
    selector: 'z-input-tag-list',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-input-time',
    variables: ['--z-input-time-column-gap', '--z-input-time-input-width'],
    variant: false,
  },
  {
    selector: 'z-kbd',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-label',
    variables: [
      '--z-label-bg',
      '--z-label-bg-o',
      '--z-label-border',
      '--z-label-border-o',
      '--z-label-color',
      '--z-label-color-o',
    ],
    variant: false,
  },
  {
    selector: 'z-label-danger',
    variables: [
      '--z-label-bg',
      '--z-label-bg-o',
      '--z-label-border',
      '--z-label-border-o',
      '--z-label-color',
      '--z-label-color-o',
    ],
    variant: true,
  },
  {
    selector: 'z-label-destructive',
    variables: [
      '--z-label-bg',
      '--z-label-bg-o',
      '--z-label-border',
      '--z-label-border-o',
      '--z-label-color',
      '--z-label-color-o',
    ],
    variant: true,
  },
  {
    selector: 'z-label-info',
    variables: [
      '--z-label-bg',
      '--z-label-bg-o',
      '--z-label-border',
      '--z-label-border-o',
      '--z-label-color',
      '--z-label-color-o',
    ],
    variant: true,
  },
  {
    selector: 'z-label-primary',
    variables: [
      '--z-label-bg',
      '--z-label-bg-o',
      '--z-label-border',
      '--z-label-border-o',
      '--z-label-color',
      '--z-label-color-o',
    ],
    variant: true,
  },
  {
    selector: 'z-label-secondary',
    variables: [
      '--z-label-bg',
      '--z-label-bg-o',
      '--z-label-border',
      '--z-label-border-o',
      '--z-label-color',
      '--z-label-color-o',
    ],
    variant: true,
  },
  {
    selector: 'z-label-success',
    variables: [
      '--z-label-bg',
      '--z-label-bg-o',
      '--z-label-border',
      '--z-label-border-o',
      '--z-label-color',
      '--z-label-color-o',
    ],
    variant: true,
  },
  {
    selector: 'z-label-warning',
    variables: [
      '--z-label-bg',
      '--z-label-bg-o',
      '--z-label-border',
      '--z-label-border-o',
      '--z-label-color',
      '--z-label-color-o',
    ],
    variant: true,
  },
  {
    selector: 'z-layout-medium',
    variables: [
      '--z-global-font-size',
      '--z-global-font-size-small',
      '--z-global-line-height',
      '--z-global-line-height-small',
    ],
    variant: true,
  },
  {
    selector: 'z-layout-small',
    variables: [
      '--z-global-font-size',
      '--z-global-font-size-small',
      '--z-global-line-height',
      '--z-global-line-height-small',
    ],
    variant: true,
  },
  {
    selector: 'z-leader',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-leader-fill',
    variables: ['--z-leader-spacing'],
    variant: false,
  },
  {
    selector: 'z-leader-hide',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-lightbox',
    variables: ['--z-lightbox-transition', '--z-lightbox-z-index'],
    variant: false,
  },
  {
    selector: 'z-lightbox-caption',
    variables: [
      '--z-lightbox-caption-bg',
      '--z-lightbox-caption-bg-o',
      '--z-lightbox-caption-color',
      '--z-lightbox-caption-color-o',
      '--z-lightbox-caption-padding',
    ],
    variant: false,
  },
  {
    selector: 'z-lightbox-dotnav',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-lightbox-iframe',
    variables: ['--z-lightbox-iframe-height', '--z-lightbox-iframe-width'],
    variant: false,
  },
  {
    selector: 'z-lightbox-page',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-lightbox-thumbnav',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-lightbox-zoom',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-link',
    variables: ['--z-link-font-weight', '--z-link-underline-offset'],
    variant: false,
  },
  {
    selector: 'z-link-muted',
    variables: ['--z-link-muted-color', '--z-link-muted-color-o', '--z-link-muted-font-weight'],
    variant: false,
  },
  {
    selector: 'z-link-reset',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-link-text',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-link-toggle',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-list-circle',
    variables: ['--z-list-indent'],
    variant: false,
  },
  {
    selector: 'z-list-decimal',
    variables: ['--z-list-indent'],
    variant: false,
  },
  {
    selector: 'z-list-disc',
    variables: ['--z-list-indent'],
    variant: false,
  },
  {
    selector: 'z-list-divider',
    variables: [
      '--z-list-divider-border-color',
      '--z-list-divider-border-color-o',
      '--z-list-divider-border-width',
      '--z-list-divider-item-margin-top',
      '--z-list-divider-item-padding-top',
    ],
    variant: false,
  },
  {
    selector: 'z-list-hyphen',
    variables: ['--z-list-indent'],
    variant: false,
  },
  {
    selector: 'z-list-muted',
    variables: ['--z-list-marker-muted-color', '--z-list-marker-muted-color-o'],
    variant: false,
  },
  {
    selector: 'z-list-primary',
    variables: ['--z-list-marker-primary-color', '--z-list-marker-primary-color-o'],
    variant: false,
  },
  {
    selector: 'z-list-secondary',
    variables: ['--z-list-marker-secondary-color', '--z-list-marker-secondary-color-o'],
    variant: false,
  },
  {
    selector: 'z-list-square',
    variables: ['--z-list-indent'],
    variant: false,
  },
  {
    selector: 'z-list-striped',
    variables: [
      '--z-list-striped-background-color',
      '--z-list-striped-background-color-o',
      '--z-list-striped-border-color',
      '--z-list-striped-border-color-o',
      '--z-list-striped-border-width',
      '--z-list-striped-item-padding',
    ],
    variant: false,
  },
  {
    selector: 'z-margin-auto-vertical',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-modal',
    variables: [
      '--z-modal-overlay-bg',
      '--z-modal-overlay-bg-o',
      '--z-modal-overlay-blur',
      '--z-modal-padding',
      '--z-modal-padding-body',
      '--z-modal-padding-bottom-scrollable',
      '--z-modal-padding-footer',
      '--z-modal-padding-header',
      '--z-modal-padding-top-after-header',
      '--z-modal-padding-top-after-scrollable',
      '--z-modal-padding-top-between',
      '--z-modal-radius',
      '--z-modal-transition',
      '--z-modal-z-index',
    ],
    variant: false,
  },
  {
    selector: 'z-modal-body',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-modal-dialog',
    variables: [
      '--z-modal-dialog-border-color',
      '--z-modal-dialog-border-color-o',
      '--z-modal-dialog-border-width',
      '--z-modal-dialog-transform',
      '--z-modal-dialog-transition',
      '--z-modal-dialog-width',
    ],
    variant: false,
  },
  {
    selector: 'z-modal-footer',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-modal-full',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-modal-header',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-modal-page',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-modal-title',
    variables: [
      '--z-modal-title-line-height',
      '--z-modal-title-size',
      '--z-modal-title-tracking',
      '--z-modal-title-weight',
    ],
    variant: false,
  },
  {
    selector: 'z-nav',
    variables: [
      '--z-nav-item-color',
      '--z-nav-item-color-o',
      '--z-nav-item-hover-color',
      '--z-nav-item-hover-color-o',
      '--z-nav-item-margin',
      '--z-nav-item-padding',
      '--z-nav-radius',
      '--z-nav-sub-border-w',
      '--z-nav-sub-item-margin',
      '--z-nav-sub-item-padding',
    ],
    variant: false,
  },
  {
    selector: 'z-nav-alt',
    variables: [
      '--z-nav-item-active-bg',
      '--z-nav-item-active-bg-o',
      '--z-nav-item-active-color',
      '--z-nav-item-active-color-o',
      '--z-nav-item-active-font-weight',
      '--z-nav-item-color',
      '--z-nav-item-hover-bg',
      '--z-nav-item-hover-bg-o',
      '--z-nav-item-hover-color',
      '--z-nav-item-hover-color-o',
      '--z-nav-item-margin',
      '--z-nav-item-padding',
      '--z-nav-sub-item-margin',
      '--z-nav-sub-item-padding',
    ],
    variant: true,
  },
  {
    selector: 'z-nav-cmd',
    variables: ['--z-nav-item-padding'],
    variant: true,
  },
  {
    selector: 'z-nav-default',
    variables: [
      '--z-nav-item-color',
      '--z-nav-item-color-o',
      '--z-nav-item-hover-color',
      '--z-nav-item-hover-color-o',
    ],
    variant: true,
  },
  {
    selector: 'z-nav-divider',
    variables: ['--z-nav-divider-color', '--z-nav-divider-color-o'],
    variant: false,
  },
  {
    selector: 'z-nav-header',
    variables: ['--z-nav-header-margin', '--z-nav-header-padding'],
    variant: false,
  },
  {
    selector: 'z-nav-parent-icon',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-nav-sub',
    variables: [
      '--z-nav-item-color',
      '--z-nav-item-color-o',
      '--z-nav-sub-active-bg',
      '--z-nav-sub-active-bg-o',
      '--z-nav-sub-border',
      '--z-nav-sub-border-o',
    ],
    variant: false,
  },
  {
    selector: 'z-notification',
    variables: [
      '--z-notification-offset-x',
      '--z-notification-offset-y',
      '--z-notification-width',
      '--z-notification-z-index',
    ],
    variant: false,
  },
  {
    selector: 'z-notification-bottom-center',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-notification-bottom-left',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-notification-bottom-right',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-notification-close',
    variables: [
      '--z-notification-close-color',
      '--z-notification-close-color-o',
      '--z-notification-close-offset-x',
      '--z-notification-close-offset-y',
      '--z-notification-close-padding',
    ],
    variant: false,
  },
  {
    selector: 'z-notification-message',
    variables: [
      '--z-notification-bg',
      '--z-notification-bg-o',
      '--z-notification-border-color',
      '--z-notification-border-color-o',
      '--z-notification-border-width',
      '--z-notification-color',
      '--z-notification-color-o',
      '--z-notification-gap',
      '--z-notification-padding',
      '--z-notification-radius',
      '--z-notification-shadow',
    ],
    variant: false,
  },
  {
    selector: 'z-notification-message-danger',
    variables: [
      '--z-notification-bg',
      '--z-notification-bg-o',
      '--z-notification-border-color',
      '--z-notification-border-color-o',
      '--z-notification-close-color',
      '--z-notification-close-color-o',
      '--z-notification-color',
      '--z-notification-color-o',
    ],
    variant: true,
  },
  {
    selector: 'z-notification-message-info',
    variables: [
      '--z-notification-bg',
      '--z-notification-bg-o',
      '--z-notification-border-color',
      '--z-notification-border-color-o',
      '--z-notification-close-color',
      '--z-notification-close-color-o',
      '--z-notification-color',
      '--z-notification-color-o',
    ],
    variant: true,
  },
  {
    selector: 'z-notification-message-muted',
    variables: [
      '--z-notification-bg',
      '--z-notification-bg-o',
      '--z-notification-border-color',
      '--z-notification-border-color-o',
      '--z-notification-close-color',
      '--z-notification-close-color-o',
      '--z-notification-color',
      '--z-notification-color-o',
    ],
    variant: true,
  },
  {
    selector: 'z-notification-message-primary',
    variables: [
      '--z-notification-bg',
      '--z-notification-bg-o',
      '--z-notification-border-color',
      '--z-notification-border-color-o',
      '--z-notification-close-color',
      '--z-notification-close-color-o',
      '--z-notification-color',
      '--z-notification-color-o',
    ],
    variant: true,
  },
  {
    selector: 'z-notification-message-secondary',
    variables: [
      '--z-notification-bg',
      '--z-notification-bg-o',
      '--z-notification-border-color',
      '--z-notification-border-color-o',
      '--z-notification-close-color',
      '--z-notification-close-color-o',
      '--z-notification-color',
      '--z-notification-color-o',
    ],
    variant: true,
  },
  {
    selector: 'z-notification-message-success',
    variables: [
      '--z-notification-bg',
      '--z-notification-bg-o',
      '--z-notification-border-color',
      '--z-notification-border-color-o',
      '--z-notification-close-color',
      '--z-notification-close-color-o',
      '--z-notification-color',
      '--z-notification-color-o',
    ],
    variant: true,
  },
  {
    selector: 'z-notification-message-warning',
    variables: [
      '--z-notification-bg',
      '--z-notification-bg-o',
      '--z-notification-border-color',
      '--z-notification-border-color-o',
      '--z-notification-close-color',
      '--z-notification-close-color-o',
      '--z-notification-color',
      '--z-notification-color-o',
    ],
    variant: true,
  },
  {
    selector: 'z-notification-top-center',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-notification-top-right',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-offcanvas',
    variables: ['--z-offcanvas-bar-width', '--z-offcanvas-z-index'],
    variant: false,
  },
  {
    selector: 'z-offcanvas-bar',
    variables: ['--z-offcanvas-bar-border-width', '--z-offcanvas-bar-transition'],
    variant: false,
  },
  {
    selector: 'z-offcanvas-bar-animation',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-offcanvas-container',
    variables: ['--z-offcanvas-container-transition'],
    variant: false,
  },
  {
    selector: 'z-offcanvas-container-animation',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-offcanvas-flip',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-offcanvas-overlay',
    variables: [
      '--z-offcanvas-overlay-bg',
      '--z-offcanvas-overlay-bg-o',
      '--z-offcanvas-overlay-blur',
      '--z-offcanvas-overlay-opacity',
      '--z-offcanvas-overlay-transition',
    ],
    variant: false,
  },
  {
    selector: 'z-offcanvas-page',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-offcanvas-reveal',
    variables: ['--z-offcanvas-reveal-transition'],
    variant: false,
  },
  {
    selector: 'z-open',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-overflow-auto',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-overflow-hidden',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-pagination',
    variables: [
      '--z-pagination-gap',
      '--z-pagination-item-font-size',
      '--z-pagination-item-font-weight',
      '--z-pagination-item-gap',
      '--z-pagination-item-height',
      '--z-pagination-item-icon-size',
      '--z-pagination-item-line-height',
      '--z-pagination-item-padding',
      '--z-pagination-item-padding-block',
      '--z-pagination-item-padding-inline',
      '--z-pagination-item-radius',
      '--z-pagination-item-shadow',
    ],
    variant: false,
  },
  {
    selector: 'z-pagination-large',
    variables: [
      '--z-interactive-height-multiplier',
      '--z-interactive-padding-block-multiplier',
      '--z-interactive-padding-inline-multiplier',
    ],
    variant: true,
  },
  {
    selector: 'z-pagination-medium',
    variables: [
      '--z-interactive-height-multiplier',
      '--z-interactive-padding-block-multiplier',
      '--z-interactive-padding-inline-multiplier',
    ],
    variant: true,
  },
  {
    selector: 'z-pagination-small',
    variables: [
      '--z-interactive-height-multiplier',
      '--z-interactive-padding-block-multiplier',
      '--z-interactive-padding-inline-multiplier',
      '--z-pagination-item-font-size',
      '--z-pagination-item-icon-size',
      '--z-pagination-item-line-height',
    ],
    variant: true,
  },
  {
    selector: 'z-pagination-xsmall',
    variables: [
      '--z-interactive-height-multiplier',
      '--z-interactive-padding-block-multiplier',
      '--z-interactive-padding-inline-multiplier',
      '--z-pagination-item-font-size',
      '--z-pagination-item-icon-size',
      '--z-pagination-item-line-height',
    ],
    variant: true,
  },
  {
    selector: 'z-paragraph',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-placeholder',
    variables: [
      '--z-placeholder-border-color',
      '--z-placeholder-border-color-o',
      '--z-placeholder-margin-bottom',
      '--z-placeholder-padding',
    ],
    variant: false,
  },
  {
    selector: 'z-position-absolute',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-position-bottom',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-position-bottom-center',
    variables: ['--z-position-translate-x'],
    variant: false,
  },
  {
    selector: 'z-position-bottom-left',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-position-bottom-right',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-position-center',
    variables: ['--z-position-translate-x', '--z-position-translate-y'],
    variant: false,
  },
  {
    selector: 'z-position-center-horizontal',
    variables: ['--z-position-translate-x'],
    variant: false,
  },
  {
    selector: 'z-position-center-left',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-position-center-left-out',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-position-center-right',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-position-center-right-out',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-position-center-vertical',
    variables: ['--z-position-translate-y'],
    variant: false,
  },
  {
    selector: 'z-position-cover',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-position-fixed',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-position-large',
    variables: ['--z-position-margin-offset'],
    variant: false,
  },
  {
    selector: 'z-position-left',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-position-medium',
    variables: ['--z-position-margin-offset'],
    variant: false,
  },
  {
    selector: 'z-position-relative',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-position-right',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-position-small',
    variables: ['--z-position-margin-offset'],
    variant: false,
  },
  {
    selector: 'z-position-sticky',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-position-top',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-position-top-center',
    variables: ['--z-position-translate-x'],
    variant: false,
  },
  {
    selector: 'z-position-top-left',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-position-top-right',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-position-z-index',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-position-z-index-high',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-position-z-index-highest',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-position-z-index-negative',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-position-z-index-zero',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-preserve',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-preserve-width',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-progress',
    variables: [
      '--z-progress-height',
      '--z-progress-margin-bottom',
      '--z-progress-radius',
      '--z-progress-track-color',
      '--z-progress-track-color-o',
      '--z-progress-transition',
      '--z-progress-value-color',
      '--z-progress-value-color-o',
    ],
    variant: false,
  },
  {
    selector: 'z-radio',
    variables: [
      '--z-form-radio-border-color',
      '--z-form-radio-border-color-o',
      '--z-form-radio-checked-bg',
      '--z-form-radio-checked-bg-o',
      '--z-form-radio-checked-border-color',
      '--z-form-radio-checked-border-color-o',
      '--z-form-radio-focus-ring-color',
      '--z-form-radio-focus-ring-color-o',
    ],
    variant: false,
  },
  {
    selector: 'z-range',
    variables: [
      '--z-range-thumb-bg',
      '--z-range-thumb-bg-o',
      '--z-range-thumb-border-color',
      '--z-range-thumb-border-color-o',
      '--z-range-thumb-margin-top',
      '--z-range-thumb-radius',
      '--z-range-thumb-size',
      '--z-range-track-bg',
      '--z-range-track-bg-o',
      '--z-range-track-height',
      '--z-range-track-radius',
    ],
    variant: false,
  },
  {
    selector: 'z-resize',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-resize-horizontal',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-resize-vertical',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-responsive-height',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-responsive-width',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-rounded',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-rounded-small',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-select',
    variables: [
      '--z-form-focus-ring-color',
      '--z-form-focus-ring-color-o',
      '--z-form-input-bg',
      '--z-form-input-border-color',
      '--z-form-input-border-color-o',
      '--z-form-input-color',
      '--z-form-input-color-o',
      '--z-form-input-height',
      '--z-form-input-padding',
      '--z-form-input-padding-block',
      '--z-form-input-padding-inline',
    ],
    variant: false,
  },
  {
    selector: 'z-shadow',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-shadow-small',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-slidenav',
    variables: [
      '--z-slidenav-active-bg',
      '--z-slidenav-active-bg-o',
      '--z-slidenav-active-color',
      '--z-slidenav-active-color-o',
      '--z-slidenav-bg',
      '--z-slidenav-bg-o',
      '--z-slidenav-border-color',
      '--z-slidenav-border-color-o',
      '--z-slidenav-border-width',
      '--z-slidenav-height',
      '--z-slidenav-hover-bg',
      '--z-slidenav-hover-bg-o',
      '--z-slidenav-hover-color',
      '--z-slidenav-hover-color-o',
      '--z-slidenav-radius',
      '--z-slidenav-shadow',
      '--z-slidenav-svg-height',
      '--z-slidenav-svg-width',
      '--z-slidenav-width',
    ],
    variant: false,
  },
  {
    selector: 'z-slidenav-container',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-slidenav-lg',
    variables: ['--z-slidenav-large-padding'],
    variant: false,
  },
  {
    selector: 'z-slider',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-slider-container',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-slider-items',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-slideshow',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-slideshow-items',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-sortable',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-sortable-drag',
    variables: ['--z-sortable-drag-z-index'],
    variant: false,
  },
  {
    selector: 'z-sortable-empty',
    variables: ['--z-sortable-empty-min-height'],
    variant: false,
  },
  {
    selector: 'z-sortable-handle',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-sortable-placeholder',
    variables: ['--z-sortable-placeholder-opacity'],
    variant: false,
  },
  {
    selector: 'z-spinner',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-sticky',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-sticky-fixed',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-sticky-placeholder',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-subnav',
    variables: [
      '--z-subnav-item-color',
      '--z-subnav-item-color-o',
      '--z-subnav-item-hover-color',
      '--z-subnav-item-hover-color-o',
    ],
    variant: false,
  },
  {
    selector: 'z-subnav-primary',
    variables: [
      '--z-subnav-item-active-background',
      '--z-subnav-item-active-background-o',
      '--z-subnav-item-active-color',
      '--z-subnav-item-active-color-o',
      '--z-subnav-item-active-hover-background',
      '--z-subnav-item-active-hover-background-o',
      '--z-subnav-item-active-hover-color',
      '--z-subnav-item-active-hover-color-o',
    ],
    variant: true,
  },
  {
    selector: 'z-svg',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-tab',
    variables: ['--z-tab-item-padding', '--z-tab-link-gap'],
    variant: false,
  },
  {
    selector: 'z-tab-alt',
    variables: [
      '--z-tab-alt-padding',
      '--z-tab-alt-padding-inner',
      '--z-tab-alt-radius',
      '--z-tab-alt-radius-inner',
    ],
    variant: false,
  },
  {
    selector: 'z-tab-bottom',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-tab-left',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-tab-right',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-table',
    variables: ['--z-table-cell-padding'],
    variant: false,
  },
  {
    selector: 'z-table-divider',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-table-expand',
    variables: ['--z-table-expand-min-width'],
    variant: false,
  },
  {
    selector: 'z-table-hover',
    variables: ['--z-table-hover-bg', '--z-table-hover-bg-o', '--z-table-hover-transition'],
    variant: false,
  },
  {
    selector: 'z-table-large',
    variables: ['--z-table-cell-padding'],
    variant: true,
  },
  {
    selector: 'z-table-link',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-table-middle',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-table-responsive',
    variables: [
      '--z-table-responsive-label-color',
      '--z-table-responsive-label-color-o',
      '--z-table-responsive-label-size',
      '--z-table-responsive-label-weight',
      '--z-table-responsive-label-width',
      '--z-table-responsive-padding-y',
    ],
    variant: false,
  },
  {
    selector: 'z-table-responsive-compact',
    variables: ['--z-table-responsive-label-width', '--z-table-responsive-padding-y'],
    variant: true,
  },
  {
    selector: 'z-table-shrink',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-table-small',
    variables: ['--z-table-cell-padding'],
    variant: true,
  },
  {
    selector: 'z-table-striped',
    variables: ['--z-table-striped-bg', '--z-table-striped-bg-o'],
    variant: false,
  },
  {
    selector: 'z-tag',
    variables: [
      '--z-tag-bg',
      '--z-tag-bg-o',
      '--z-tag-color',
      '--z-tag-color-o',
      '--z-tag-font-size',
      '--z-tag-gap',
      '--z-tag-height',
      '--z-tag-hover-duration',
      '--z-tag-hover-opacity',
      '--z-tag-line-height',
      '--z-tag-padding',
      '--z-tag-radius',
    ],
    variant: false,
  },
  {
    selector: 'z-tag-danger',
    variables: ['--z-tag-bg', '--z-tag-bg-o', '--z-tag-color', '--z-tag-color-o'],
    variant: true,
  },
  {
    selector: 'z-tag-info',
    variables: ['--z-tag-bg', '--z-tag-bg-o', '--z-tag-color', '--z-tag-color-o'],
    variant: true,
  },
  {
    selector: 'z-tag-muted',
    variables: ['--z-tag-bg', '--z-tag-bg-o', '--z-tag-color', '--z-tag-color-o'],
    variant: true,
  },
  {
    selector: 'z-tag-primary',
    variables: ['--z-tag-bg', '--z-tag-bg-o', '--z-tag-color', '--z-tag-color-o'],
    variant: true,
  },
  {
    selector: 'z-tag-secondary',
    variables: ['--z-tag-bg', '--z-tag-bg-o', '--z-tag-color', '--z-tag-color-o'],
    variant: true,
  },
  {
    selector: 'z-tag-success',
    variables: ['--z-tag-bg', '--z-tag-bg-o', '--z-tag-color', '--z-tag-color-o'],
    variant: true,
  },
  {
    selector: 'z-tag-warning',
    variables: ['--z-tag-bg', '--z-tag-bg-o', '--z-tag-color', '--z-tag-color-o'],
    variant: true,
  },
  {
    selector: 'z-text-2xlarge',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-text-2xsmall',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-text-3xlarge',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-text-background',
    variables: ['--z-text-background-bg', '--z-text-background-image'],
    variant: false,
  },
  {
    selector: 'z-text-base',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-text-break',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-text-center',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-text-large',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-text-lead',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-text-medium',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-text-meta',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-text-right',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-text-small',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-text-truncate',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-text-xlarge',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-text-xsmall',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-textarea',
    variables: [
      '--z-form-focus-ring-color',
      '--z-form-focus-ring-color-o',
      '--z-form-input-bg',
      '--z-form-input-border-color',
      '--z-form-input-border-color-o',
      '--z-form-input-color',
      '--z-form-input-color-o',
      '--z-form-input-height',
      '--z-form-input-padding',
      '--z-form-input-padding-block',
      '--z-form-input-padding-inline',
    ],
    variant: false,
  },
  {
    selector: 'z-thumbnav',
    variables: [
      '--z-thumbnav-item-padding-horizontal',
      '--z-thumbnav-overlay-active-opacity',
      '--z-thumbnav-overlay-hover-opacity',
      '--z-thumbnav-overlay-transition',
    ],
    variant: false,
  },
  {
    selector: 'z-thumbnav-vertical',
    variables: ['--z-thumbnav-item-padding-vertical'],
    variant: false,
  },
  {
    selector: 'z-toggle-switch',
    variables: [
      '--z-toggle-switch-bg',
      '--z-toggle-switch-bg-o',
      '--z-toggle-switch-height',
      '--z-toggle-switch-knob-bg',
      '--z-toggle-switch-knob-bg-o',
      '--z-toggle-switch-width',
    ],
    variant: false,
  },
  {
    selector: 'z-toggle-switch-danger',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-toggle-switch-primary',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-tooltip',
    variables: [
      '--z-position-offset',
      '--z-position-viewport-offset',
      '--z-tooltip-bg',
      '--z-tooltip-bg-o',
      '--z-tooltip-color',
      '--z-tooltip-color-o',
      '--z-tooltip-font-size',
      '--z-tooltip-line-height',
      '--z-tooltip-max-width',
      '--z-tooltip-padding',
      '--z-tooltip-radius',
      '--z-tooltip-z-index',
    ],
    variant: false,
  },
  {
    selector: 'z-transform-center',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-transform-origin-bottom-center',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-transform-origin-bottom-left',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-transform-origin-bottom-right',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-transform-origin-center-left',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-transform-origin-center-right',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-transform-origin-top-center',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-transform-origin-top-left',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-transform-origin-top-right',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-transition-disable',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-transition-fade',
    variables: [
      '--z-position-translate-x',
      '--z-position-translate-y',
      '--z-scale-x',
      '--z-scale-y',
      '--z-translate-x',
      '--z-translate-y',
    ],
    variant: false,
  },
  {
    selector: 'z-transition-opaque',
    variables: [],
    variant: false,
  },
  {
    selector: 'z-transition-scale-down',
    variables: ['--z-scale-x', '--z-scale-y'],
    variant: false,
  },
  {
    selector: 'z-transition-scale-up',
    variables: ['--z-scale-x', '--z-scale-y'],
    variant: false,
  },
  {
    selector: 'z-transition-slide-bottom',
    variables: ['--z-translate-y'],
    variant: true,
  },
  {
    selector: 'z-transition-slide-bottom-medium',
    variables: ['--z-translate-y'],
    variant: true,
  },
  {
    selector: 'z-transition-slide-bottom-small',
    variables: ['--z-translate-y'],
    variant: true,
  },
  {
    selector: 'z-transition-slide-left',
    variables: ['--z-translate-x'],
    variant: true,
  },
  {
    selector: 'z-transition-slide-left-medium',
    variables: ['--z-translate-x'],
    variant: true,
  },
  {
    selector: 'z-transition-slide-left-small',
    variables: ['--z-translate-x'],
    variant: true,
  },
  {
    selector: 'z-transition-slide-right',
    variables: ['--z-translate-x'],
    variant: true,
  },
  {
    selector: 'z-transition-slide-right-medium',
    variables: ['--z-translate-x'],
    variant: true,
  },
  {
    selector: 'z-transition-slide-right-small',
    variables: ['--z-translate-x'],
    variant: true,
  },
  {
    selector: 'z-transition-slide-top',
    variables: ['--z-translate-y'],
    variant: true,
  },
  {
    selector: 'z-transition-slide-top-medium',
    variables: ['--z-translate-y'],
    variant: true,
  },
  {
    selector: 'z-transition-slide-top-small',
    variables: ['--z-translate-y'],
    variant: true,
  },
  {
    selector: 'z-transition-slow',
    variables: [],
    variant: false,
  },
];
