export default {
  text: 'Backgrounds',
  items: [
    {
      type: 'vd',
      name: 'bg',
      accepts: 'color-mix',
      description: 'Sets the background color via --bg.',
      keywords: ['background', 'fill', 'surface', 'backdrop', 'color'],
    },
    {
      type: 'vd',
      name: 'bg/o',
      accepts: 'numeric',
      unit: '%',
      min: 0,
      max: 100,
      step: 1,
      description: 'Sets background color + opacity via --bg and --bg-o independently.',
      keywords: ['background', 'fill', 'surface', 'backdrop', 'color', 'transparent', 'alpha'],
    },
    {
      type: 'vd',
      name: 'bg-image',
      accepts: 'raw',
      description: 'Sets background-image via --bg-image. Accepts url() or a gradient string.',
      keywords: ['background', 'image', 'photo', 'gradient', 'url'],
    },
    {
      type: 'cc',
      name: 'bg-image-none',
      description: 'Removes the background image.',
      keywords: ['background', 'image', 'none', 'remove', 'reset'],
    },
    {
      type: 'vd',
      name: 'bg-size',
      accepts: 'raw',
      description: 'Sets background-size via --bg-size. E.g. 50%, 200px.',
      keywords: ['background', 'size', 'scale', 'fit'],
    },
    {
      type: 'cc',
      name: 'bg-cover',
      description: 'Sets background-size: cover. Image fills the entire container.',
      keywords: ['background', 'cover', 'fill', 'size'],
    },
    {
      type: 'cc',
      name: 'bg-contain',
      description: 'Sets background-size: contain. Image fits within the container.',
      keywords: ['background', 'contain', 'fit', 'size'],
    },
    {
      type: 'vd',
      name: 'bg-position',
      accepts: 'raw',
      description: 'Sets background-position via --bg-position. E.g. 50% 25%.',
      keywords: ['background', 'position', 'alignment', 'focal-point'],
    },
    {
      type: 'cc',
      name: 'bg-center',
      description: 'Sets background-position: center.',
      keywords: ['background', 'position', 'center'],
    },
    {
      type: 'cc',
      name: 'bg-top',
      description: 'Sets background-position: top.',
      keywords: ['background', 'position', 'top'],
    },
    {
      type: 'cc',
      name: 'bg-bottom',
      description: 'Sets background-position: bottom.',
      keywords: ['background', 'position', 'bottom'],
    },
    {
      type: 'cc',
      name: 'bg-fixed',
      description: 'Sets background-attachment: fixed. Background stays fixed during scroll.',
      keywords: ['background', 'fixed', 'parallax', 'attachment', 'scroll'],
    },
    {
      type: 'cc',
      name: 'bg-scroll',
      description: 'Sets background-attachment: scroll. Background scrolls with the element.',
      keywords: ['background', 'scroll', 'attachment'],
    },
    {
      type: 'cc',
      name: 'bg-no-repeat',
      description: 'Sets background-repeat: no-repeat.',
      keywords: ['background', 'repeat', 'no-repeat', 'tile'],
    },
    {
      type: 'cc',
      name: 'bg-repeat',
      description: 'Sets background-repeat: repeat.',
      keywords: ['background', 'repeat', 'tile', 'pattern'],
    },
    {
      type: 'cc',
      name: 'bg-clip-text',
      description: 'Clips the background to the text shape. Use with bg to create gradient text.',
      keywords: ['background', 'clip', 'text', 'gradient', 'effect'],
    },
    {
      type: 'cc',
      name: 'bg-clip-border',
      description: 'Sets background-clip: border-box. Background extends under the border.',
      keywords: ['background', 'clip', 'border-box'],
    },
    {
      type: 'cc',
      name: 'bg-clip-padding',
      description: 'Sets background-clip: padding-box. Background is clipped to the padding edge.',
      keywords: ['background', 'clip', 'padding-box'],
    },
    {
      type: 'co',
      name: 'linear-to-r',
      description: 'Sets gradient direction to the right. Combine with from, via, and to.',
      keywords: ['gradient', 'linear', 'direction', 'right', 'background'],
    },
    {
      type: 'co',
      name: 'linear-to-br',
      description: 'Sets gradient direction to bottom-right. Combine with from, via, and to.',
      keywords: ['gradient', 'linear', 'direction', 'diagonal', 'background'],
    },
    {
      type: 'co',
      name: 'linear-to-b',
      description: 'Sets gradient direction to the bottom. Combine with from, via, and to.',
      keywords: ['gradient', 'linear', 'direction', 'vertical', 'background'],
    },
    {
      type: 'vd',
      name: 'from',
      accepts: 'color-mix',
      description: 'Sets the gradient start color via --from.',
      keywords: ['gradient', 'from', 'start', 'color', 'stop'],
    },
    {
      type: 'vd',
      name: 'from/o',
      accepts: 'numeric',
      unit: '%',
      min: 0,
      max: 100,
      step: 1,
      description: 'Sets gradient start color + opacity via --from and --from-o.',
      keywords: ['gradient', 'from', 'start', 'color', 'opacity', 'alpha'],
    },
    {
      type: 'vd',
      name: 'via',
      accepts: 'color-mix',
      description: 'Sets the gradient midpoint color via --via.',
      keywords: ['gradient', 'via', 'middle', 'midpoint', 'color', 'stop'],
    },
    {
      type: 'vd',
      name: 'to',
      accepts: 'color-mix',
      description: 'Sets the gradient end color via --to.',
      keywords: ['gradient', 'to', 'end', 'color', 'stop'],
    },
    {
      type: 'vd',
      name: 'from-position',
      accepts: 'raw',
      description: 'Sets the gradient from-stop position via --from-position. E.g. 10%.',
      keywords: ['gradient', 'from', 'stop', 'position', 'percent'],
    },
    {
      type: 'vd',
      name: 'via-position',
      accepts: 'raw',
      description: 'Sets the gradient via-stop position via --via-position. E.g. 50%.',
      keywords: ['gradient', 'via', 'stop', 'position', 'percent'],
    },
    {
      type: 'vd',
      name: 'to-position',
      accepts: 'raw',
      description: 'Sets the gradient to-stop position via --to-position. E.g. 90%.',
      keywords: ['gradient', 'to', 'stop', 'position', 'percent'],
    },

    {
      type: 'cc',
      name: 'bg-blend-saturation',
      description:
        "Blends the background image/color with the element's backdrop using the saturation blend mode.",
      keywords: ['background', 'blend', 'mode', 'saturation'],
    },
    {
      type: 'cc',
      name: 'bg-blend-color',
      description:
        "Blends the background image/color with the element's backdrop using the color blend mode.",
      keywords: ['background', 'blend', 'mode', 'color'],
    },
    {
      type: 'cc',
      name: 'bg-blend-luminosity',
      description:
        "Blends the background image/color with the element's backdrop using the luminosity blend mode.",
      keywords: ['background', 'blend', 'mode', 'luminosity'],
    },

    {
      type: 'cc',
      name: 'bg-gradient-to-t',
      description: 'Sets a linear gradient background direction towards the top.',
      keywords: ['background', 'gradient', 'linear', 'top'],
    },
    {
      type: 'cc',
      name: 'bg-gradient-to-tr',
      description: 'Sets a linear gradient background direction towards the top right.',
      keywords: ['background', 'gradient', 'linear', 'top', 'right'],
    },
    {
      type: 'cc',
      name: 'bg-gradient-to-r',
      description: 'Sets a linear gradient background direction towards the right.',
      keywords: ['background', 'gradient', 'linear', 'right'],
    },
    {
      type: 'cc',
      name: 'bg-gradient-to-br',
      description: 'Sets a linear gradient background direction towards the bottom right.',
      keywords: ['background', 'gradient', 'linear', 'bottom', 'right'],
    },
    {
      type: 'cc',
      name: 'bg-gradient-to-b',
      description: 'Sets a linear gradient background direction towards the bottom.',
      keywords: ['background', 'gradient', 'linear', 'bottom'],
    },
    {
      type: 'cc',
      name: 'bg-gradient-to-bl',
      description: 'Sets a linear gradient background direction towards the bottom left.',
      keywords: ['background', 'gradient', 'linear', 'bottom', 'left'],
    },
    {
      type: 'cc',
      name: 'bg-gradient-to-l',
      description: 'Sets a linear gradient background direction towards the left.',
      keywords: ['background', 'gradient', 'linear', 'left'],
    },
    {
      type: 'cc',
      name: 'bg-gradient-to-tl',
      description: 'Sets a linear gradient background direction towards the top left.',
      keywords: ['background', 'gradient', 'linear', 'top', 'left'],
    },

    {
      type: 'cc',
      name: 'bg-local',
      description: "Scrolls the background image with the element's contents.",
      keywords: ['background', 'attachment', 'local', 'scroll'],
    },
    {
      type: 'cc',
      name: 'bg-clip-content',
      description: 'Clips the background to the content box.',
      keywords: ['background', 'clip', 'content', 'box'],
    },
    {
      type: 'cc',
      name: 'bg-origin-border',
      description: 'Positions the background relative to the border box.',
      keywords: ['background', 'origin', 'border', 'box'],
    },
    {
      type: 'cc',
      name: 'bg-origin-padding',
      description: 'Positions the background relative to the padding box.',
      keywords: ['background', 'origin', 'padding', 'box'],
    },
    {
      type: 'cc',
      name: 'bg-origin-content',
      description: 'Positions the background relative to the content box.',
      keywords: ['background', 'origin', 'content', 'box'],
    },
    {
      type: 'cc',
      name: 'bg-top-left',
      description: 'Positions the background image at the top left.',
      keywords: ['background', 'position', 'top', 'left'],
    },
    {
      type: 'cc',
      name: 'bg-top-right',
      description: 'Positions the background image at the top right.',
      keywords: ['background', 'position', 'top', 'right'],
    },
    {
      type: 'cc',
      name: 'bg-left',
      description: 'Positions the background image on the left.',
      keywords: ['background', 'position', 'left', 'center'],
    },
    {
      type: 'cc',
      name: 'bg-right',
      description: 'Positions the background image on the right.',
      keywords: ['background', 'position', 'right', 'center'],
    },
    {
      type: 'cc',
      name: 'bg-bottom-left',
      description: 'Positions the background image at the bottom left.',
      keywords: ['background', 'position', 'bottom', 'left'],
    },
    {
      type: 'cc',
      name: 'bg-bottom-right',
      description: 'Positions the background image at the bottom right.',
      keywords: ['background', 'position', 'bottom', 'right'],
    },
    {
      type: 'cc',
      name: 'bg-repeat-x',
      description: 'Repeats the background image only horizontally.',
      keywords: ['background', 'repeat', 'horizontal', 'x'],
    },
    {
      type: 'cc',
      name: 'bg-repeat-y',
      description: 'Repeats the background image only vertically.',
      keywords: ['background', 'repeat', 'vertical', 'y'],
    },
    {
      type: 'cc',
      name: 'bg-repeat-space',
      description: 'Spaces the background image evenly without clipping.',
      keywords: ['background', 'repeat', 'space'],
    },
    {
      type: 'cc',
      name: 'bg-repeat-round',
      description:
        'Scales the background image to fit exactly an integer number of times without clipping.',
      keywords: ['background', 'repeat', 'round', 'scale'],
    },
    {
      type: 'cc',
      name: 'bg-auto',
      description: 'Displays the background image at its original size.',
      keywords: ['background', 'size', 'auto'],
    },
    {
      type: 'cc',
      name: 'bg-blend-normal',
      description: 'Sets the background blend mode to normal.',
      keywords: ['background', 'blend', 'mode', 'normal'],
    },
    {
      type: 'cc',
      name: 'bg-blend-screen',
      description: 'Sets the background blend mode to screen.',
      keywords: ['background', 'blend', 'mode', 'screen'],
    },
    {
      type: 'cc',
      name: 'bg-blend-darken',
      description: 'Sets the background blend mode to darken.',
      keywords: ['background', 'blend', 'mode', 'darken'],
    },
    {
      type: 'cc',
      name: 'bg-blend-lighten',
      description: 'Sets the background blend mode to lighten.',
      keywords: ['background', 'blend', 'mode', 'lighten'],
    },
    {
      type: 'cc',
      name: 'bg-blend-color-dodge',
      description: 'Sets the background blend mode to color-dodge.',
      keywords: ['background', 'blend', 'mode', 'color', 'dodge'],
    },
    {
      type: 'cc',
      name: 'bg-blend-color-burn',
      description: 'Sets the background blend mode to color-burn.',
      keywords: ['background', 'blend', 'mode', 'color', 'burn'],
    },
    {
      type: 'cc',
      name: 'bg-blend-hard-light',
      description: 'Sets the background blend mode to hard-light.',
      keywords: ['background', 'blend', 'mode', 'hard', 'light'],
    },
    {
      type: 'cc',
      name: 'bg-blend-soft-light',
      description: 'Sets the background blend mode to soft-light.',
      keywords: ['background', 'blend', 'mode', 'soft', 'light'],
    },
    {
      type: 'cc',
      name: 'bg-blend-difference',
      description: 'Sets the background blend mode to difference.',
      keywords: ['background', 'blend', 'mode', 'difference'],
    },
    {
      type: 'cc',
      name: 'bg-blend-exclusion',
      description: 'Sets the background blend mode to exclusion.',
      keywords: ['background', 'blend', 'mode', 'exclusion'],
    },
    {
      type: 'cc',
      name: 'bg-blend-hue',
      description: 'Sets the background blend mode to hue.',
      keywords: ['background', 'blend', 'mode', 'hue'],
    },

    {
      type: 'vd',
      name: 'via/o',
      accepts: 'numeric',
      unit: '%',
      min: 0,
      max: 100,
      step: 1,
      description: 'Sets gradient via color + opacity independently via --via and --via-o.',
      keywords: ['gradient', 'via', 'color-stop', 'opacity', 'background'],
    },
    {
      type: 'vd',
      name: 'to/o',
      accepts: 'numeric',
      unit: '%',
      min: 0,
      max: 100,
      step: 1,
      description: 'Sets gradient end color + opacity independently via --to and --to-o.',
      keywords: ['gradient', 'to', 'color-stop', 'opacity', 'background'],
    },
    {
      type: 'vd',
      name: 'gradient-position',
      description:
        'Sets gradient position/interpolation via --gradient-position, falling back to oklab.',
      keywords: ['gradient', 'position', 'background', 'oklab', 'interpolation'],
    },

    {
      type: 'co',
      name: 'linear',
      description: 'Creates a linear gradient background using configured gradient stops.',
      keywords: ['gradient', 'linear', 'background', 'gradient-stops'],
    },
    {
      type: 'co',
      name: 'radial',
      description: 'Creates a radial gradient background using configured gradient stops.',
      keywords: ['gradient', 'radial', 'background', 'gradient-stops'],
    },
    {
      type: 'co',
      name: 'conic',
      description: 'Creates a conic gradient background using configured gradient stops.',
      keywords: ['gradient', 'conic', 'background', 'gradient-stops'],
    },
    {
      type: 'co',
      name: 'linear-to-t',
      description: 'Points a linear gradient toward the top and uses oklab interpolation.',
      keywords: ['gradient', 'linear', 'to-top', 'background'],
    },
    {
      type: 'co',
      name: 'linear-to-tr',
      description: 'Points a linear gradient toward the top right and uses oklab interpolation.',
      keywords: ['gradient', 'linear', 'to-top-right', 'background'],
    },
    {
      type: 'co',
      name: 'linear-to-bl',
      description: 'Points a linear gradient toward the bottom left and uses oklab interpolation.',
      keywords: ['gradient', 'linear', 'to-bottom-left', 'background'],
    },
    {
      type: 'co',
      name: 'linear-to-l',
      description: 'Points a linear gradient toward the left and uses oklab interpolation.',
      keywords: ['gradient', 'linear', 'to-left', 'background'],
    },
    {
      type: 'co',
      name: 'linear-to-tl',
      description: 'Points a linear gradient toward the top left and uses oklab interpolation.',
      keywords: ['gradient', 'linear', 'to-top-left', 'background'],
    },
  ],
};
