export default {
  text: 'Borders',
  items: [
    {
      type: 'vd',
      name: 'border',
      accepts: 'color-mix',
      description: 'Sets border-color on all sides via --border.',
      keywords: ['border', 'color', 'stroke', 'outline'],
    },
    {
      type: 'vd',
      name: 'border/o',
      accepts: 'numeric',
      unit: '%',
      min: 0,
      max: 100,
      step: 1,
      description: 'Sets border-color + opacity via --border and --border-o.',
      keywords: ['border', 'color', 'opacity', 'alpha', 'transparent'],
    },
    {
      type: 'vd',
      name: 'border-t',
      accepts: 'color-mix',
      description: 'Sets border-top-color via --border-t.',
      keywords: ['border', 'top', 'color'],
    },
    {
      type: 'vd',
      name: 'border-b',
      accepts: 'color-mix',
      description: 'Sets border-bottom-color via --border-b.',
      keywords: ['border', 'bottom', 'color'],
    },
    {
      type: 'vd',
      name: 'border-l',
      accepts: 'color-mix',
      description: 'Sets border-left-color via --border-l.',
      keywords: ['border', 'left', 'color'],
    },
    {
      type: 'vd',
      name: 'border-r',
      accepts: 'color-mix',
      description: 'Sets border-right-color via --border-r.',
      keywords: ['border', 'right', 'color'],
    },
    {
      type: 'vd',
      name: 'border-x',
      accepts: 'color-mix',
      description: 'Sets border-left-color and border-right-color via --border-x.',
      keywords: ['border', 'horizontal', 'left', 'right', 'color'],
    },
    {
      type: 'vd',
      name: 'border-y',
      accepts: 'color-mix',
      description: 'Sets border-top-color and border-bottom-color via --border-y.',
      keywords: ['border', 'vertical', 'top', 'bottom', 'color'],
    },
    {
      type: 'vd',
      name: 'border-w',
      accepts: 'raw',
      description:
        'Sets border-width on all sides via --border-w. Raw value, include unit (e.g. 2px).',
      keywords: ['border', 'width', 'thickness', 'size'],
    },
    {
      type: 'vd',
      name: 'border-t-w',
      accepts: 'raw',
      description: 'Sets border-top-width via --border-t-w. Raw value.',
      keywords: ['border', 'top', 'width', 'thickness'],
    },
    {
      type: 'vd',
      name: 'border-b-w',
      accepts: 'raw',
      description: 'Sets border-bottom-width via --border-b-w. Raw value.',
      keywords: ['border', 'bottom', 'width', 'thickness'],
    },
    {
      type: 'vd',
      name: 'border-x-w',
      accepts: 'raw',
      description: 'Sets border-left-width and border-right-width via --border-x-w. Raw value.',
      keywords: ['border', 'horizontal', 'width', 'thickness'],
    },
    {
      type: 'vd',
      name: 'border-y-w',
      accepts: 'raw',
      description: 'Sets border-top-width and border-bottom-width via --border-y-w. Raw value.',
      keywords: ['border', 'vertical', 'width', 'thickness'],
    },
    {
      type: 'cc',
      name: 'border-solid',
      description: 'Sets border-style: solid.',
      keywords: ['border', 'style', 'solid'],
    },
    {
      type: 'cc',
      name: 'border-dashed',
      description: 'Sets border-style: dashed.',
      keywords: ['border', 'style', 'dashed'],
    },
    {
      type: 'cc',
      name: 'border-dotted',
      description: 'Sets border-style: dotted.',
      keywords: ['border', 'style', 'dotted'],
    },
    {
      type: 'cc',
      name: 'border-double',
      description: 'Sets border-style: double.',
      keywords: ['border', 'style', 'double'],
    },
    {
      type: 'cc',
      name: 'border-none',
      description: 'Sets border-style: none. Removes the border.',
      keywords: ['border', 'none', 'remove', 'reset'],
    },
    {
      type: 'vd',
      name: 'rounded',
      accepts: 'raw',
      description: 'Sets border-radius on all corners via --rounded. E.g. 8px, 50%.',
      keywords: ['border-radius', 'rounded', 'corners', 'radius'],
    },
    {
      type: 'co',
      name: 'rounded-sm',
      description: 'Sets border-radius to sm preset.',
      keywords: ['border-radius', 'rounded', 'small'],
    },
    {
      type: 'co',
      name: 'rounded-md',
      description: 'Sets border-radius to md preset.',
      keywords: ['border-radius', 'rounded', 'medium'],
    },
    {
      type: 'co',
      name: 'rounded-lg',
      description: 'Sets border-radius to lg preset.',
      keywords: ['border-radius', 'rounded', 'large'],
    },
    {
      type: 'co',
      name: 'rounded-xl',
      description: 'Sets border-radius to xl preset.',
      keywords: ['border-radius', 'rounded', 'extra-large'],
    },
    {
      type: 'co',
      name: 'rounded-full',
      description: 'Sets border-radius: 9999px. Creates circles or pill shapes.',
      keywords: ['border-radius', 'rounded', 'full', 'circle', 'pill'],
    },
    {
      type: 'co',
      name: 'rounded-none',
      description: 'Removes border-radius.',
      keywords: ['border-radius', 'none', 'sharp', 'square'],
    },
    {
      type: 'vo',
      name: 'rounded-t',
      accepts: 'raw',
      description: 'Sets border-radius on top corners via --rounded-t.',
      keywords: ['border-radius', 'rounded', 'top', 'corners'],
    },
    {
      type: 'vo',
      name: 'rounded-b',
      accepts: 'raw',
      description: 'Sets border-radius on bottom corners via --rounded-b.',
      keywords: ['border-radius', 'rounded', 'bottom', 'corners'],
    },
    {
      type: 'vd',
      name: 'outline',
      accepts: 'color-mix',
      description: 'Sets outline-color via --outline.',
      keywords: ['outline', 'focus', 'color', 'accessibility'],
    },
    {
      type: 'vd',
      name: 'outline/o',
      accepts: 'numeric',
      unit: '%',
      min: 0,
      max: 100,
      step: 1,
      description: 'Sets outline-color + opacity via --outline and --outline-o.',
      keywords: ['outline', 'color', 'opacity', 'alpha', 'focus'],
    },
    {
      type: 'vd',
      name: 'outline-w',
      accepts: 'raw',
      description: 'Sets outline-width via --outline-w. Raw value.',
      keywords: ['outline', 'width', 'thickness', 'focus'],
    },
    {
      type: 'vd',
      name: 'outline-offset',
      accepts: 'raw',
      description: 'Sets outline-offset via --outline-offset. Raw value.',
      keywords: ['outline', 'offset', 'gap', 'focus'],
    },
    {
      type: 'cc',
      name: 'outline-none',
      description: 'Sets outline: none. Removes the outline.',
      keywords: ['outline', 'none', 'remove', 'focus'],
    },
    {
      type: 'cc',
      name: 'outline-dashed',
      description: 'Sets outline-style: dashed.',
      keywords: ['outline', 'style', 'dashed'],
    },
    {
      type: 'vd',
      name: 'divide-x',
      accepts: 'scaled',
      description:
        'Adds vertical divider borders between horizontal children via --divide-x. Scaled.',
      keywords: ['divide', 'border', 'separator', 'children', 'horizontal'],
    },
    {
      type: 'vd',
      name: 'divide-y',
      accepts: 'scaled',
      description:
        'Adds horizontal divider borders between vertical children via --divide-y. Scaled.',
      keywords: ['divide', 'border', 'separator', 'children', 'vertical'],
    },

    {
      type: 'co',
      name: 'rounded-bl-xl',
      description: 'Sets the bottom-left border radius to extra large.',
      keywords: ['border', 'radius', 'bottom', 'left', 'rounded', 'bl'],
    },
    {
      type: 'co',
      name: 'rounded-bl-2xl',
      description: 'Sets the bottom-left border radius to 2xl.',
      keywords: ['border', 'radius', 'bottom', 'left', 'rounded', 'bl'],
    },
    {
      type: 'co',
      name: 'rounded-bl-3xl',
      description: 'Sets the bottom-left border radius to 3xl.',
      keywords: ['border', 'radius', 'bottom', 'left', 'rounded', 'bl'],
    },
    {
      type: 'co',
      name: 'rounded-bl-4xl',
      description: 'Sets the bottom-left border radius to 4xl.',
      keywords: ['border', 'radius', 'bottom', 'left', 'rounded', 'bl'],
    },
    {
      type: 'co',
      name: 'rounded-bl-none',
      description: 'Removes the bottom-left border radius.',
      keywords: ['border', 'radius', 'bottom', 'left', 'none', 'bl'],
    },
    {
      type: 'co',
      name: 'rounded-bl-full',
      description: 'Sets the bottom-left border radius to fully rounded (pill/circle).',
      keywords: ['border', 'radius', 'bottom', 'left', 'full', 'bl'],
    },
    {
      type: 'cc',
      name: 'border-hidden',
      description: 'Sets the border style to hidden.',
      keywords: ['border', 'style', 'hidden'],
    },

    {
      type: 'cc',
      name: 'outline-hidden',
      description:
        'Hides the outline and replaces it with a transparent 2px solid border, useful for accessibility focus rings.',
      keywords: ['outline', 'hidden', 'accessibility', 'focus', 'ring'],
    },
    {
      type: 'cc',
      name: 'outline-dotted',
      description: 'Sets the outline style to dotted.',
      keywords: ['outline', 'style', 'dotted', 'border'],
    },
    {
      type: 'cc',
      name: 'outline-double',
      description: 'Sets the outline style to double.',
      keywords: ['outline', 'style', 'double', 'border'],
    },

    {
      type: 'vo',
      name: 'rounded-s',
      description:
        'Rounds the inline-start side corners via --rounded-s. Logical for RTL/LTR-aware layouts.',
      keywords: ['radius', 'rounded', 'logical', 'start', 'border'],
    },
    {
      type: 'vo',
      name: 'rounded-e',
      description:
        'Rounds the inline-end side corners via --rounded-e. Logical for RTL/LTR-aware layouts.',
      keywords: ['radius', 'rounded', 'logical', 'end', 'border'],
    },
    {
      type: 'vo',
      name: 'rounded-r',
      description:
        'Rounds both right-side corners via --rounded-r. Physical direction, not logical.',
      keywords: ['radius', 'rounded', 'right', 'border'],
    },
    {
      type: 'vo',
      name: 'rounded-l',
      description:
        'Rounds both left-side corners via --rounded-l. Physical direction, not logical.',
      keywords: ['radius', 'rounded', 'left', 'border'],
    },
    {
      type: 'vo',
      name: 'rounded-ss',
      description: 'Rounds only the start-start corner. Accepts a custom radius value.',
      keywords: ['radius', 'rounded', 'corner', 'start-start', 'logical'],
    },
    {
      type: 'vo',
      name: 'rounded-se',
      description: 'Rounds only the start-end corner. Accepts a custom radius value.',
      keywords: ['radius', 'rounded', 'corner', 'start-end', 'logical'],
    },
    {
      type: 'vo',
      name: 'rounded-ee',
      description: 'Rounds only the end-end corner. Accepts a custom radius value.',
      keywords: ['radius', 'rounded', 'corner', 'end-end', 'logical'],
    },
    {
      type: 'vo',
      name: 'rounded-es',
      description: 'Rounds only the end-start corner. Accepts a custom radius value.',
      keywords: ['radius', 'rounded', 'corner', 'end-start', 'logical'],
    },
    {
      type: 'vo',
      name: 'rounded-tl',
      description: 'Rounds only the top-left corner. Accepts a custom radius value.',
      keywords: ['radius', 'rounded', 'corner', 'top-left'],
    },
    {
      type: 'vo',
      name: 'rounded-tr',
      description: 'Rounds only the top-right corner. Accepts a custom radius value.',
      keywords: ['radius', 'rounded', 'corner', 'top-right'],
    },
    {
      type: 'vo',
      name: 'rounded-br',
      description: 'Rounds only the bottom-right corner. Accepts a custom radius value.',
      keywords: ['radius', 'rounded', 'corner', 'bottom-right'],
    },
    {
      type: 'vo',
      name: 'rounded-bl',
      description: 'Rounds only the bottom-left corner. Accepts a custom radius value.',
      keywords: ['radius', 'rounded', 'corner', 'bottom-left'],
    },

    {
      type: 'vd',
      name: 'border-r-w',
      description: 'Sets the right border thickness. Accepts a custom width value.',
      keywords: ['border', 'width', 'right', 'thickness'],
    },
    {
      type: 'vd',
      name: 'border-l-w',
      description: 'Sets the left border thickness. Accepts a custom width value.',
      keywords: ['border', 'width', 'left', 'thickness'],
    },
    {
      type: 'vd',
      name: 'border-s-w',
      description: 'Sets the inline-start border thickness. Logical width for start-edge borders.',
      keywords: ['border', 'width', 'start', 'logical', 'thickness'],
    },
    {
      type: 'vd',
      name: 'border-e-w',
      description: 'Sets the inline-end border thickness. Logical width for end-edge borders.',
      keywords: ['border', 'width', 'end', 'logical', 'thickness'],
    },
    {
      type: 'vd',
      name: 'border-s',
      description:
        'Colors the inline-start border. Accepts an arbitrary color and supports dark mode.',
      keywords: ['border', 'color', 'start', 'logical', 'dark'],
    },
    {
      type: 'vd',
      name: 'border-e',
      description:
        'Colors the inline-end border. Accepts an arbitrary color and supports dark mode.',
      keywords: ['border', 'color', 'end', 'logical', 'dark'],
    },
    {
      type: 'vd',
      name: 'border-t/o',
      accepts: 'numeric',
      unit: '%',
      min: 0,
      max: 100,
      step: 1,
      description: 'Sets border-top color + opacity independently via --border-t and --border-t-o.',
      keywords: ['border', 'top', 'color', 'opacity', 'alpha'],
    },
    {
      type: 'vd',
      name: 'border-r/o',
      accepts: 'numeric',
      unit: '%',
      min: 0,
      max: 100,
      step: 1,
      description:
        'Sets border-right color + opacity independently via --border-r and --border-r-o.',
      keywords: ['border', 'right', 'color', 'opacity', 'alpha'],
    },
    {
      type: 'vd',
      name: 'border-b/o',
      accepts: 'numeric',
      unit: '%',
      min: 0,
      max: 100,
      step: 1,
      description:
        'Sets border-bottom color + opacity independently via --border-b and --border-b-o.',
      keywords: ['border', 'bottom', 'color', 'opacity', 'alpha'],
    },
    {
      type: 'vd',
      name: 'border-l/o',
      accepts: 'numeric',
      unit: '%',
      min: 0,
      max: 100,
      step: 1,
      description:
        'Sets border-left color + opacity independently via --border-l and --border-l-o.',
      keywords: ['border', 'left', 'color', 'opacity', 'alpha'],
    },
    {
      type: 'vd',
      name: 'border-s/o',
      accepts: 'numeric',
      unit: '%',
      min: 0,
      max: 100,
      step: 1,
      description:
        'Sets border-inline-start color + opacity independently via --border-s and --border-s-o.',
      keywords: ['border', 'start', 'logical', 'color', 'opacity'],
    },
    {
      type: 'vd',
      name: 'border-e/o',
      accepts: 'numeric',
      unit: '%',
      min: 0,
      max: 100,
      step: 1,
      description:
        'Sets border-inline-end color + opacity independently via --border-e and --border-e-o.',
      keywords: ['border', 'end', 'logical', 'color', 'opacity'],
    },
    {
      type: 'vd',
      name: 'border-x/o',
      accepts: 'numeric',
      unit: '%',
      min: 0,
      max: 100,
      step: 1,
      description:
        'Sets border-inline color + opacity independently via --border-x and --border-x-o.',
      keywords: ['border', 'inline', 'x', 'color', 'opacity'],
    },
    {
      type: 'vd',
      name: 'border-y/o',
      accepts: 'numeric',
      unit: '%',
      min: 0,
      max: 100,
      step: 1,
      description:
        'Sets border-block color + opacity independently via --border-y and --border-y-o.',
      keywords: ['border', 'block', 'y', 'color', 'opacity'],
    },

    {
      type: 'co',
      name: 'rounded-xs',
      description: 'Applies extra-small radius via --radius-xs to all corners.',
      keywords: ['radius', 'rounded', 'xs', 'subtle', 'border'],
    },
    {
      type: 'co',
      name: 'rounded-2xl',
      description: 'Applies very large radius via --radius-2xl to all corners.',
      keywords: ['radius', 'rounded', '2xl', 'large', 'border'],
    },
    {
      type: 'co',
      name: 'rounded-3xl',
      description: 'Applies larger radius via --radius-3xl to all corners.',
      keywords: ['radius', 'rounded', '3xl', 'larger', 'border'],
    },
    {
      type: 'co',
      name: 'rounded-4xl',
      description: 'Applies largest radius via --radius-4xl to all corners.',
      keywords: ['radius', 'rounded', '4xl', 'largest', 'border'],
    },
    {
      type: 'co',
      name: 'rounded-s-xs',
      description:
        'Applies extra-small radius to inline-start corners via --radius-xs. Logical start edge.',
      keywords: ['radius', 'rounded', 'start', 'logical', 'xs'],
    },
    {
      type: 'co',
      name: 'rounded-s-sm',
      description:
        'Applies small radius to inline-start corners via --radius-sm. Logical start edge.',
      keywords: ['radius', 'rounded', 'start', 'logical', 'sm'],
    },
    {
      type: 'co',
      name: 'rounded-s-md',
      description:
        'Applies medium radius to inline-start corners via --radius-md. Logical start edge.',
      keywords: ['radius', 'rounded', 'start', 'logical', 'md'],
    },
    {
      type: 'co',
      name: 'rounded-s-lg',
      description:
        'Applies large radius to inline-start corners via --radius-lg. Logical start edge.',
      keywords: ['radius', 'rounded', 'start', 'logical', 'lg'],
    },
    {
      type: 'co',
      name: 'rounded-s-xl',
      description:
        'Applies extra-large radius to inline-start corners via --radius-xl. Logical start edge.',
      keywords: ['radius', 'rounded', 'start', 'logical', 'xl'],
    },
    {
      type: 'co',
      name: 'rounded-s-2xl',
      description:
        'Applies very large radius to inline-start corners via --radius-2xl. Logical start edge.',
      keywords: ['radius', 'rounded', 'start', 'logical', '2xl'],
    },
    {
      type: 'co',
      name: 'rounded-s-3xl',
      description:
        'Applies larger radius to inline-start corners via --radius-3xl. Logical start edge.',
      keywords: ['radius', 'rounded', 'start', 'logical', '3xl'],
    },
    {
      type: 'co',
      name: 'rounded-s-4xl',
      description:
        'Applies largest radius to inline-start corners via --radius-4xl. Logical start edge.',
      keywords: ['radius', 'rounded', 'start', 'logical', '4xl'],
    },
    {
      type: 'co',
      name: 'rounded-s-none',
      description: 'Removes radius from inline-start corners.',
      keywords: ['radius', 'rounded', 'start', 'none', 'reset'],
    },
    {
      type: 'co',
      name: 'rounded-s-full',
      description: 'Makes inline-start corners fully rounded using an infinite radius.',
      keywords: ['radius', 'rounded', 'start', 'full', 'pill'],
    },
    {
      type: 'co',
      name: 'rounded-e-xs',
      description:
        'Applies extra-small radius to inline-end corners via --radius-xs. Logical end edge.',
      keywords: ['radius', 'rounded', 'end', 'logical', 'xs'],
    },
    {
      type: 'co',
      name: 'rounded-e-sm',
      description: 'Applies small radius to inline-end corners via --radius-sm. Logical end edge.',
      keywords: ['radius', 'rounded', 'end', 'logical', 'sm'],
    },
    {
      type: 'co',
      name: 'rounded-e-md',
      description: 'Applies medium radius to inline-end corners via --radius-md. Logical end edge.',
      keywords: ['radius', 'rounded', 'end', 'logical', 'md'],
    },
    {
      type: 'co',
      name: 'rounded-e-lg',
      description: 'Applies large radius to inline-end corners via --radius-lg. Logical end edge.',
      keywords: ['radius', 'rounded', 'end', 'logical', 'lg'],
    },
    {
      type: 'co',
      name: 'rounded-e-xl',
      description:
        'Applies extra-large radius to inline-end corners via --radius-xl. Logical end edge.',
      keywords: ['radius', 'rounded', 'end', 'logical', 'xl'],
    },
    {
      type: 'co',
      name: 'rounded-e-2xl',
      description:
        'Applies very large radius to inline-end corners via --radius-2xl. Logical end edge.',
      keywords: ['radius', 'rounded', 'end', 'logical', '2xl'],
    },
    {
      type: 'co',
      name: 'rounded-e-3xl',
      description:
        'Applies larger radius to inline-end corners via --radius-3xl. Logical end edge.',
      keywords: ['radius', 'rounded', 'end', 'logical', '3xl'],
    },
    {
      type: 'co',
      name: 'rounded-e-4xl',
      description:
        'Applies largest radius to inline-end corners via --radius-4xl. Logical end edge.',
      keywords: ['radius', 'rounded', 'end', 'logical', '4xl'],
    },
    {
      type: 'co',
      name: 'rounded-e-none',
      description: 'Removes radius from inline-end corners.',
      keywords: ['radius', 'rounded', 'end', 'none', 'reset'],
    },
    {
      type: 'co',
      name: 'rounded-e-full',
      description: 'Makes inline-end corners fully rounded using an infinite radius.',
      keywords: ['radius', 'rounded', 'end', 'full', 'pill'],
    },
    {
      type: 'co',
      name: 'rounded-t-xs',
      description: 'Applies extra-small radius to top-left and top-right corners via --radius-xs.',
      keywords: ['radius', 'rounded', 'top', 'xs', 'border'],
    },
    {
      type: 'co',
      name: 'rounded-t-sm',
      description: 'Applies small radius to top-left and top-right corners via --radius-sm.',
      keywords: ['radius', 'rounded', 'top', 'sm', 'border'],
    },
    {
      type: 'co',
      name: 'rounded-t-md',
      description: 'Applies medium radius to top-left and top-right corners via --radius-md.',
      keywords: ['radius', 'rounded', 'top', 'md', 'border'],
    },
    {
      type: 'co',
      name: 'rounded-t-lg',
      description: 'Applies large radius to top-left and top-right corners via --radius-lg.',
      keywords: ['radius', 'rounded', 'top', 'lg', 'border'],
    },
    {
      type: 'co',
      name: 'rounded-t-xl',
      description: 'Applies extra-large radius to top-left and top-right corners via --radius-xl.',
      keywords: ['radius', 'rounded', 'top', 'xl', 'border'],
    },
    {
      type: 'co',
      name: 'rounded-t-2xl',
      description: 'Applies very large radius to top-left and top-right corners via --radius-2xl.',
      keywords: ['radius', 'rounded', 'top', '2xl', 'border'],
    },
    {
      type: 'co',
      name: 'rounded-t-3xl',
      description: 'Applies larger radius to top-left and top-right corners via --radius-3xl.',
      keywords: ['radius', 'rounded', 'top', '3xl', 'border'],
    },
    {
      type: 'co',
      name: 'rounded-t-4xl',
      description: 'Applies largest radius to top-left and top-right corners via --radius-4xl.',
      keywords: ['radius', 'rounded', 'top', '4xl', 'border'],
    },
    {
      type: 'co',
      name: 'rounded-t-none',
      description: 'Removes radius from top-left and top-right corners.',
      keywords: ['radius', 'rounded', 'top', 'none', 'reset'],
    },
    {
      type: 'co',
      name: 'rounded-t-full',
      description: 'Makes top-left and top-right corners fully rounded using an infinite radius.',
      keywords: ['radius', 'rounded', 'top', 'full', 'pill'],
    },
    {
      type: 'co',
      name: 'rounded-r-xs',
      description:
        'Applies extra-small radius to top-right and bottom-right corners via --radius-xs.',
      keywords: ['radius', 'rounded', 'right', 'xs', 'border'],
    },
    {
      type: 'co',
      name: 'rounded-r-sm',
      description: 'Applies small radius to top-right and bottom-right corners via --radius-sm.',
      keywords: ['radius', 'rounded', 'right', 'sm', 'border'],
    },
    {
      type: 'co',
      name: 'rounded-r-md',
      description: 'Applies medium radius to top-right and bottom-right corners via --radius-md.',
      keywords: ['radius', 'rounded', 'right', 'md', 'border'],
    },
    {
      type: 'co',
      name: 'rounded-r-lg',
      description: 'Applies large radius to top-right and bottom-right corners via --radius-lg.',
      keywords: ['radius', 'rounded', 'right', 'lg', 'border'],
    },

    {
      type: 'co',
      name: 'rounded-r-xl',
      description:
        'Applies extra-large radius to top-right and bottom-right corners via --radius-xl.',
      keywords: ['radius', 'rounded', 'right', 'xl', 'border'],
    },
    {
      type: 'co',
      name: 'rounded-r-2xl',
      description:
        'Applies very large radius to top-right and bottom-right corners via --radius-2xl.',
      keywords: ['radius', 'rounded', 'right', '2xl', 'border'],
    },
    {
      type: 'co',
      name: 'rounded-r-3xl',
      description: 'Applies larger radius to top-right and bottom-right corners via --radius-3xl.',
      keywords: ['radius', 'rounded', 'right', '3xl', 'border'],
    },
    {
      type: 'co',
      name: 'rounded-r-4xl',
      description: 'Applies largest radius to top-right and bottom-right corners via --radius-4xl.',
      keywords: ['radius', 'rounded', 'right', '4xl', 'border'],
    },
    {
      type: 'co',
      name: 'rounded-r-none',
      description: 'Removes radius from top-right and bottom-right corners.',
      keywords: ['radius', 'rounded', 'right', 'none', 'reset'],
    },
    {
      type: 'co',
      name: 'rounded-r-full',
      description:
        'Makes top-right and bottom-right corners fully rounded using an infinite radius.',
      keywords: ['radius', 'rounded', 'right', 'full', 'pill'],
    },
    {
      type: 'co',
      name: 'rounded-b-xs',
      description:
        'Applies extra-small radius to bottom-left and bottom-right corners via --radius-xs.',
      keywords: ['radius', 'rounded', 'bottom', 'xs', 'border'],
    },
    {
      type: 'co',
      name: 'rounded-b-sm',
      description: 'Applies small radius to bottom-left and bottom-right corners via --radius-sm.',
      keywords: ['radius', 'rounded', 'bottom', 'sm', 'border'],
    },
    {
      type: 'co',
      name: 'rounded-b-md',
      description: 'Applies medium radius to bottom-left and bottom-right corners via --radius-md.',
      keywords: ['radius', 'rounded', 'bottom', 'md', 'border'],
    },
    {
      type: 'co',
      name: 'rounded-b-lg',
      description: 'Applies large radius to bottom-left and bottom-right corners via --radius-lg.',
      keywords: ['radius', 'rounded', 'bottom', 'lg', 'border'],
    },
    {
      type: 'co',
      name: 'rounded-b-xl',
      description:
        'Applies extra-large radius to bottom-left and bottom-right corners via --radius-xl.',
      keywords: ['radius', 'rounded', 'bottom', 'xl', 'border'],
    },
    {
      type: 'co',
      name: 'rounded-b-2xl',
      description:
        'Applies very large radius to bottom-left and bottom-right corners via --radius-2xl.',
      keywords: ['radius', 'rounded', 'bottom', '2xl', 'border'],
    },
    {
      type: 'co',
      name: 'rounded-b-3xl',
      description:
        'Applies larger radius to bottom-left and bottom-right corners via --radius-3xl.',
      keywords: ['radius', 'rounded', 'bottom', '3xl', 'border'],
    },
    {
      type: 'co',
      name: 'rounded-b-4xl',
      description:
        'Applies largest radius to bottom-left and bottom-right corners via --radius-4xl.',
      keywords: ['radius', 'rounded', 'bottom', '4xl', 'border'],
    },
    {
      type: 'co',
      name: 'rounded-b-none',
      description: 'Removes radius from bottom-left and bottom-right corners.',
      keywords: ['radius', 'rounded', 'bottom', 'none', 'reset'],
    },
    {
      type: 'co',
      name: 'rounded-b-full',
      description:
        'Makes bottom-left and bottom-right corners fully rounded using an infinite radius.',
      keywords: ['radius', 'rounded', 'bottom', 'full', 'pill'],
    },
    {
      type: 'co',
      name: 'rounded-l-xs',
      description:
        'Applies extra-small radius to top-left and bottom-left corners via --radius-xs.',
      keywords: ['radius', 'rounded', 'left', 'xs', 'border'],
    },
    {
      type: 'co',
      name: 'rounded-l-sm',
      description: 'Applies small radius to top-left and bottom-left corners via --radius-sm.',
      keywords: ['radius', 'rounded', 'left', 'sm', 'border'],
    },
    {
      type: 'co',
      name: 'rounded-l-md',
      description: 'Applies medium radius to top-left and bottom-left corners via --radius-md.',
      keywords: ['radius', 'rounded', 'left', 'md', 'border'],
    },
    {
      type: 'co',
      name: 'rounded-l-lg',
      description: 'Applies large radius to top-left and bottom-left corners via --radius-lg.',
      keywords: ['radius', 'rounded', 'left', 'lg', 'border'],
    },
    {
      type: 'co',
      name: 'rounded-l-xl',
      description:
        'Applies extra-large radius to top-left and bottom-left corners via --radius-xl.',
      keywords: ['radius', 'rounded', 'left', 'xl', 'border'],
    },
    {
      type: 'co',
      name: 'rounded-l-2xl',
      description:
        'Applies very large radius to top-left and bottom-left corners via --radius-2xl.',
      keywords: ['radius', 'rounded', 'left', '2xl', 'border'],
    },
    {
      type: 'co',
      name: 'rounded-l-3xl',
      description: 'Applies larger radius to top-left and bottom-left corners via --radius-3xl.',
      keywords: ['radius', 'rounded', 'left', '3xl', 'border'],
    },
    {
      type: 'co',
      name: 'rounded-l-4xl',
      description: 'Applies largest radius to top-left and bottom-left corners via --radius-4xl.',
      keywords: ['radius', 'rounded', 'left', '4xl', 'border'],
    },
    {
      type: 'co',
      name: 'rounded-l-none',
      description: 'Removes radius from top-left and bottom-left corners.',
      keywords: ['radius', 'rounded', 'left', 'none', 'reset'],
    },
    {
      type: 'co',
      name: 'rounded-l-full',
      description: 'Makes top-left and bottom-left corners fully rounded using an infinite radius.',
      keywords: ['radius', 'rounded', 'left', 'full', 'pill'],
    },
    {
      type: 'co',
      name: 'rounded-ss-xs',
      description: 'Applies extra-small radius to the start-start logical corner via --radius-xs.',
      keywords: ['radius', 'rounded', 'start-start', 'logical', 'xs'],
    },
    {
      type: 'co',
      name: 'rounded-ss-sm',
      description: 'Applies small radius to the start-start logical corner via --radius-sm.',
      keywords: ['radius', 'rounded', 'start-start', 'logical', 'sm'],
    },
    {
      type: 'co',
      name: 'rounded-ss-md',
      description: 'Applies medium radius to the start-start logical corner via --radius-md.',
      keywords: ['radius', 'rounded', 'start-start', 'logical', 'md'],
    },
    {
      type: 'co',
      name: 'rounded-ss-lg',
      description: 'Applies large radius to the start-start logical corner via --radius-lg.',
      keywords: ['radius', 'rounded', 'start-start', 'logical', 'lg'],
    },
    {
      type: 'co',
      name: 'rounded-ss-xl',
      description: 'Applies extra-large radius to the start-start logical corner via --radius-xl.',
      keywords: ['radius', 'rounded', 'start-start', 'logical', 'xl'],
    },
    {
      type: 'co',
      name: 'rounded-ss-2xl',
      description: 'Applies very large radius to the start-start logical corner via --radius-2xl.',
      keywords: ['radius', 'rounded', 'start-start', 'logical', '2xl'],
    },
    {
      type: 'co',
      name: 'rounded-ss-3xl',
      description: 'Applies larger radius to the start-start logical corner via --radius-3xl.',
      keywords: ['radius', 'rounded', 'start-start', 'logical', '3xl'],
    },
    {
      type: 'co',
      name: 'rounded-ss-4xl',
      description: 'Applies largest radius to the start-start logical corner via --radius-4xl.',
      keywords: ['radius', 'rounded', 'start-start', 'logical', '4xl'],
    },
    {
      type: 'co',
      name: 'rounded-ss-none',
      description: 'Removes radius from the start-start logical corner.',
      keywords: ['radius', 'rounded', 'start-start', 'none', 'reset'],
    },
    {
      type: 'co',
      name: 'rounded-ss-full',
      description: 'Makes the start-start logical corner fully rounded using an infinite radius.',
      keywords: ['radius', 'rounded', 'start-start', 'full', 'pill'],
    },
    {
      type: 'co',
      name: 'rounded-se-xs',
      description: 'Applies extra-small radius to the start-end logical corner via --radius-xs.',
      keywords: ['radius', 'rounded', 'start-end', 'logical', 'xs'],
    },
    {
      type: 'co',
      name: 'rounded-se-sm',
      description: 'Applies small radius to the start-end logical corner via --radius-sm.',
      keywords: ['radius', 'rounded', 'start-end', 'logical', 'sm'],
    },
    {
      type: 'co',
      name: 'rounded-se-md',
      description: 'Applies medium radius to the start-end logical corner via --radius-md.',
      keywords: ['radius', 'rounded', 'start-end', 'logical', 'md'],
    },
    {
      type: 'co',
      name: 'rounded-se-lg',
      description: 'Applies large radius to the start-end logical corner via --radius-lg.',
      keywords: ['radius', 'rounded', 'start-end', 'logical', 'lg'],
    },
    {
      type: 'co',
      name: 'rounded-se-xl',
      description: 'Applies extra-large radius to the start-end logical corner via --radius-xl.',
      keywords: ['radius', 'rounded', 'start-end', 'logical', 'xl'],
    },
    {
      type: 'co',
      name: 'rounded-se-2xl',
      description: 'Applies very large radius to the start-end logical corner via --radius-2xl.',
      keywords: ['radius', 'rounded', 'start-end', 'logical', '2xl'],
    },
    {
      type: 'co',
      name: 'rounded-se-3xl',
      description: 'Applies larger radius to the start-end logical corner via --radius-3xl.',
      keywords: ['radius', 'rounded', 'start-end', 'logical', '3xl'],
    },
    {
      type: 'co',
      name: 'rounded-se-4xl',
      description: 'Applies largest radius to the start-end logical corner via --radius-4xl.',
      keywords: ['radius', 'rounded', 'start-end', 'logical', '4xl'],
    },
    {
      type: 'co',
      name: 'rounded-se-none',
      description: 'Removes radius from the start-end logical corner.',
      keywords: ['radius', 'rounded', 'start-end', 'none', 'reset'],
    },
    {
      type: 'co',
      name: 'rounded-se-full',
      description: 'Makes the start-end logical corner fully rounded using an infinite radius.',
      keywords: ['radius', 'rounded', 'start-end', 'full', 'pill'],
    },
    {
      type: 'co',
      name: 'rounded-ee-xs',
      description: 'Applies extra-small radius to the end-end logical corner via --radius-xs.',
      keywords: ['radius', 'rounded', 'end-end', 'logical', 'xs'],
    },
    {
      type: 'co',
      name: 'rounded-ee-sm',
      description: 'Applies small radius to the end-end logical corner via --radius-sm.',
      keywords: ['radius', 'rounded', 'end-end', 'logical', 'sm'],
    },
    {
      type: 'co',
      name: 'rounded-ee-md',
      description: 'Applies medium radius to the end-end logical corner via --radius-md.',
      keywords: ['radius', 'rounded', 'end-end', 'logical', 'md'],
    },
    {
      type: 'co',
      name: 'rounded-ee-lg',
      description: 'Applies large radius to the end-end logical corner via --radius-lg.',
      keywords: ['radius', 'rounded', 'end-end', 'logical', 'lg'],
    },

    {
      type: 'co',
      name: 'rounded-ee-xl',
      description: 'Applies extra-large radius to the end-end logical corner via --radius-xl.',
      keywords: ['radius', 'rounded', 'end-end', 'logical', 'xl'],
    },
    {
      type: 'co',
      name: 'rounded-ee-2xl',
      description: 'Applies very large radius to the end-end logical corner via --radius-2xl.',
      keywords: ['radius', 'rounded', 'end-end', 'logical', '2xl'],
    },
    {
      type: 'co',
      name: 'rounded-ee-3xl',
      description: 'Applies larger radius to the end-end logical corner via --radius-3xl.',
      keywords: ['radius', 'rounded', 'end-end', 'logical', '3xl'],
    },
    {
      type: 'co',
      name: 'rounded-ee-4xl',
      description: 'Applies largest radius to the end-end logical corner via --radius-4xl.',
      keywords: ['radius', 'rounded', 'end-end', 'logical', '4xl'],
    },
    {
      type: 'co',
      name: 'rounded-ee-none',
      description: 'Removes radius from the end-end logical corner.',
      keywords: ['radius', 'rounded', 'end-end', 'none', 'reset'],
    },
    {
      type: 'co',
      name: 'rounded-ee-full',
      description: 'Makes the end-end logical corner fully rounded using an infinite radius.',
      keywords: ['radius', 'rounded', 'end-end', 'full', 'pill'],
    },
    {
      type: 'co',
      name: 'rounded-es-xs',
      description: 'Applies extra-small radius to the end-start logical corner via --radius-xs.',
      keywords: ['radius', 'rounded', 'end-start', 'logical', 'xs'],
    },
    {
      type: 'co',
      name: 'rounded-es-sm',
      description: 'Applies small radius to the end-start logical corner via --radius-sm.',
      keywords: ['radius', 'rounded', 'end-start', 'logical', 'sm'],
    },
    {
      type: 'co',
      name: 'rounded-es-md',
      description: 'Applies medium radius to the end-start logical corner via --radius-md.',
      keywords: ['radius', 'rounded', 'end-start', 'logical', 'md'],
    },
    {
      type: 'co',
      name: 'rounded-es-lg',
      description: 'Applies large radius to the end-start logical corner via --radius-lg.',
      keywords: ['radius', 'rounded', 'end-start', 'logical', 'lg'],
    },
    {
      type: 'co',
      name: 'rounded-es-xl',
      description: 'Applies extra-large radius to the end-start logical corner via --radius-xl.',
      keywords: ['radius', 'rounded', 'end-start', 'logical', 'xl'],
    },
    {
      type: 'co',
      name: 'rounded-es-2xl',
      description: 'Applies very large radius to the end-start logical corner via --radius-2xl.',
      keywords: ['radius', 'rounded', 'end-start', 'logical', '2xl'],
    },
    {
      type: 'co',
      name: 'rounded-es-3xl',
      description: 'Applies larger radius to the end-start logical corner via --radius-3xl.',
      keywords: ['radius', 'rounded', 'end-start', 'logical', '3xl'],
    },
    {
      type: 'co',
      name: 'rounded-es-4xl',
      description: 'Applies largest radius to the end-start logical corner via --radius-4xl.',
      keywords: ['radius', 'rounded', 'end-start', 'logical', '4xl'],
    },
    {
      type: 'co',
      name: 'rounded-es-none',
      description: 'Removes radius from the end-start logical corner.',
      keywords: ['radius', 'rounded', 'end-start', 'none', 'reset'],
    },
    {
      type: 'co',
      name: 'rounded-es-full',
      description: 'Makes the end-start logical corner fully rounded using an infinite radius.',
      keywords: ['radius', 'rounded', 'end-start', 'full', 'pill'],
    },
    {
      type: 'co',
      name: 'rounded-tl-xs',
      description: 'Applies extra-small radius to the top-left corner via --radius-xs.',
      keywords: ['radius', 'rounded', 'top-left', 'corner', 'xs'],
    },
    {
      type: 'co',
      name: 'rounded-tl-sm',
      description: 'Applies small radius to the top-left corner via --radius-sm.',
      keywords: ['radius', 'rounded', 'top-left', 'corner', 'sm'],
    },
    {
      type: 'co',
      name: 'rounded-tl-md',
      description: 'Applies medium radius to the top-left corner via --radius-md.',
      keywords: ['radius', 'rounded', 'top-left', 'corner', 'md'],
    },
    {
      type: 'co',
      name: 'rounded-tl-lg',
      description: 'Applies large radius to the top-left corner via --radius-lg.',
      keywords: ['radius', 'rounded', 'top-left', 'corner', 'lg'],
    },
    {
      type: 'co',
      name: 'rounded-tl-xl',
      description: 'Applies extra-large radius to the top-left corner via --radius-xl.',
      keywords: ['radius', 'rounded', 'top-left', 'corner', 'xl'],
    },
    {
      type: 'co',
      name: 'rounded-tl-2xl',
      description: 'Applies very large radius to the top-left corner via --radius-2xl.',
      keywords: ['radius', 'rounded', 'top-left', 'corner', '2xl'],
    },
    {
      type: 'co',
      name: 'rounded-tl-3xl',
      description: 'Applies larger radius to the top-left corner via --radius-3xl.',
      keywords: ['radius', 'rounded', 'top-left', 'corner', '3xl'],
    },
    {
      type: 'co',
      name: 'rounded-tl-4xl',
      description: 'Applies largest radius to the top-left corner via --radius-4xl.',
      keywords: ['radius', 'rounded', 'top-left', 'corner', '4xl'],
    },
    {
      type: 'co',
      name: 'rounded-tl-none',
      description: 'Removes radius from the top-left corner.',
      keywords: ['radius', 'rounded', 'top-left', 'none', 'reset'],
    },
    {
      type: 'co',
      name: 'rounded-tl-full',
      description: 'Makes the top-left corner fully rounded using an infinite radius.',
      keywords: ['radius', 'rounded', 'top-left', 'full', 'pill'],
    },
    {
      type: 'co',
      name: 'rounded-tr-xs',
      description: 'Applies extra-small radius to the top-right corner via --radius-xs.',
      keywords: ['radius', 'rounded', 'top-right', 'corner', 'xs'],
    },
    {
      type: 'co',
      name: 'rounded-tr-sm',
      description: 'Applies small radius to the top-right corner via --radius-sm.',
      keywords: ['radius', 'rounded', 'top-right', 'corner', 'sm'],
    },
    {
      type: 'co',
      name: 'rounded-tr-md',
      description: 'Applies medium radius to the top-right corner via --radius-md.',
      keywords: ['radius', 'rounded', 'top-right', 'corner', 'md'],
    },
    {
      type: 'co',
      name: 'rounded-tr-lg',
      description: 'Applies large radius to the top-right corner via --radius-lg.',
      keywords: ['radius', 'rounded', 'top-right', 'corner', 'lg'],
    },
    {
      type: 'co',
      name: 'rounded-tr-xl',
      description: 'Applies extra-large radius to the top-right corner via --radius-xl.',
      keywords: ['radius', 'rounded', 'top-right', 'corner', 'xl'],
    },
    {
      type: 'co',
      name: 'rounded-tr-2xl',
      description: 'Applies very large radius to the top-right corner via --radius-2xl.',
      keywords: ['radius', 'rounded', 'top-right', 'corner', '2xl'],
    },
    {
      type: 'co',
      name: 'rounded-tr-3xl',
      description: 'Applies larger radius to the top-right corner via --radius-3xl.',
      keywords: ['radius', 'rounded', 'top-right', 'corner', '3xl'],
    },
    {
      type: 'co',
      name: 'rounded-tr-4xl',
      description: 'Applies largest radius to the top-right corner via --radius-4xl.',
      keywords: ['radius', 'rounded', 'top-right', 'corner', '4xl'],
    },
    {
      type: 'co',
      name: 'rounded-tr-none',
      description: 'Removes radius from the top-right corner.',
      keywords: ['radius', 'rounded', 'top-right', 'none', 'reset'],
    },
    {
      type: 'co',
      name: 'rounded-tr-full',
      description: 'Makes the top-right corner fully rounded using an infinite radius.',
      keywords: ['radius', 'rounded', 'top-right', 'full', 'pill'],
    },
    {
      type: 'co',
      name: 'rounded-br-xs',
      description: 'Applies extra-small radius to the bottom-right corner via --radius-xs.',
      keywords: ['radius', 'rounded', 'bottom-right', 'corner', 'xs'],
    },
    {
      type: 'co',
      name: 'rounded-br-sm',
      description: 'Applies small radius to the bottom-right corner via --radius-sm.',
      keywords: ['radius', 'rounded', 'bottom-right', 'corner', 'sm'],
    },
    {
      type: 'co',
      name: 'rounded-br-md',
      description: 'Applies medium radius to the bottom-right corner via --radius-md.',
      keywords: ['radius', 'rounded', 'bottom-right', 'corner', 'md'],
    },
    {
      type: 'co',
      name: 'rounded-br-lg',
      description: 'Applies large radius to the bottom-right corner via --radius-lg.',
      keywords: ['radius', 'rounded', 'bottom-right', 'corner', 'lg'],
    },
    {
      type: 'co',
      name: 'rounded-br-xl',
      description: 'Applies extra-large radius to the bottom-right corner via --radius-xl.',
      keywords: ['radius', 'rounded', 'bottom-right', 'corner', 'xl'],
    },
    {
      type: 'co',
      name: 'rounded-br-2xl',
      description: 'Applies very large radius to the bottom-right corner via --radius-2xl.',
      keywords: ['radius', 'rounded', 'bottom-right', 'corner', '2xl'],
    },
    {
      type: 'co',
      name: 'rounded-br-3xl',
      description: 'Applies larger radius to the bottom-right corner via --radius-3xl.',
      keywords: ['radius', 'rounded', 'bottom-right', 'corner', '3xl'],
    },
    {
      type: 'co',
      name: 'rounded-br-4xl',
      description: 'Applies largest radius to the bottom-right corner via --radius-4xl.',
      keywords: ['radius', 'rounded', 'bottom-right', 'corner', '4xl'],
    },
    {
      type: 'co',
      name: 'rounded-br-none',
      description: 'Removes radius from the bottom-right corner.',
      keywords: ['radius', 'rounded', 'bottom-right', 'none', 'reset'],
    },
    {
      type: 'co',
      name: 'rounded-br-full',
      description: 'Makes the bottom-right corner fully rounded using an infinite radius.',
      keywords: ['radius', 'rounded', 'bottom-right', 'full', 'pill'],
    },
    {
      type: 'co',
      name: 'rounded-bl-xs',
      description: 'Applies extra-small radius to the bottom-left corner via --radius-xs.',
      keywords: ['radius', 'rounded', 'bottom-left', 'corner', 'xs'],
    },
    {
      type: 'co',
      name: 'rounded-bl-sm',
      description: 'Applies small radius to the bottom-left corner via --radius-sm.',
      keywords: ['radius', 'rounded', 'bottom-left', 'corner', 'sm'],
    },
    {
      type: 'co',
      name: 'rounded-bl-md',
      description: 'Applies medium radius to the bottom-left corner via --radius-md.',
      keywords: ['radius', 'rounded', 'bottom-left', 'corner', 'md'],
    },
    {
      type: 'co',
      name: 'rounded-bl-lg',
      description: 'Applies large radius to the bottom-left corner via --radius-lg.',
      keywords: ['radius', 'rounded', 'bottom-left', 'corner', 'lg'],
    },

    {
      type: 'cc',
      name: 'divide-x-reverse',
      description: 'Reverses the side used for horizontal divide borders between siblings.',
      keywords: ['divide', 'border', 'separator', 'reverse', 'x'],
    },
    {
      type: 'cc',
      name: 'divide-y-reverse',
      description: 'Reverses the side used for vertical divide borders between siblings.',
      keywords: ['divide', 'border', 'separator', 'reverse', 'y'],
    },
    {
      type: 'vd',
      name: '[divide-x]',
      description:
        'Applies the raw --divide-x CSS variable directly to horizontal divider styling.',
      keywords: ['divide', 'border', 'separator', 'x', 'css-variable'],
    },
    {
      type: 'vd',
      name: '[divide-y]',
      description: 'Applies the raw --divide-y CSS variable directly to vertical divider styling.',
      keywords: ['divide', 'border', 'separator', 'y', 'css-variable'],
    },
  ],
};
