export default {
  text: 'Filters',
  items: [
    {
      type: 'vd',
      name: 'blur',
      accepts: 'raw',
      description: 'Sets a blur filter via --blur. E.g. 4px.',
      keywords: ['blur', 'filter', 'soft', 'defocus'],
    },
    {
      type: 'co',
      name: 'blur-sm',
      description: 'Applies a small blur filter preset.',
      keywords: ['blur', 'filter', 'small', 'soft'],
    },
    {
      type: 'co',
      name: 'blur-md',
      description: 'Applies a medium blur filter preset.',
      keywords: ['blur', 'filter', 'medium', 'soft'],
    },
    {
      type: 'co',
      name: 'blur-lg',
      description: 'Applies a large blur filter preset.',
      keywords: ['blur', 'filter', 'large'],
    },
    {
      type: 'cc',
      name: 'blur-none',
      description: 'Removes blur filter.',
      keywords: ['blur', 'filter', 'none', 'clear', 'sharp'],
    },
    {
      type: 'vd',
      name: 'brightness',
      accepts: 'raw',
      description: 'Sets brightness filter via --brightness. E.g. 0.5 to dim, 1.5 to brighten.',
      keywords: ['brightness', 'filter', 'light', 'dark', 'exposure'],
    },
    {
      type: 'vd',
      name: 'contrast',
      accepts: 'raw',
      description: 'Sets contrast filter via --contrast. E.g. 200%.',
      keywords: ['contrast', 'filter', 'pop', 'vivid'],
    },
    {
      type: 'vd',
      name: 'grayscale',
      accepts: 'raw',
      description: 'Sets grayscale filter via --grayscale. E.g. 100% for full desaturation.',
      keywords: ['grayscale', 'filter', 'desaturate', 'black-and-white', 'monochrome'],
    },
    {
      type: 'vd',
      name: 'saturate',
      accepts: 'raw',
      description: 'Sets saturation filter via --saturate. E.g. 0 to remove color, 2 to boost.',
      keywords: ['saturate', 'filter', 'color', 'vivid', 'muted'],
    },
    {
      type: 'vd',
      name: 'sepia',
      accepts: 'raw',
      description: 'Sets sepia filter via --sepia. E.g. 100% for full sepia tone.',
      keywords: ['sepia', 'filter', 'vintage', 'warm', 'tone'],
    },
    {
      type: 'vd',
      name: 'hue-rotate',
      accepts: 'raw',
      description: 'Sets hue-rotate filter via --hue-rotate. E.g. 90deg.',
      keywords: ['hue', 'rotate', 'filter', 'color', 'shift'],
    },
    {
      type: 'vd',
      name: 'invert',
      accepts: 'raw',
      description: 'Sets invert filter via --invert. E.g. 100% to fully invert colors.',
      keywords: ['invert', 'filter', 'negative', 'negate', 'dark'],
    },
    {
      type: 'vd',
      name: 'filter',
      accepts: 'raw',
      description:
        'Sets a fully custom filter string via --filter. E.g. blur(4px) brightness(1.2).',
      keywords: ['filter', 'custom', 'combined', 'effect'],
    },
    {
      type: 'cc',
      name: 'filter-none',
      description: 'Removes all filters.',
      keywords: ['filter', 'none', 'reset', 'clear'],
    },
    {
      type: 'vd',
      name: 'backdrop-blur',
      accepts: 'raw',
      description: 'Sets backdrop-blur via --backdrop-blur. Blurs content behind the element.',
      keywords: ['backdrop', 'blur', 'filter', 'glass', 'frosted'],
    },
    {
      type: 'co',
      name: 'backdrop-blur-sm',
      description: 'Applies a small backdrop blur preset.',
      keywords: ['backdrop', 'blur', 'small', 'glass'],
    },
    {
      type: 'co',
      name: 'backdrop-blur-md',
      description: 'Applies a medium backdrop blur preset. Good for frosted glass effects.',
      keywords: ['backdrop', 'blur', 'medium', 'glass', 'frosted'],
    },
    {
      type: 'co',
      name: 'backdrop-blur-lg',
      description: 'Applies a large backdrop blur preset.',
      keywords: ['backdrop', 'blur', 'large', 'glass', 'frosted'],
    },
    {
      type: 'vd',
      name: 'backdrop-brightness',
      accepts: 'raw',
      description: 'Sets backdrop-brightness via --backdrop-brightness.',
      keywords: ['backdrop', 'brightness', 'filter', 'behind'],
    },
    {
      type: 'vd',
      name: 'backdrop-contrast',
      accepts: 'raw',
      description: 'Sets backdrop-contrast via --backdrop-contrast.',
      keywords: ['backdrop', 'contrast', 'filter', 'behind'],
    },
    {
      type: 'vd',
      name: 'backdrop-grayscale',
      accepts: 'raw',
      description: 'Sets backdrop-grayscale via --backdrop-grayscale.',
      keywords: ['backdrop', 'grayscale', 'filter', 'behind', 'monochrome'],
    },
    {
      type: 'vd',
      name: 'backdrop-saturate',
      accepts: 'raw',
      description: 'Sets backdrop-saturate via --backdrop-saturate.',
      keywords: ['backdrop', 'saturate', 'filter', 'color', 'behind'],
    },
    {
      type: 'vd',
      name: 'backdrop-filter',
      accepts: 'raw',
      description: 'Sets a fully custom backdrop-filter string via --backdrop-filter.',
      keywords: ['backdrop', 'filter', 'custom', 'glass', 'behind'],
    },
    {
      type: 'cc',
      name: 'backdrop-filter-none',
      description: 'Removes all backdrop filters.',
      keywords: ['backdrop', 'filter', 'none', 'reset'],
    },

    {
      type: 'co',
      name: 'backdrop-blur-xs',
      description:
        'Applies a small backdrop blur using the xs scale token, blurring content behind the element.',
      keywords: ['backdrop-filter', 'filters', 'blur', 'xs', 'backdrop'],
    },
    {
      type: 'co',
      name: 'backdrop-blur-xl',
      description:
        'Applies a large backdrop blur using the xl scale token, blurring content behind the element.',
      keywords: ['backdrop-filter', 'filters', 'blur', 'xl', 'backdrop'],
    },
    {
      type: 'co',
      name: 'backdrop-blur-2xl',
      description:
        'Applies a larger backdrop blur using the 2xl scale token, blurring content behind the element.',
      keywords: ['backdrop-filter', 'filters', 'blur', '2xl', 'backdrop'],
    },
    {
      type: 'co',
      name: 'backdrop-blur-3xl',
      description:
        'Applies the largest backdrop blur using the 3xl scale token, blurring content behind the element.',
      keywords: ['backdrop-filter', 'filters', 'blur', '3xl', 'backdrop'],
    },
    {
      type: 'co',
      name: 'backdrop-blur-none',
      description: 'Removes backdrop blur by setting the backdrop blur function to 0.',
      keywords: ['backdrop-filter', 'filters', 'blur', 'none', 'backdrop'],
    },
    {
      type: 'co',
      name: 'blur-xs',
      description: 'Applies a small blur filter to the element using the xs scale token.',
      keywords: ['filter', 'filters', 'blur', 'xs'],
    },
    {
      type: 'co',
      name: 'blur-xl',
      description: 'Applies a large blur filter to the element using the xl scale token.',
      keywords: ['filter', 'filters', 'blur', 'xl'],
    },
    {
      type: 'co',
      name: 'blur-2xl',
      description: 'Applies a larger blur filter to the element using the 2xl scale token.',
      keywords: ['filter', 'filters', 'blur', '2xl'],
    },
    {
      type: 'co',
      name: 'blur-3xl',
      description: 'Applies the largest blur filter to the element using the 3xl scale token.',
      keywords: ['filter', 'filters', 'blur', '3xl'],
    },

    {
      type: 'vd',
      name: 'backdrop-hue-rotate',
      description:
        'Rotates the hue of the backdrop behind an element. Often used in frosted-glass effects.',
      keywords: ['backdrop', 'filter', 'hue', 'color-shift', 'glass'],
    },
    {
      type: 'vd',
      name: 'backdrop-invert',
      description: 'Inverts colors behind an element using backdrop-filter.',
      keywords: ['backdrop', 'filter', 'invert', 'contrast', 'effects'],
    },
    {
      type: 'vd',
      name: 'backdrop-opacity',
      description: 'Fades the backdrop behind an element using backdrop-filter opacity.',
      keywords: ['backdrop', 'filter', 'opacity', 'fade', 'dim'],
    },
    {
      type: 'vd',
      name: 'backdrop-sepia',
      description: 'Applies a sepia tone to the backdrop behind an element.',
      keywords: ['backdrop', 'filter', 'sepia', 'vintage', 'tone'],
    },
  ],
};
