export default {
  text: 'Flexbox & Grid',
  items: [
    {
      type: 'vd',
      name: 'gap',
      accepts: 'scaled',
      description: 'Sets gap between flex/grid children via --gap. Scaled.',
      keywords: ['gap', 'spacing', 'gutter', 'flex', 'grid'],
    },
    {
      type: 'vd',
      name: 'gap-x',
      accepts: 'scaled',
      description: 'Sets column-gap via --gap-x. Scaled.',
      keywords: ['gap', 'column', 'horizontal', 'flex', 'grid'],
    },
    {
      type: 'vd',
      name: 'gap-y',
      accepts: 'scaled',
      description: 'Sets row-gap via --gap-y. Scaled.',
      keywords: ['gap', 'row', 'vertical', 'flex', 'grid'],
    },
    {
      type: 'cc',
      name: 'flex-row',
      description: 'Sets flex-direction: row.',
      keywords: ['flex', 'direction', 'row', 'horizontal'],
    },
    {
      type: 'cc',
      name: 'flex-col',
      description: 'Sets flex-direction: column.',
      keywords: ['flex', 'direction', 'column', 'vertical'],
    },
    {
      type: 'cc',
      name: 'flex-row-reverse',
      description: 'Sets flex-direction: row-reverse.',
      keywords: ['flex', 'direction', 'row', 'reverse'],
    },
    {
      type: 'cc',
      name: 'flex-col-reverse',
      description: 'Sets flex-direction: column-reverse.',
      keywords: ['flex', 'direction', 'column', 'reverse'],
    },
    {
      type: 'cc',
      name: 'flex-wrap',
      description: 'Sets flex-wrap: wrap. Items wrap to the next line.',
      keywords: ['flex', 'wrap', 'responsive', 'multi-line'],
    },
    {
      type: 'cc',
      name: 'flex-nowrap',
      description: 'Sets flex-wrap: nowrap. Items remain on one line.',
      keywords: ['flex', 'wrap', 'nowrap', 'single-line'],
    },
    {
      type: 'cc',
      name: 'flex-1',
      description: 'Sets flex: 1 1 0%. Item grows and shrinks equally.',
      keywords: ['flex', 'grow', 'shrink', 'equal'],
    },
    {
      type: 'cc',
      name: 'flex-auto',
      description: 'Sets flex: 1 1 auto. Grows and shrinks based on content size.',
      keywords: ['flex', 'auto', 'grow', 'shrink'],
    },
    {
      type: 'cc',
      name: 'flex-none',
      description: 'Sets flex: none. Item will not grow or shrink.',
      keywords: ['flex', 'none', 'fixed', 'no-shrink'],
    },
    {
      type: 'vd',
      name: 'flex',
      accepts: 'raw',
      description: 'Sets the flex shorthand via --flex. E.g. 1 1 auto.',
      keywords: ['flex', 'grow', 'shrink', 'basis', 'custom'],
    },
    {
      type: 'vd',
      name: 'basis',
      accepts: 'scaled',
      description: 'Sets flex-basis via --basis. Scaled. Use [basis] for raw values.',
      keywords: ['flex', 'basis', 'size', 'initial'],
    },
    {
      type: 'cc',
      name: 'grow-1',
      description: 'Sets flex-grow: 1. Item grows to fill available space.',
      keywords: ['flex', 'grow', 'expand'],
    },
    {
      type: 'cc',
      name: 'grow-0',
      description: 'Sets flex-grow: 0. Item will not grow.',
      keywords: ['flex', 'grow', 'no-grow', 'fixed'],
    },
    {
      type: 'cc',
      name: 'shrink-1',
      description: 'Sets flex-shrink: 1. Item shrinks when space is limited.',
      keywords: ['flex', 'shrink', 'compress'],
    },
    {
      type: 'cc',
      name: 'shrink-0',
      description: 'Sets flex-shrink: 0. Item will not shrink.',
      keywords: ['flex', 'shrink', 'no-shrink', 'fixed'],
    },
    {
      type: 'cc',
      name: 'justify-start',
      description: 'Sets justify-content: flex-start.',
      keywords: ['justify', 'content', 'start', 'left', 'flex', 'grid'],
    },
    {
      type: 'cc',
      name: 'justify-end',
      description: 'Sets justify-content: flex-end.',
      keywords: ['justify', 'content', 'end', 'right', 'flex', 'grid'],
    },
    {
      type: 'cc',
      name: 'justify-center',
      description: 'Sets justify-content: center.',
      keywords: ['justify', 'content', 'center', 'flex', 'grid'],
    },
    {
      type: 'cc',
      name: 'justify-between',
      description: 'Sets justify-content: space-between.',
      keywords: ['justify', 'content', 'between', 'space', 'flex', 'grid'],
    },
    {
      type: 'cc',
      name: 'justify-around',
      description: 'Sets justify-content: space-around.',
      keywords: ['justify', 'content', 'around', 'space', 'flex', 'grid'],
    },
    {
      type: 'cc',
      name: 'justify-evenly',
      description: 'Sets justify-content: space-evenly.',
      keywords: ['justify', 'content', 'evenly', 'space', 'flex', 'grid'],
    },
    {
      type: 'cc',
      name: 'justify-stretch',
      description: 'Sets justify-content: stretch.',
      keywords: ['justify', 'content', 'stretch', 'fill', 'grid'],
    },
    {
      type: 'cc',
      name: 'items-start',
      description: 'Sets align-items: flex-start.',
      keywords: ['align', 'items', 'start', 'top', 'flex', 'grid'],
    },
    {
      type: 'cc',
      name: 'items-end',
      description: 'Sets align-items: flex-end.',
      keywords: ['align', 'items', 'end', 'bottom', 'flex', 'grid'],
    },
    {
      type: 'cc',
      name: 'items-center',
      description: 'Sets align-items: center. Vertically centers children.',
      keywords: ['align', 'items', 'center', 'middle', 'flex', 'grid'],
    },
    {
      type: 'cc',
      name: 'items-stretch',
      description: 'Sets align-items: stretch. Children fill the cross axis.',
      keywords: ['align', 'items', 'stretch', 'fill', 'flex', 'grid'],
    },
    {
      type: 'cc',
      name: 'items-baseline',
      description: 'Sets align-items: baseline. Aligns children to their text baseline.',
      keywords: ['align', 'items', 'baseline', 'text', 'flex'],
    },
    {
      type: 'cc',
      name: 'self-auto',
      description: 'Sets align-self: auto on a single item.',
      keywords: ['align', 'self', 'auto', 'flex', 'grid'],
    },
    {
      type: 'cc',
      name: 'self-center',
      description: 'Sets align-self: center on a single item.',
      keywords: ['align', 'self', 'center', 'flex', 'grid'],
    },
    {
      type: 'cc',
      name: 'self-stretch',
      description: 'Sets align-self: stretch on a single item.',
      keywords: ['align', 'self', 'stretch', 'flex', 'grid'],
    },
    {
      type: 'cc',
      name: 'content-start',
      description: 'Sets align-content: flex-start.',
      keywords: ['align', 'content', 'start', 'flex', 'grid'],
    },
    {
      type: 'cc',
      name: 'content-center',
      description: 'Sets align-content: center.',
      keywords: ['align', 'content', 'center', 'flex', 'grid'],
    },
    {
      type: 'cc',
      name: 'content-between',
      description: 'Sets align-content: space-between.',
      keywords: ['align', 'content', 'between', 'space', 'flex', 'grid'],
    },
    {
      type: 'cc',
      name: 'place-content-center',
      description: 'Sets place-content: center. Shorthand for align + justify center.',
      keywords: ['place', 'content', 'center', 'grid', 'shorthand'],
    },
    {
      type: 'cc',
      name: 'place-items-center',
      description: 'Sets place-items: center. Centers items on both axes within their grid cell.',
      keywords: ['place', 'items', 'center', 'grid', 'shorthand'],
    },
    {
      type: 'vd',
      name: 'order',
      accepts: 'integer',
      description: 'Sets flex/grid order via --order. Raw integer.',
      keywords: ['order', 'sequence', 'flex', 'grid', 'sort'],
    },
    {
      type: 'cc',
      name: 'order-first',
      description: 'Sets order: -9999. Moves item to the very front.',
      keywords: ['order', 'first', 'flex', 'grid'],
    },
    {
      type: 'cc',
      name: 'order-last',
      description: 'Sets order: 9999. Moves item to the very end.',
      keywords: ['order', 'last', 'flex', 'grid'],
    },
    {
      type: 'vd',
      name: 'grid-cols',
      accepts: 'integer',
      description:
        'Sets grid-template-columns with N equal columns via --grid-cols. Use [grid-cols] for custom track definitions.',
      keywords: ['grid', 'columns', 'template', 'layout'],
    },
    {
      type: 'cc',
      name: 'grid-cols-none',
      description: 'Removes grid-template-columns.',
      keywords: ['grid', 'columns', 'reset', 'remove'],
    },
    {
      type: 'cc',
      name: 'grid-cols-subgrid',
      description:
        'Sets grid-template-columns: subgrid. Inherits column tracks from the parent grid.',
      keywords: ['grid', 'columns', 'subgrid', 'inherit', 'nested'],
    },
    {
      type: 'vd',
      name: 'grid-rows',
      accepts: 'integer',
      description: 'Sets grid-template-rows with N equal rows via --grid-rows.',
      keywords: ['grid', 'rows', 'template', 'layout'],
    },
    {
      type: 'vd',
      name: 'col-span',
      accepts: 'integer',
      description: 'Sets how many grid columns an item spans via --col-span.',
      keywords: ['grid', 'column', 'span', 'merge', 'colspan'],
    },
    {
      type: 'cc',
      name: 'col-span-full',
      description: 'Makes a grid item span all columns.',
      keywords: ['grid', 'column', 'span', 'full', 'merge'],
    },
    {
      type: 'cc',
      name: 'col-auto',
      description: 'Sets grid-column: auto.',
      keywords: ['grid', 'column', 'auto', 'placement'],
    },
    {
      type: 'vd',
      name: 'col-start',
      accepts: 'integer',
      description: 'Sets grid-column-start via --col-start. Raw integer.',
      keywords: ['grid', 'column', 'start', 'placement'],
    },
    {
      type: 'vd',
      name: 'col-end',
      accepts: 'integer',
      description: 'Sets grid-column-end via --col-end. Raw integer.',
      keywords: ['grid', 'column', 'end', 'placement'],
    },
    {
      type: 'vd',
      name: 'row-span',
      accepts: 'integer',
      description: 'Sets how many grid rows an item spans via --row-span.',
      keywords: ['grid', 'row', 'span', 'merge', 'rowspan'],
    },
    {
      type: 'cc',
      name: 'row-span-full',
      description: 'Makes a grid item span all rows.',
      keywords: ['grid', 'row', 'span', 'full', 'merge'],
    },
    {
      type: 'cc',
      name: 'grid-flow-row',
      description: 'Sets grid-auto-flow: row. Items flow row by row.',
      keywords: ['grid', 'flow', 'auto', 'row', 'direction'],
    },
    {
      type: 'cc',
      name: 'grid-flow-col',
      description: 'Sets grid-auto-flow: column. Items flow column by column.',
      keywords: ['grid', 'flow', 'auto', 'column', 'direction'],
    },
    {
      type: 'cc',
      name: 'grid-flow-dense',
      description: 'Sets grid-auto-flow: dense. Fills gaps aggressively, may reorder items.',
      keywords: ['grid', 'flow', 'dense', 'pack', 'fill'],
    },

    {
      type: 'cc',
      name: 'justify-normal',
      description:
        'Sets justify-content to normal, using the default content justification behavior.',
      keywords: ['justify-content', 'flexbox', 'grid', 'normal', 'alignment'],
    },
    {
      type: 'cc',
      name: 'justify-end-safe',
      description:
        'Justifies content to the end, falling back to start alignment when space is insufficient (overflow-safe).',
      keywords: ['justify-content', 'flexbox', 'grid', 'end', 'safe', 'overflow'],
    },
    {
      type: 'cc',
      name: 'justify-center-safe',
      description:
        'Justifies content to the center, falling back to start alignment when space is insufficient (overflow-safe).',
      keywords: ['justify-content', 'flexbox', 'grid', 'center', 'safe', 'overflow'],
    },
    {
      type: 'cc',
      name: 'justify-items-start',
      description: 'Aligns grid/flex items to the start of their inline axis via justify-items.',
      keywords: ['justify-items', 'grid', 'flexbox', 'start', 'alignment'],
    },
    {
      type: 'cc',
      name: 'justify-items-end',
      description: 'Aligns grid/flex items to the end of their inline axis via justify-items.',
      keywords: ['justify-items', 'grid', 'flexbox', 'end', 'alignment'],
    },
    {
      type: 'cc',
      name: 'justify-items-center',
      description: 'Centers grid/flex items along their inline axis via justify-items.',
      keywords: ['justify-items', 'grid', 'flexbox', 'center', 'alignment'],
    },
    {
      type: 'cc',
      name: 'justify-items-stretch',
      description: 'Stretches grid/flex items to fill their inline axis via justify-items.',
      keywords: ['justify-items', 'grid', 'flexbox', 'stretch', 'alignment'],
    },
    {
      type: 'cc',
      name: 'justify-items-end-safe',
      description:
        'Aligns items to the end of the inline axis, falling back to start when space is insufficient (overflow-safe).',
      keywords: ['justify-items', 'grid', 'flexbox', 'end', 'safe', 'overflow'],
    },
    {
      type: 'cc',
      name: 'justify-items-center-safe',
      description:
        'Centers items along the inline axis, falling back to start when space is insufficient (overflow-safe).',
      keywords: ['justify-items', 'grid', 'flexbox', 'center', 'safe', 'overflow'],
    },
    {
      type: 'cc',
      name: 'justify-items-normal',
      description: 'Sets justify-items to normal, using the default item justification behavior.',
      keywords: ['justify-items', 'grid', 'flexbox', 'normal', 'alignment'],
    },
    {
      type: 'cc',
      name: 'justify-self-auto',
      description:
        "Sets justify-self to auto, inheriting the parent's justify-items behavior for this item.",
      keywords: ['justify-self', 'grid', 'flexbox', 'auto', 'alignment'],
    },
    {
      type: 'cc',
      name: 'justify-self-start',
      description: 'Aligns this individual grid/flex item to the start of its inline axis.',
      keywords: ['justify-self', 'grid', 'flexbox', 'start', 'alignment'],
    },
    {
      type: 'cc',
      name: 'justify-self-end',
      description: 'Aligns this individual grid/flex item to the end of its inline axis.',
      keywords: ['justify-self', 'grid', 'flexbox', 'end', 'alignment'],
    },
    {
      type: 'cc',
      name: 'justify-self-center',
      description: 'Centers this individual grid/flex item along its inline axis.',
      keywords: ['justify-self', 'grid', 'flexbox', 'center', 'alignment'],
    },
    {
      type: 'cc',
      name: 'justify-self-stretch',
      description: 'Stretches this individual grid/flex item to fill its inline axis.',
      keywords: ['justify-self', 'grid', 'flexbox', 'stretch', 'alignment'],
    },
    {
      type: 'cc',
      name: 'justify-self-end-safe',
      description:
        'Aligns this item to the end of the inline axis, falling back to start when space is insufficient (overflow-safe).',
      keywords: ['justify-self', 'grid', 'flexbox', 'end', 'safe', 'overflow'],
    },
    {
      type: 'cc',
      name: 'justify-self-center-safe',
      description:
        'Centers this item along the inline axis, falling back to start when space is insufficient (overflow-safe).',
      keywords: ['justify-self', 'grid', 'flexbox', 'center', 'safe', 'overflow'],
    },

    {
      type: 'co',
      name: 'basis-3xs',
      description: 'Sets flex-basis to 3xs container width.',
      keywords: ['flex', 'basis', 'sizing', '3xs'],
    },
    {
      type: 'co',
      name: 'basis-2xs',
      description: 'Sets flex-basis to 2xs container width.',
      keywords: ['flex', 'basis', 'sizing', '2xs'],
    },
    {
      type: 'co',
      name: 'basis-xs',
      description: 'Sets flex-basis to extra small container width.',
      keywords: ['flex', 'basis', 'sizing', 'xs'],
    },
    {
      type: 'co',
      name: 'basis-sm',
      description: 'Sets flex-basis to small container width.',
      keywords: ['flex', 'basis', 'sizing', 'sm'],
    },
    {
      type: 'co',
      name: 'basis-md',
      description: 'Sets flex-basis to medium container width.',
      keywords: ['flex', 'basis', 'sizing', 'md'],
    },
    {
      type: 'co',
      name: 'basis-lg',
      description: 'Sets flex-basis to large container width.',
      keywords: ['flex', 'basis', 'sizing', 'lg'],
    },
    {
      type: 'co',
      name: 'basis-xl',
      description: 'Sets flex-basis to extra large container width.',
      keywords: ['flex', 'basis', 'sizing', 'xl'],
    },
    {
      type: 'co',
      name: 'basis-2xl',
      description: 'Sets flex-basis to 2xl container width.',
      keywords: ['flex', 'basis', 'sizing', '2xl'],
    },
    {
      type: 'co',
      name: 'basis-3xl',
      description: 'Sets flex-basis to 3xl container width.',
      keywords: ['flex', 'basis', 'sizing', '3xl'],
    },
    {
      type: 'co',
      name: 'basis-4xl',
      description: 'Sets flex-basis to 4xl container width.',
      keywords: ['flex', 'basis', 'sizing', '4xl'],
    },
    {
      type: 'co',
      name: 'basis-5xl',
      description: 'Sets flex-basis to 5xl container width.',
      keywords: ['flex', 'basis', 'sizing', '5xl'],
    },
    {
      type: 'co',
      name: 'basis-6xl',
      description: 'Sets flex-basis to 6xl container width.',
      keywords: ['flex', 'basis', 'sizing', '6xl'],
    },
    {
      type: 'co',
      name: 'basis-7xl',
      description: 'Sets flex-basis to 7xl container width.',
      keywords: ['flex', 'basis', 'sizing', '7xl'],
    },
    {
      type: 'cc',
      name: 'basis-auto',
      description: "Sets flex-basis to auto, basing its size on the element's content.",
      keywords: ['flex', 'basis', 'sizing', 'auto'],
    },
    {
      type: 'cc',
      name: 'basis-full',
      description: 'Sets flex-basis to 100%.',
      keywords: ['flex', 'basis', 'sizing', 'full'],
    },
    {
      type: 'cc',
      name: 'flex-initial',
      description:
        'Sets flex to 0 1 auto, preventing the element from growing but allowing it to shrink.',
      keywords: ['flex', 'initial', 'layout'],
    },
    {
      type: 'cc',
      name: 'flex-wrap-reverse',
      description: 'Allows flex items to wrap onto multiple lines in reverse order.',
      keywords: ['flex', 'wrap', 'reverse', 'layout'],
    },

    {
      type: 'cc',
      name: '-order-first',
      description: 'Sets the flex/grid order to 9999.',
      keywords: ['order', 'flexbox', 'grid', 'first'],
    },
    {
      type: 'cc',
      name: '-order-last',
      description: 'Sets the flex/grid order to -9999.',
      keywords: ['order', 'flexbox', 'grid', 'last'],
    },
    {
      type: 'cc',
      name: '-order-none',
      description: 'Sets the flex/grid order to 0.',
      keywords: ['order', 'flexbox', 'grid', 'none'],
    },
    {
      type: 'cc',
      name: 'order-none',
      description: 'Sets the flex/grid order to 0.',
      keywords: ['order', 'flexbox', 'grid', 'none'],
    },
    {
      type: 'cc',
      name: 'place-content-start',
      description:
        'Packs items toward the start of the block and inline axis in a flex/grid container.',
      keywords: ['place', 'content', 'start', 'grid', 'flexbox'],
    },
    {
      type: 'cc',
      name: 'place-content-end',
      description:
        'Packs items toward the end of the block and inline axis in a flex/grid container.',
      keywords: ['place', 'content', 'end', 'grid', 'flexbox'],
    },
    {
      type: 'cc',
      name: 'place-content-between',
      description:
        'Distributes items with equal space between them on both axes in a flex/grid container.',
      keywords: ['place', 'content', 'between', 'space', 'grid', 'flexbox'],
    },
    {
      type: 'cc',
      name: 'place-content-around',
      description:
        'Distributes items with equal space around them on both axes in a flex/grid container.',
      keywords: ['place', 'content', 'around', 'space', 'grid', 'flexbox'],
    },
    {
      type: 'cc',
      name: 'place-content-evenly',
      description:
        'Distributes items with equal space evenly on both axes in a flex/grid container.',
      keywords: ['place', 'content', 'evenly', 'space', 'grid', 'flexbox'],
    },
    {
      type: 'cc',
      name: 'place-content-baseline',
      description: 'Aligns content against the baseline on both axes in a flex/grid container.',
      keywords: ['place', 'content', 'baseline', 'grid', 'flexbox'],
    },
    {
      type: 'cc',
      name: 'place-content-stretch',
      description: 'Stretches items to fill the container on both axes in a flex/grid container.',
      keywords: ['place', 'content', 'stretch', 'grid', 'flexbox'],
    },
    {
      type: 'cc',
      name: 'place-content-end-safe',
      description:
        'Safely packs items toward the end of both axes, preventing data loss if content overflows.',
      keywords: ['place', 'content', 'end', 'safe', 'grid', 'flexbox'],
    },
    {
      type: 'cc',
      name: 'place-content-center-safe',
      description: 'Safely centers items on both axes, preventing data loss if content overflows.',
      keywords: ['place', 'content', 'center', 'safe', 'grid', 'flexbox'],
    },
    {
      type: 'cc',
      name: 'place-items-start',
      description: 'Aligns items to the start of their grid areas on both axes.',
      keywords: ['place', 'items', 'start', 'grid', 'flexbox'],
    },
    {
      type: 'cc',
      name: 'place-items-end',
      description: 'Aligns items to the end of their grid areas on both axes.',
      keywords: ['place', 'items', 'end', 'grid', 'flexbox'],
    },
    {
      type: 'cc',
      name: 'place-items-baseline',
      description: 'Aligns items against the baseline of their grid areas on both axes.',
      keywords: ['place', 'items', 'baseline', 'grid', 'flexbox'],
    },
    {
      type: 'cc',
      name: 'place-items-stretch',
      description: 'Stretches items to fill their grid areas on both axes.',
      keywords: ['place', 'items', 'stretch', 'grid', 'flexbox'],
    },
    {
      type: 'cc',
      name: 'place-items-end-safe',
      description:
        'Safely aligns items to the end of their grid areas, preventing overflow clipping.',
      keywords: ['place', 'items', 'end', 'safe', 'grid', 'flexbox'],
    },
    {
      type: 'cc',
      name: 'place-items-center-safe',
      description: 'Safely centers items in their grid areas, preventing overflow clipping.',
      keywords: ['place', 'items', 'center', 'safe', 'grid', 'flexbox'],
    },
    {
      type: 'cc',
      name: 'place-self-auto',
      description: "Sets the element's alignment in its grid area to auto.",
      keywords: ['place', 'self', 'auto', 'grid', 'flexbox'],
    },
    {
      type: 'cc',
      name: 'place-self-start',
      description: 'Aligns the element to the start of its grid area on both axes.',
      keywords: ['place', 'self', 'start', 'grid', 'flexbox'],
    },
    {
      type: 'cc',
      name: 'place-self-end',
      description: 'Aligns the element to the end of its grid area on both axes.',
      keywords: ['place', 'self', 'end', 'grid', 'flexbox'],
    },
    {
      type: 'cc',
      name: 'place-self-center',
      description: 'Centers the element within its grid area on both axes.',
      keywords: ['place', 'self', 'center', 'grid', 'flexbox'],
    },
    {
      type: 'cc',
      name: 'place-self-stretch',
      description: 'Stretches the element to fill its grid area on both axes.',
      keywords: ['place', 'self', 'stretch', 'grid', 'flexbox'],
    },
    {
      type: 'cc',
      name: 'place-self-end-safe',
      description:
        'Safely aligns the element to the end of its grid area, preventing overflow clipping.',
      keywords: ['place', 'self', 'end', 'safe', 'grid', 'flexbox'],
    },
    {
      type: 'cc',
      name: 'place-self-center-safe',
      description: 'Safely centers the element in its grid area, preventing overflow clipping.',
      keywords: ['place', 'self', 'center', 'safe', 'grid', 'flexbox'],
    },

    {
      type: 'vd',
      name: '[basis]',
      description:
        'Applies raw --basis directly to flex-basis. Controls the starting size of a flex item.',
      keywords: ['flex', 'basis', 'size', 'raw', 'flexbox'],
    },
    {
      type: 'vd',
      name: 'grow',
      accepts: 'numeric',
      description: 'Lets a flex item grow by the --grow factor when extra space is available.',
      keywords: ['flex', 'grow', 'expand', 'fill', 'flexbox'],
    },
    {
      type: 'vd',
      name: 'shrink',
      accepts: 'numeric',
      description: 'Lets a flex item shrink by the --shrink factor when space is limited.',
      keywords: ['flex', 'shrink', 'contract', 'overflow', 'flexbox'],
    },

    {
      type: 'cc',
      name: 'content-normal',
      description: 'Restores normal align-content packing for wrapped lines.',
      keywords: ['align-content', 'flex', 'grid', 'wrap', 'normal'],
    },
    {
      type: 'cc',
      name: 'content-end',
      description: 'Packs wrapped lines toward the end of the cross axis.',
      keywords: ['align-content', 'flex', 'grid', 'wrap', 'end'],
    },
    {
      type: 'cc',
      name: 'content-around',
      description: 'Distributes wrapped lines with space around each line.',
      keywords: ['align-content', 'flex', 'grid', 'wrap', 'space-around'],
    },
    {
      type: 'cc',
      name: 'content-evenly',
      description: 'Distributes wrapped lines with equal space between them.',
      keywords: ['align-content', 'flex', 'grid', 'wrap', 'space-evenly'],
    },

    {
      type: 'cc',
      name: 'content-baseline',
      description: 'Aligns wrapped lines to a shared baseline.',
      keywords: ['align-content', 'flex', 'grid', 'baseline', 'wrap'],
    },
    {
      type: 'cc',
      name: 'content-stretch',
      description: "Stretches wrapped lines to fill the container's cross axis.",
      keywords: ['align-content', 'flex', 'grid', 'stretch', 'wrap'],
    },
    {
      type: 'cc',
      name: 'items-end-safe',
      description: 'Aligns items to the cross-axis end using safe, overflow-aware alignment.',
      keywords: ['align-items', 'flex', 'end', 'safe', 'alignment'],
    },
    {
      type: 'cc',
      name: 'items-center-safe',
      description: 'Aligns items to the cross-axis center using safe, overflow-aware alignment.',
      keywords: ['align-items', 'flex', 'center', 'safe', 'alignment'],
    },
    {
      type: 'cc',
      name: 'items-baseline-last',
      description: 'Aligns items using their last baseline.',
      keywords: ['align-items', 'flex', 'baseline', 'last-baseline', 'alignment'],
    },
    {
      type: 'cc',
      name: 'self-start',
      description: 'Overrides item alignment to start on the cross axis.',
      keywords: ['align-self', 'flex', 'start', 'item', 'alignment'],
    },
    {
      type: 'cc',
      name: 'self-end',
      description: 'Overrides item alignment to end on the cross axis.',
      keywords: ['align-self', 'flex', 'end', 'item', 'alignment'],
    },
    {
      type: 'cc',
      name: 'self-baseline',
      description: 'Overrides item alignment to use its baseline.',
      keywords: ['align-self', 'flex', 'baseline', 'item', 'alignment'],
    },
    {
      type: 'cc',
      name: 'self-end-safe',
      description: 'Overrides item alignment to end on the cross axis with safe overflow handling.',
      keywords: ['align-self', 'flex', 'end', 'safe', 'alignment'],
    },
    {
      type: 'cc',
      name: 'self-center-safe',
      description:
        'Overrides item alignment to center on the cross axis with safe overflow handling.',
      keywords: ['align-self', 'flex', 'center', 'safe', 'alignment'],
    },
    {
      type: 'cc',
      name: 'self-baseline-last',
      description: 'Overrides item alignment to use its last baseline.',
      keywords: ['align-self', 'flex', 'baseline', 'last-baseline', 'alignment'],
    },
  ],
};
