export default {
  text: 'Sizing',
  items: [
    {
      type: 'vd',
      name: 'w',
      accepts: 'scaled',
      description: 'Sets width via --w. Scaled by spacing unit. Use [w] for raw values.',
      keywords: ['width', 'size', 'dimension'],
    },
    {
      type: 'cc',
      name: 'w-full',
      description: 'Sets width: 100%.',
      keywords: ['width', 'full', '100%'],
    },
    {
      type: 'cc',
      name: 'w-screen',
      description: 'Sets width: 100vw.',
      keywords: ['width', 'screen', 'viewport'],
    },
    {
      type: 'cc',
      name: 'w-auto',
      description: 'Sets width: auto.',
      keywords: ['width', 'auto'],
    },
    {
      type: 'cc',
      name: 'w-min',
      description: 'Sets width: min-content.',
      keywords: ['width', 'min-content', 'shrink', 'intrinsic'],
    },
    {
      type: 'cc',
      name: 'w-max',
      description: 'Sets width: max-content.',
      keywords: ['width', 'max-content', 'grow', 'intrinsic'],
    },
    {
      type: 'cc',
      name: 'w-fit',
      description: 'Sets width: fit-content.',
      keywords: ['width', 'fit-content', 'intrinsic'],
    },
    {
      type: 'vd',
      name: 'max-w',
      accepts: 'raw',
      description: 'Sets max-width via --max-w.',
      keywords: ['max-width', 'width', 'constraint', 'limit'],
    },
    {
      type: 'cc',
      name: 'max-w-full',
      description: 'Sets max-width: 100%.',
      keywords: ['max-width', 'full', 'constraint'],
    },
    {
      type: 'cc',
      name: 'max-w-none',
      description: 'Removes max-width constraint.',
      keywords: ['max-width', 'none', 'unconstrained'],
    },
    {
      type: 'vd',
      name: 'min-w',
      accepts: 'raw',
      description: 'Sets min-width via --min-w.',
      keywords: ['min-width', 'width', 'minimum'],
    },
    {
      type: 'vd',
      name: 'h',
      accepts: 'scaled',
      description: 'Sets height via --h. Scaled by spacing unit. Use [h] for raw values.',
      keywords: ['height', 'size', 'dimension'],
    },
    {
      type: 'cc',
      name: 'h-full',
      description: 'Sets height: 100%.',
      keywords: ['height', 'full', '100%'],
    },
    {
      type: 'cc',
      name: 'h-screen',
      description: 'Sets height: 100vh.',
      keywords: ['height', 'screen', 'viewport'],
    },
    {
      type: 'cc',
      name: 'h-dvh',
      description: 'Sets height: 100dvh (dynamic viewport height, accounts for mobile chrome).',
      keywords: ['height', 'dynamic', 'viewport', 'mobile', 'dvh'],
    },
    {
      type: 'cc',
      name: 'h-auto',
      description: 'Sets height: auto.',
      keywords: ['height', 'auto'],
    },
    {
      type: 'vd',
      name: 'max-h',
      accepts: 'raw',
      description: 'Sets max-height via --max-h.',
      keywords: ['max-height', 'height', 'constraint', 'limit'],
    },
    {
      type: 'cc',
      name: 'max-h-screen',
      description: 'Sets max-height: 100vh.',
      keywords: ['max-height', 'screen', 'viewport'],
    },
    {
      type: 'vd',
      name: 'min-h',
      accepts: 'raw',
      description: 'Sets min-height via --min-h.',
      keywords: ['min-height', 'height', 'minimum'],
    },
    {
      type: 'cc',
      name: 'min-h-screen',
      description: 'Sets min-height: 100vh.',
      keywords: ['min-height', 'screen', 'viewport', 'full'],
    },

    {
      type: 'cc',
      name: 'h-dvw',
      description: 'Sets height to 100% of the dynamic viewport width (100dvw).',
      keywords: ['height', 'sizing', 'viewport', 'dynamic', 'dvw'],
    },
    {
      type: 'cc',
      name: 'h-lvh',
      description: 'Sets height to 100% of the large viewport height (100lvh).',
      keywords: ['height', 'sizing', 'viewport', 'large', 'lvh'],
    },
    {
      type: 'cc',
      name: 'h-lvw',
      description: 'Sets height to 100% of the large viewport width (100lvw).',
      keywords: ['height', 'sizing', 'viewport', 'large', 'lvw'],
    },
    {
      type: 'cc',
      name: 'h-svh',
      description: 'Sets height to 100% of the small viewport height (100svh).',
      keywords: ['height', 'sizing', 'viewport', 'small', 'svh'],
    },
    {
      type: 'cc',
      name: 'h-svw',
      description: 'Sets height to 100% of the small viewport width (100svw).',
      keywords: ['height', 'sizing', 'viewport', 'small', 'svw'],
    },
    {
      type: 'cc',
      name: 'h-min',
      description: 'Sets height to the intrinsic min-content size of the element.',
      keywords: ['height', 'sizing', 'min-content', 'intrinsic'],
    },
    {
      type: 'cc',
      name: 'h-max',
      description: 'Sets height to the intrinsic max-content size of the element.',
      keywords: ['height', 'sizing', 'max-content', 'intrinsic'],
    },
    {
      type: 'cc',
      name: 'h-fit',
      description:
        "Sets height to fit-content, sizing based on the element's content within constraints.",
      keywords: ['height', 'sizing', 'fit-content', 'intrinsic'],
    },
    {
      type: 'cc',
      name: 'h-lh',
      description: 'Sets height to one line-height unit (1lh).',
      keywords: ['height', 'sizing', 'line-height', 'lh'],
    },
    {
      type: 'cc',
      name: 'max-h-none',
      description: 'Removes any max-height constraint by setting it to none.',
      keywords: ['max-height', 'sizing', 'none', 'constraint'],
    },
    {
      type: 'cc',
      name: 'max-h-full',
      description: 'Caps max-height at 100% of the containing block.',
      keywords: ['max-height', 'sizing', 'full', 'constraint'],
    },
    {
      type: 'cc',
      name: 'max-h-dvh',
      description: 'Caps max-height at 100% of the dynamic viewport height (100dvh).',
      keywords: ['max-height', 'sizing', 'viewport', 'dynamic', 'dvh'],
    },
    {
      type: 'cc',
      name: 'max-h-dvw',
      description: 'Caps max-height at 100% of the dynamic viewport width (100dvw).',
      keywords: ['max-height', 'sizing', 'viewport', 'dynamic', 'dvw'],
    },
    {
      type: 'cc',
      name: 'max-h-lvh',
      description: 'Caps max-height at 100% of the large viewport height (100lvh).',
      keywords: ['max-height', 'sizing', 'viewport', 'large', 'lvh'],
    },
    {
      type: 'cc',
      name: 'max-h-lvw',
      description: 'Caps max-height at 100% of the large viewport width (100lvw).',
      keywords: ['max-height', 'sizing', 'viewport', 'large', 'lvw'],
    },
    {
      type: 'cc',
      name: 'max-h-svh',
      description: 'Caps max-height at 100% of the small viewport height (100svh).',
      keywords: ['max-height', 'sizing', 'viewport', 'small', 'svh'],
    },
    {
      type: 'cc',
      name: 'max-h-svw',
      description: 'Caps max-height at 100% of the small viewport width (100svw).',
      keywords: ['max-height', 'sizing', 'viewport', 'small', 'svw'],
    },
    {
      type: 'cc',
      name: 'max-h-min',
      description: 'Caps max-height at the intrinsic min-content size of the element.',
      keywords: ['max-height', 'sizing', 'min-content', 'intrinsic'],
    },
    {
      type: 'cc',
      name: 'max-h-max',
      description: 'Caps max-height at the intrinsic max-content size of the element.',
      keywords: ['max-height', 'sizing', 'max-content', 'intrinsic'],
    },
    {
      type: 'cc',
      name: 'max-h-fit',
      description:
        "Caps max-height at fit-content, based on the element's content within constraints.",
      keywords: ['max-height', 'sizing', 'fit-content', 'intrinsic'],
    },
    {
      type: 'cc',
      name: 'max-h-lh',
      description: 'Caps max-height at one line-height unit (1lh).',
      keywords: ['max-height', 'sizing', 'line-height', 'lh'],
    },
    {
      type: 'co',
      name: 'max-w-3xs',
      description: 'Caps max-width at the 3xs container size scale token.',
      keywords: ['max-width', 'sizing', 'container', 'scale', '3xs'],
    },
    {
      type: 'co',
      name: 'max-w-2xs',
      description: 'Caps max-width at the 2xs container size scale token.',
      keywords: ['max-width', 'sizing', 'container', 'scale', '2xs'],
    },
    {
      type: 'co',
      name: 'max-w-xs',
      description: 'Caps max-width at the xs container size scale token.',
      keywords: ['max-width', 'sizing', 'container', 'scale', 'xs'],
    },
    {
      type: 'co',
      name: 'max-w-sm',
      description: 'Caps max-width at the sm container size scale token.',
      keywords: ['max-width', 'sizing', 'container', 'scale', 'sm'],
    },
    {
      type: 'co',
      name: 'max-w-md',
      description: 'Caps max-width at the md container size scale token.',
      keywords: ['max-width', 'sizing', 'container', 'scale', 'md'],
    },
    {
      type: 'co',
      name: 'max-w-lg',
      description: 'Caps max-width at the lg container size scale token.',
      keywords: ['max-width', 'sizing', 'container', 'scale', 'lg'],
    },
    {
      type: 'co',
      name: 'max-w-xl',
      description: 'Caps max-width at the xl container size scale token.',
      keywords: ['max-width', 'sizing', 'container', 'scale', 'xl'],
    },
    {
      type: 'co',
      name: 'max-w-2xl',
      description: 'Caps max-width at the 2xl container size scale token.',
      keywords: ['max-width', 'sizing', 'container', 'scale', '2xl'],
    },
    {
      type: 'co',
      name: 'max-w-3xl',
      description: 'Caps max-width at the 3xl container size scale token.',
      keywords: ['max-width', 'sizing', 'container', 'scale', '3xl'],
    },
    {
      type: 'co',
      name: 'max-w-4xl',
      description: 'Caps max-width at the 4xl container size scale token.',
      keywords: ['max-width', 'sizing', 'container', 'scale', '4xl'],
    },
    {
      type: 'co',
      name: 'max-w-5xl',
      description: 'Caps max-width at the 5xl container size scale token.',
      keywords: ['max-width', 'sizing', 'container', 'scale', '5xl'],
    },
    {
      type: 'co',
      name: 'max-w-6xl',
      description: 'Caps max-width at the 6xl container size scale token.',
      keywords: ['max-width', 'sizing', 'container', 'scale', '6xl'],
    },
    {
      type: 'co',
      name: 'max-w-7xl',
      description: 'Caps max-width at the 7xl container size scale token.',
      keywords: ['max-width', 'sizing', 'container', 'scale', '7xl'],
    },
    {
      type: 'cc',
      name: 'max-w-screen',
      description: 'Caps max-width at 100% of the viewport width (100vw).',
      keywords: ['max-width', 'sizing', 'viewport', 'screen'],
    },
    {
      type: 'cc',
      name: 'max-w-dvw',
      description: 'Caps max-width at 100% of the dynamic viewport width (100dvw).',
      keywords: ['max-width', 'sizing', 'viewport', 'dynamic', 'dvw'],
    },
    {
      type: 'cc',
      name: 'max-w-dvh',
      description: 'Caps max-width at 100% of the dynamic viewport height (100dvh).',
      keywords: ['max-width', 'sizing', 'viewport', 'dynamic', 'dvh'],
    },
    {
      type: 'cc',
      name: 'max-w-lvw',
      description: 'Caps max-width at 100% of the large viewport width (100lvw).',
      keywords: ['max-width', 'sizing', 'viewport', 'large', 'lvw'],
    },
    {
      type: 'cc',
      name: 'max-w-lvh',
      description: 'Caps max-width at 100% of the large viewport height (100lvh).',
      keywords: ['max-width', 'sizing', 'viewport', 'large', 'lvh'],
    },
    {
      type: 'cc',
      name: 'max-w-svw',
      description: 'Caps max-width at 100% of the small viewport width (100svw).',
      keywords: ['max-width', 'sizing', 'viewport', 'small', 'svw'],
    },
    {
      type: 'cc',
      name: 'max-w-svh',
      description: 'Caps max-width at 100% of the small viewport height (100svh).',
      keywords: ['max-width', 'sizing', 'viewport', 'small', 'svh'],
    },
    {
      type: 'cc',
      name: 'max-w-min',
      description: 'Caps max-width at the intrinsic min-content size of the element.',
      keywords: ['max-width', 'sizing', 'min-content', 'intrinsic'],
    },
    {
      type: 'cc',
      name: 'max-w-max',
      description: 'Caps max-width at the intrinsic max-content size of the element.',
      keywords: ['max-width', 'sizing', 'max-content', 'intrinsic'],
    },

    {
      type: 'cc',
      name: 'max-w-fit',
      description: "Sets the maximum width to fit the element's content.",
      keywords: ['max', 'width', 'fit', 'content', 'sizing'],
    },
    {
      type: 'cc',
      name: 'min-h-auto',
      description: 'Sets the minimum height to auto.',
      keywords: ['min', 'height', 'auto', 'sizing'],
    },
    {
      type: 'cc',
      name: 'min-h-full',
      description: 'Sets the minimum height to 100% of the parent container.',
      keywords: ['min', 'height', 'full', '100%', 'sizing'],
    },
    {
      type: 'cc',
      name: 'min-h-dvh',
      description: 'Sets the minimum height to 100 dynamic viewport heights.',
      keywords: ['min', 'height', 'viewport', 'dynamic', 'dvh'],
    },
    {
      type: 'cc',
      name: 'min-h-dvw',
      description: 'Sets the minimum height to 100 dynamic viewport widths.',
      keywords: ['min', 'height', 'viewport', 'dynamic', 'dvw'],
    },
    {
      type: 'cc',
      name: 'min-h-lvh',
      description: 'Sets the minimum height to 100 large viewport heights.',
      keywords: ['min', 'height', 'viewport', 'large', 'lvh'],
    },
    {
      type: 'cc',
      name: 'min-h-lvw',
      description: 'Sets the minimum height to 100 large viewport widths.',
      keywords: ['min', 'height', 'viewport', 'large', 'lvw'],
    },
    {
      type: 'cc',
      name: 'min-h-svh',
      description: 'Sets the minimum height to 100 small viewport heights.',
      keywords: ['min', 'height', 'viewport', 'small', 'svh'],
    },
    {
      type: 'cc',
      name: 'min-h-svw',
      description: 'Sets the minimum height to 100 small viewport widths.',
      keywords: ['min', 'height', 'viewport', 'small', 'svw'],
    },
    {
      type: 'cc',
      name: 'min-h-min',
      description: 'Sets the minimum height to the intrinsic minimum height of the content.',
      keywords: ['min', 'height', 'content', 'intrinsic'],
    },
    {
      type: 'cc',
      name: 'min-h-max',
      description: 'Sets the minimum height to the intrinsic maximum height of the content.',
      keywords: ['min', 'height', 'content', 'intrinsic', 'max'],
    },
    {
      type: 'cc',
      name: 'min-h-fit',
      description: "Sets the minimum height to fit the element's content.",
      keywords: ['min', 'height', 'fit', 'content'],
    },
    {
      type: 'cc',
      name: 'min-h-lh',
      description: 'Sets the minimum height to exactly 1 line height.',
      keywords: ['min', 'height', 'line', 'lh'],
    },
    {
      type: 'co',
      name: 'min-w-3xs',
      description: 'Sets the minimum width to the 3xs container size variable.',
      keywords: ['min', 'width', 'container', '3xs', 'sizing'],
    },
    {
      type: 'co',
      name: 'min-w-2xs',
      description: 'Sets the minimum width to the 2xs container size variable.',
      keywords: ['min', 'width', 'container', '2xs', 'sizing'],
    },
    {
      type: 'co',
      name: 'min-w-xs',
      description: 'Sets the minimum width to the xs container size variable.',
      keywords: ['min', 'width', 'container', 'xs', 'sizing'],
    },
    {
      type: 'co',
      name: 'min-w-sm',
      description: 'Sets the minimum width to the sm container size variable.',
      keywords: ['min', 'width', 'container', 'sm', 'sizing'],
    },
    {
      type: 'co',
      name: 'min-w-md',
      description: 'Sets the minimum width to the md container size variable.',
      keywords: ['min', 'width', 'container', 'md', 'sizing'],
    },
    {
      type: 'co',
      name: 'min-w-lg',
      description: 'Sets the minimum width to the lg container size variable.',
      keywords: ['min', 'width', 'container', 'lg', 'sizing'],
    },
    {
      type: 'co',
      name: 'min-w-xl',
      description: 'Sets the minimum width to the xl container size variable.',
      keywords: ['min', 'width', 'container', 'xl', 'sizing'],
    },
    {
      type: 'co',
      name: 'min-w-2xl',
      description: 'Sets the minimum width to the 2xl container size variable.',
      keywords: ['min', 'width', 'container', '2xl', 'sizing'],
    },
    {
      type: 'co',
      name: 'min-w-3xl',
      description: 'Sets the minimum width to the 3xl container size variable.',
      keywords: ['min', 'width', 'container', '3xl', 'sizing'],
    },
    {
      type: 'co',
      name: 'min-w-4xl',
      description: 'Sets the minimum width to the 4xl container size variable.',
      keywords: ['min', 'width', 'container', '4xl', 'sizing'],
    },
    {
      type: 'co',
      name: 'min-w-5xl',
      description: 'Sets the minimum width to the 5xl container size variable.',
      keywords: ['min', 'width', 'container', '5xl', 'sizing'],
    },
    {
      type: 'co',
      name: 'min-w-6xl',
      description: 'Sets the minimum width to the 6xl container size variable.',
      keywords: ['min', 'width', 'container', '6xl', 'sizing'],
    },
    {
      type: 'co',
      name: 'min-w-7xl',
      description: 'Sets the minimum width to the 7xl container size variable.',
      keywords: ['min', 'width', 'container', '7xl', 'sizing'],
    },
    {
      type: 'cc',
      name: 'min-w-auto',
      description: 'Sets the minimum width to auto.',
      keywords: ['min', 'width', 'auto', 'sizing'],
    },
    {
      type: 'cc',
      name: 'min-w-full',
      description: 'Sets the minimum width to 100% of the parent container.',
      keywords: ['min', 'width', 'full', '100%', 'sizing'],
    },
    {
      type: 'cc',
      name: 'min-w-screen',
      description: 'Sets the minimum width to 100vw (viewport width).',
      keywords: ['min', 'width', 'screen', 'viewport', '100vw'],
    },
    {
      type: 'cc',
      name: 'min-w-dvw',
      description: 'Sets the minimum width to 100 dynamic viewport widths.',
      keywords: ['min', 'width', 'viewport', 'dynamic', 'dvw'],
    },
    {
      type: 'cc',
      name: 'min-w-dvh',
      description: 'Sets the minimum width to 100 dynamic viewport heights.',
      keywords: ['min', 'width', 'viewport', 'dynamic', 'dvh'],
    },
    {
      type: 'cc',
      name: 'min-w-lvw',
      description: 'Sets the minimum width to 100 large viewport widths.',
      keywords: ['min', 'width', 'viewport', 'large', 'lvw'],
    },
    {
      type: 'cc',
      name: 'min-w-lvh',
      description: 'Sets the minimum width to 100 large viewport heights.',
      keywords: ['min', 'width', 'viewport', 'large', 'lvh'],
    },
    {
      type: 'cc',
      name: 'min-w-svw',
      description: 'Sets the minimum width to 100 small viewport widths.',
      keywords: ['min', 'width', 'viewport', 'small', 'svw'],
    },
    {
      type: 'cc',
      name: 'min-w-svh',
      description: 'Sets the minimum width to 100 small viewport heights.',
      keywords: ['min', 'width', 'viewport', 'small', 'svh'],
    },
    {
      type: 'cc',
      name: 'min-w-min',
      description: 'Sets the minimum width to the intrinsic minimum width of the content.',
      keywords: ['min', 'width', 'content', 'intrinsic'],
    },
    {
      type: 'cc',
      name: 'min-w-max',
      description: 'Sets the minimum width to the intrinsic maximum width of the content.',
      keywords: ['min', 'width', 'content', 'intrinsic', 'max'],
    },
    {
      type: 'cc',
      name: 'min-w-fit',
      description: "Sets the minimum width to fit the element's content.",
      keywords: ['min', 'width', 'fit', 'content'],
    },
    {
      type: 'cc',
      name: 'size-auto',
      description: 'Sets both width and height to auto.',
      keywords: ['size', 'width', 'height', 'auto'],
    },
    {
      type: 'cc',
      name: 'size-full',
      description: 'Sets both width and height to 100%.',
      keywords: ['size', 'width', 'height', 'full', '100%'],
    },
    {
      type: 'cc',
      name: 'size-dvw',
      description: 'Sets both width and height to 100 dynamic viewport widths.',
      keywords: ['size', 'width', 'height', 'viewport', 'dvw'],
    },

    {
      type: 'vd',
      name: '[h]',
      description: 'Applies raw --h directly to height. Use for custom, unscaled sizing.',
      keywords: ['height', 'sizing', 'raw', 'dimension'],
    },

    {
      type: 'vd',
      name: '[max-h]',
      description: 'Caps height using raw --max-h. Useful for responsive size constraints.',
      keywords: ['max-height', 'sizing', 'constraint', 'raw'],
    },
    {
      type: 'vd',
      name: '[max-w]',
      description: 'Caps width using raw --max-w. Useful for responsive size constraints.',
      keywords: ['max-width', 'sizing', 'constraint', 'raw'],
    },
    {
      type: 'vd',
      name: '[min-h]',
      description: 'Enforces a minimum height using raw --min-h.',
      keywords: ['min-height', 'sizing', 'constraint', 'raw'],
    },
    {
      type: 'vd',
      name: '[min-w]',
      description: 'Enforces a minimum width using raw --min-w.',
      keywords: ['min-width', 'sizing', 'constraint', 'raw'],
    },
    {
      type: 'vd',
      name: 'size',
      accepts: 'numeric',
      description:
        'Sets width and height together via --size. Scaled by spacing unit. Use [size] for raw dimensions.',
      keywords: ['size', 'width', 'height', 'square', 'spacing'],
    },
    {
      type: 'vd',
      name: '[size]',
      description:
        'Applies raw --size directly to width and height. Use size for spacing-scaled dimensions.',
      keywords: ['size', 'width', 'height', 'square', 'raw'],
    },
    {
      type: 'vd',
      name: '[w]',
      description: 'Applies raw --w directly to width. Use for custom, unscaled sizing.',
      keywords: ['width', 'sizing', 'raw', 'dimension'],
    },

    {
      type: 'cc',
      name: 'aspect-auto',
      description:
        'Resets aspect ratio to auto so sizing follows intrinsic content and constraints.',
      keywords: ['aspect-ratio', 'sizing', 'responsive', 'media', 'auto'],
    },
    {
      type: 'cc',
      name: 'size-dvh',
      description: 'Sets both width and height to 100% of the dynamic viewport height (100dvh).',
      keywords: ['size', 'sizing', 'width', 'height', 'viewport', 'dynamic', 'dvh'],
    },
    {
      type: 'cc',
      name: 'size-lvw',
      description: 'Sets both width and height to 100% of the large viewport width (100lvw).',
      keywords: ['size', 'sizing', 'width', 'height', 'viewport', 'large', 'lvw'],
    },
    {
      type: 'cc',
      name: 'size-lvh',
      description: 'Sets both width and height to 100% of the large viewport height (100lvh).',
      keywords: ['size', 'sizing', 'width', 'height', 'viewport', 'large', 'lvh'],
    },
    {
      type: 'cc',
      name: 'size-svw',
      description: 'Sets both width and height to 100% of the small viewport width (100svw).',
      keywords: ['size', 'sizing', 'width', 'height', 'viewport', 'small', 'svw'],
    },
    {
      type: 'cc',
      name: 'size-svh',
      description: 'Sets both width and height to 100% of the small viewport height (100svh).',
      keywords: ['size', 'sizing', 'width', 'height', 'viewport', 'small', 'svh'],
    },
    {
      type: 'cc',
      name: 'size-min',
      description: 'Sets both width and height to their intrinsic min-content size.',
      keywords: ['size', 'sizing', 'width', 'height', 'min-content', 'intrinsic'],
    },
    {
      type: 'cc',
      name: 'size-max',
      description: 'Sets both width and height to their intrinsic max-content size.',
      keywords: ['size', 'sizing', 'width', 'height', 'max-content', 'intrinsic'],
    },
    {
      type: 'cc',
      name: 'size-fit',
      description:
        "Sets both width and height to fit-content, sizing based on the element's content within constraints.",
      keywords: ['size', 'sizing', 'width', 'height', 'fit-content', 'intrinsic'],
    },
    {
      type: 'co',
      name: 'w-3xs',
      description: 'Sets width to the 3xs container size scale token.',
      keywords: ['width', 'sizing', 'container', 'scale', '3xs'],
    },
    {
      type: 'co',
      name: 'w-2xs',
      description: 'Sets width to the 2xs container size scale token.',
      keywords: ['width', 'sizing', 'container', 'scale', '2xs'],
    },
    {
      type: 'co',
      name: 'w-xs',
      description: 'Sets width to the xs container size scale token.',
      keywords: ['width', 'sizing', 'container', 'scale', 'xs'],
    },
    {
      type: 'co',
      name: 'w-sm',
      description: 'Sets width to the sm container size scale token.',
      keywords: ['width', 'sizing', 'container', 'scale', 'sm'],
    },
    {
      type: 'co',
      name: 'w-md',
      description: 'Sets width to the md container size scale token.',
      keywords: ['width', 'sizing', 'container', 'scale', 'md'],
    },
    {
      type: 'co',
      name: 'w-lg',
      description: 'Sets width to the lg container size scale token.',
      keywords: ['width', 'sizing', 'container', 'scale', 'lg'],
    },
    {
      type: 'co',
      name: 'w-xl',
      description: 'Sets width to the xl container size scale token.',
      keywords: ['width', 'sizing', 'container', 'scale', 'xl'],
    },
    {
      type: 'co',
      name: 'w-2xl',
      description: 'Sets width to the 2xl container size scale token.',
      keywords: ['width', 'sizing', 'container', 'scale', '2xl'],
    },
    {
      type: 'co',
      name: 'w-3xl',
      description: 'Sets width to the 3xl container size scale token.',
      keywords: ['width', 'sizing', 'container', 'scale', '3xl'],
    },
    {
      type: 'co',
      name: 'w-4xl',
      description: 'Sets width to the 4xl container size scale token.',
      keywords: ['width', 'sizing', 'container', 'scale', '4xl'],
    },
    {
      type: 'co',
      name: 'w-5xl',
      description: 'Sets width to the 5xl container size scale token.',
      keywords: ['width', 'sizing', 'container', 'scale', '5xl'],
    },
    {
      type: 'co',
      name: 'w-6xl',
      description: 'Sets width to the 6xl container size scale token.',
      keywords: ['width', 'sizing', 'container', 'scale', '6xl'],
    },
    {
      type: 'co',
      name: 'w-7xl',
      description: 'Sets width to the 7xl container size scale token.',
      keywords: ['width', 'sizing', 'container', 'scale', '7xl'],
    },
    {
      type: 'cc',
      name: 'w-dvw',
      description: 'Sets width to 100% of the dynamic viewport width (100dvw).',
      keywords: ['width', 'sizing', 'viewport', 'dynamic', 'dvw'],
    },
    {
      type: 'cc',
      name: 'w-dvh',
      description: 'Sets width to 100% of the dynamic viewport height (100dvh).',
      keywords: ['width', 'sizing', 'viewport', 'dynamic', 'dvh'],
    },
    {
      type: 'cc',
      name: 'w-lvw',
      description: 'Sets width to 100% of the large viewport width (100lvw).',
      keywords: ['width', 'sizing', 'viewport', 'large', 'lvw'],
    },
    {
      type: 'cc',
      name: 'w-lvh',
      description: 'Sets width to 100% of the large viewport height (100lvh).',
      keywords: ['width', 'sizing', 'viewport', 'large', 'lvh'],
    },
    {
      type: 'cc',
      name: 'w-svw',
      description: 'Sets width to 100% of the small viewport width (100svw).',
      keywords: ['width', 'sizing', 'viewport', 'small', 'svw'],
    },
    {
      type: 'cc',
      name: 'w-svh',
      description: 'Sets width to 100% of the small viewport height (100svh).',
      keywords: ['width', 'sizing', 'viewport', 'small', 'svh'],
    },
  ],
};
