export default {
  text: 'Typography',
  items: [
    {
      type: 'vd',
      name: 'color',
      accepts: 'color-mix',
      description: 'Sets the text color via --color.',
      keywords: ['text', 'font', 'foreground', 'label', 'color'],
    },
    {
      type: 'vd',
      name: 'color/o',
      accepts: 'numeric',
      unit: '%',
      min: 0,
      max: 100,
      step: 1,
      description: 'Sets text color + opacity via --color and --color-o independently.',
      keywords: ['text', 'font', 'foreground', 'color', 'transparent', 'alpha'],
    },
    {
      type: 'vd',
      name: 'font-size',
      accepts: 'raw',
      description: 'Sets font-size via --font-size. E.g. 2rem, 18px.',
      keywords: ['font', 'size', 'text', 'scale'],
    },
    {
      type: 'co',
      name: 'text-xs',
      description: 'Sets font-size to xs preset.',
      keywords: ['font', 'size', 'xs', 'tiny', 'small'],
    },
    {
      type: 'co',
      name: 'text-sm',
      description: 'Sets font-size to sm preset.',
      keywords: ['font', 'size', 'sm', 'small'],
    },
    {
      type: 'co',
      name: 'text-base',
      description: 'Sets font-size to base preset. The default body text size.',
      keywords: ['font', 'size', 'base', 'body', 'default'],
    },
    {
      type: 'co',
      name: 'text-lg',
      description: 'Sets font-size to lg preset.',
      keywords: ['font', 'size', 'lg', 'large'],
    },
    {
      type: 'co',
      name: 'text-xl',
      description: 'Sets font-size to xl preset.',
      keywords: ['font', 'size', 'xl', 'large', 'heading'],
    },
    {
      type: 'co',
      name: 'text-2xl',
      description: 'Sets font-size to 2xl preset.',
      keywords: ['font', 'size', '2xl', 'heading', 'display'],
    },
    {
      type: 'co',
      name: 'text-4xl',
      description: 'Sets font-size to 4xl preset.',
      keywords: ['font', 'size', '4xl', 'heading', 'display', 'large'],
    },
    {
      type: 'vd',
      name: 'font-family',
      accepts: 'raw',
      description: 'Sets font-family via --font-family. E.g. "Georgia", serif.',
      keywords: ['font', 'family', 'typeface', 'custom'],
    },
    {
      type: 'co',
      name: 'font-sans',
      description: 'Applies the configured sans-serif font stack.',
      keywords: ['font', 'family', 'sans', 'sans-serif'],
    },
    {
      type: 'co',
      name: 'font-serif',
      description: 'Applies the configured serif font stack.',
      keywords: ['font', 'family', 'serif', 'editorial'],
    },
    {
      type: 'co',
      name: 'font-mono',
      description: 'Applies the configured monospace font stack. Good for code.',
      keywords: ['font', 'family', 'mono', 'monospace', 'code'],
    },
    {
      type: 'cc',
      name: 'font-thin',
      description: 'Sets font-weight: 100.',
      keywords: ['font', 'weight', 'thin', '100'],
    },
    {
      type: 'cc',
      name: 'font-light',
      description: 'Sets font-weight: 300.',
      keywords: ['font', 'weight', 'light', '300'],
    },
    {
      type: 'cc',
      name: 'font-normal',
      description: 'Sets font-weight: 400.',
      keywords: ['font', 'weight', 'normal', 'regular', '400'],
    },
    {
      type: 'cc',
      name: 'font-medium',
      description: 'Sets font-weight: 500.',
      keywords: ['font', 'weight', 'medium', '500'],
    },
    {
      type: 'cc',
      name: 'font-semibold',
      description: 'Sets font-weight: 600.',
      keywords: ['font', 'weight', 'semibold', '600'],
    },
    {
      type: 'cc',
      name: 'font-bold',
      description: 'Sets font-weight: 700.',
      keywords: ['font', 'weight', 'bold', '700'],
    },
    {
      type: 'cc',
      name: 'font-black',
      description: 'Sets font-weight: 900.',
      keywords: ['font', 'weight', 'black', 'heavy', '900'],
    },
    {
      type: 'vd',
      name: 'tracking',
      accepts: 'raw',
      description: 'Sets letter-spacing via --tracking. Raw value. E.g. 0.05em.',
      keywords: ['tracking', 'letter-spacing', 'kerning', 'spacing'],
    },
    {
      type: 'cc',
      name: 'tracking-tight',
      description: 'Sets letter-spacing to tight preset.',
      keywords: ['tracking', 'letter-spacing', 'tight', 'condensed'],
    },
    {
      type: 'cc',
      name: 'tracking-wide',
      description: 'Sets letter-spacing to wide preset.',
      keywords: ['tracking', 'letter-spacing', 'wide', 'expanded'],
    },
    {
      type: 'cc',
      name: 'tracking-widest',
      description: 'Sets letter-spacing to widest preset.',
      keywords: ['tracking', 'letter-spacing', 'widest', 'expanded', 'spaced'],
    },
    {
      type: 'vd',
      name: 'leading',
      accepts: 'scaled',
      description: 'Sets line-height via --leading. Scaled. Use [leading] for raw values.',
      keywords: ['leading', 'line-height', 'vertical', 'spacing'],
    },
    {
      type: 'cc',
      name: 'leading-none',
      description: 'Sets line-height: 1.',
      keywords: ['leading', 'line-height', 'none', 'tight', 'compact'],
    },
    {
      type: 'cc',
      name: 'leading-tight',
      description: 'Sets line-height to tight preset.',
      keywords: ['leading', 'line-height', 'tight', 'compact'],
    },
    {
      type: 'cc',
      name: 'leading-normal',
      description: 'Sets line-height to normal preset.',
      keywords: ['leading', 'line-height', 'normal', 'default'],
    },
    {
      type: 'cc',
      name: 'leading-loose',
      description: 'Sets line-height to loose preset.',
      keywords: ['leading', 'line-height', 'loose', 'spacious', 'relaxed'],
    },
    {
      type: 'cc',
      name: 'text-left',
      description: 'Sets text-align: left.',
      keywords: ['text', 'align', 'left'],
    },
    {
      type: 'cc',
      name: 'text-center',
      description: 'Sets text-align: center.',
      keywords: ['text', 'align', 'center'],
    },
    {
      type: 'cc',
      name: 'text-right',
      description: 'Sets text-align: right.',
      keywords: ['text', 'align', 'right'],
    },
    {
      type: 'cc',
      name: 'text-justify',
      description: 'Sets text-align: justify.',
      keywords: ['text', 'align', 'justify', 'block'],
    },
    {
      type: 'cc',
      name: 'uppercase',
      description: 'Sets text-transform: uppercase.',
      keywords: ['text', 'transform', 'uppercase', 'caps'],
    },
    {
      type: 'cc',
      name: 'lowercase',
      description: 'Sets text-transform: lowercase.',
      keywords: ['text', 'transform', 'lowercase'],
    },
    {
      type: 'cc',
      name: 'capitalize',
      description: 'Sets text-transform: capitalize.',
      keywords: ['text', 'transform', 'capitalize', 'title-case'],
    },
    {
      type: 'cc',
      name: 'normal-case',
      description: 'Resets text-transform.',
      keywords: ['text', 'transform', 'normal', 'reset'],
    },
    {
      type: 'cc',
      name: 'italic',
      description: 'Sets font-style: italic.',
      keywords: ['font', 'style', 'italic', 'oblique'],
    },
    {
      type: 'cc',
      name: 'not-italic',
      description: 'Sets font-style: normal. Resets italic.',
      keywords: ['font', 'style', 'normal', 'reset', 'italic'],
    },
    {
      type: 'cc',
      name: 'underline',
      description: 'Sets text-decoration-line: underline.',
      keywords: ['text', 'decoration', 'underline', 'link'],
    },
    {
      type: 'cc',
      name: 'overline',
      description: 'Sets text-decoration-line: overline.',
      keywords: ['text', 'decoration', 'overline'],
    },
    {
      type: 'cc',
      name: 'line-through',
      description: 'Sets text-decoration-line: line-through.',
      keywords: ['text', 'decoration', 'strikethrough', 'strike', 'delete'],
    },
    {
      type: 'cc',
      name: 'no-underline',
      description: 'Removes text-decoration.',
      keywords: ['text', 'decoration', 'underline', 'none', 'remove'],
    },
    {
      type: 'vd',
      name: 'decoration',
      accepts: 'color-mix',
      description: 'Sets text-decoration-color via --decoration.',
      keywords: ['text', 'decoration', 'color', 'underline'],
    },
    {
      type: 'vd',
      name: 'decoration/o',
      accepts: 'numeric',
      unit: '%',
      min: 0,
      max: 100,
      step: 1,
      description: 'Sets text-decoration-color + opacity via --decoration and --decoration-o.',
      keywords: ['text', 'decoration', 'color', 'opacity', 'alpha'],
    },
    {
      type: 'vd',
      name: 'decoration-thickness',
      accepts: 'raw',
      description: 'Sets text-decoration-thickness via --decoration-thickness. E.g. 2px.',
      keywords: ['text', 'decoration', 'thickness', 'width', 'underline'],
    },
    {
      type: 'cc',
      name: 'decoration-solid',
      description: 'Sets text-decoration-style: solid.',
      keywords: ['text', 'decoration', 'style', 'solid', 'underline'],
    },
    {
      type: 'cc',
      name: 'decoration-dashed',
      description: 'Sets text-decoration-style: dashed.',
      keywords: ['text', 'decoration', 'style', 'dashed', 'underline'],
    },
    {
      type: 'cc',
      name: 'decoration-dotted',
      description: 'Sets text-decoration-style: dotted.',
      keywords: ['text', 'decoration', 'style', 'dotted', 'underline'],
    },
    {
      type: 'cc',
      name: 'decoration-wavy',
      description: 'Sets text-decoration-style: wavy.',
      keywords: ['text', 'decoration', 'style', 'wavy', 'squiggly', 'underline'],
    },
    {
      type: 'vd',
      name: 'underline-offset',
      accepts: 'raw',
      description: 'Sets text-underline-offset via --underline-offset. E.g. 4px.',
      keywords: ['underline', 'offset', 'gap', 'spacing', 'decoration'],
    },
    {
      type: 'vd',
      name: 'indent',
      accepts: 'scaled',
      description: 'Sets text-indent via --indent. Scaled. Use [indent] for raw values.',
      keywords: ['text', 'indent', 'paragraph', 'tab'],
    },
    {
      type: 'cc',
      name: 'truncate',
      description: 'Truncates overflowing text with an ellipsis on a single line.',
      keywords: ['text', 'overflow', 'truncate', 'ellipsis', 'clip'],
    },
    {
      type: 'cc',
      name: 'text-ellipsis',
      description: 'Sets text-overflow: ellipsis.',
      keywords: ['text', 'overflow', 'ellipsis'],
    },
    {
      type: 'cc',
      name: 'line-clamp-2',
      description: 'Clamps text to 2 lines with an ellipsis.',
      keywords: ['text', 'clamp', 'lines', 'ellipsis', 'overflow'],
    },
    {
      type: 'cc',
      name: 'line-clamp-3',
      description: 'Clamps text to 3 lines with an ellipsis.',
      keywords: ['text', 'clamp', 'lines', 'ellipsis', 'overflow'],
    },
    {
      type: 'cc',
      name: 'whitespace-nowrap',
      description: 'Sets white-space: nowrap. Prevents line breaks.',
      keywords: ['whitespace', 'nowrap', 'wrap', 'line-break'],
    },
    {
      type: 'cc',
      name: 'whitespace-pre',
      description: 'Sets white-space: pre. Preserves whitespace and line breaks.',
      keywords: ['whitespace', 'pre', 'preserve', 'code'],
    },
    {
      type: 'cc',
      name: 'whitespace-pre-wrap',
      description: 'Sets white-space: pre-wrap. Preserves whitespace and wraps when needed.',
      keywords: ['whitespace', 'pre', 'wrap', 'preserve'],
    },
    {
      type: 'cc',
      name: 'break-words',
      description: 'Sets overflow-wrap: break-word. Breaks long words to prevent overflow.',
      keywords: ['word-break', 'overflow', 'wrap', 'break', 'long'],
    },
    {
      type: 'cc',
      name: 'break-all',
      description: 'Sets word-break: break-all. Breaks words at any character.',
      keywords: ['word-break', 'break-all', 'overflow', 'wrap'],
    },
    {
      type: 'cc',
      name: 'text-balance',
      description: 'Sets text-wrap: balance. Evenly balances line lengths. Best for headings.',
      keywords: ['text', 'wrap', 'balance', 'optical', 'heading'],
    },
    {
      type: 'cc',
      name: 'text-pretty',
      description: 'Sets text-wrap: pretty. Avoids orphans and improves multi-line wrapping.',
      keywords: ['text', 'wrap', 'pretty', 'orphan', 'paragraph'],
    },
    {
      type: 'cc',
      name: 'antialiased',
      description: 'Enables antialiased font smoothing.',
      keywords: ['font', 'smoothing', 'antialiased', 'rendering', 'sharp'],
    },
    {
      type: 'co',
      name: 'tabular-nums',
      description:
        'Sets font-variant-numeric: tabular-nums. Digits use equal widths for alignment.',
      keywords: ['font', 'numeric', 'tabular', 'digits', 'table', 'align'],
    },
    {
      type: 'cc',
      name: 'list-disc',
      description: 'Sets list-style-type: disc. Standard bulleted list.',
      keywords: ['list', 'bullet', 'disc', 'ul'],
    },
    {
      type: 'cc',
      name: 'list-decimal',
      description: 'Sets list-style-type: decimal. Numbered list.',
      keywords: ['list', 'numbered', 'decimal', 'ol'],
    },
    {
      type: 'cc',
      name: 'list-none',
      description: 'Sets list-style-type: none. Removes list markers.',
      keywords: ['list', 'none', 'reset', 'marker'],
    },
    {
      type: 'cc',
      name: 'list-inside',
      description: 'Sets list-style-position: inside.',
      keywords: ['list', 'position', 'inside'],
    },
    {
      type: 'cc',
      name: 'list-outside',
      description: 'Sets list-style-position: outside.',
      keywords: ['list', 'position', 'outside'],
    },
    {
      type: 'vd',
      name: 'align',
      accepts: 'raw',
      description: 'Sets vertical-align via --align. E.g. middle, baseline.',
      keywords: ['vertical-align', 'align', 'baseline', 'middle', 'inline'],
    },

    {
      type: 'cc',
      name: '-tracking-normal',
      description:
        'Sets letter-spacing to a negated zero value (-0em); functionally equivalent to normal tracking.',
      keywords: ['letter-spacing', 'typography', 'tracking', 'negative', 'normal'],
    },
    {
      type: 'cc',
      name: '-tracking-tight',
      description:
        'Applies a negative letter-spacing override that widens tracking by 0.025em (inverse of tight).',
      keywords: ['letter-spacing', 'typography', 'tracking', 'negative', 'tight'],
    },
    {
      type: 'cc',
      name: '-tracking-tighter',
      description:
        'Applies a negative letter-spacing override that widens tracking by 0.05em (inverse of tighter).',
      keywords: ['letter-spacing', 'typography', 'tracking', 'negative', 'tighter'],
    },
    {
      type: 'cc',
      name: '-tracking-wide',
      description:
        'Applies a negative letter-spacing of -0.025em, tightening tracking (inverse of wide).',
      keywords: ['letter-spacing', 'typography', 'tracking', 'negative', 'wide'],
    },
    {
      type: 'cc',
      name: '-tracking-wider',
      description:
        'Applies a negative letter-spacing of -0.05em, tightening tracking (inverse of wider).',
      keywords: ['letter-spacing', 'typography', 'tracking', 'negative', 'wider'],
    },
    {
      type: 'cc',
      name: '-tracking-widest',
      description:
        'Applies a negative letter-spacing of -0.1em, tightening tracking (inverse of widest).',
      keywords: ['letter-spacing', 'typography', 'tracking', 'negative', 'widest'],
    },
    {
      type: 'cc',
      name: 'tracking-normal',
      description: 'Sets letter-spacing to 0em, the default tracking value.',
      keywords: ['letter-spacing', 'typography', 'tracking', 'normal'],
    },
    {
      type: 'cc',
      name: 'tracking-tighter',
      description: 'Sets letter-spacing to -0.05em, tightening character spacing.',
      keywords: ['letter-spacing', 'typography', 'tracking', 'tighter'],
    },
    {
      type: 'cc',
      name: 'tracking-wider',
      description: 'Sets letter-spacing to 0.05em, loosening character spacing.',
      keywords: ['letter-spacing', 'typography', 'tracking', 'wider'],
    },
    {
      type: 'cc',
      name: 'leading-relaxed',
      description: 'Sets line-height to 1.625 for relaxed, airy text spacing.',
      keywords: ['line-height', 'typography', 'leading', 'relaxed'],
    },
    {
      type: 'cc',
      name: 'leading-snug',
      description: 'Sets line-height to 1.375 for snug, compact text spacing.',
      keywords: ['line-height', 'typography', 'leading', 'snug'],
    },

    {
      type: 'co',
      name: 'text-3xl',
      description: 'Sets text to 3xl size and line height.',
      keywords: ['text', 'font', 'size', '3xl', 'typography'],
    },
    {
      type: 'co',
      name: 'text-5xl',
      description: 'Sets text to 5xl size and line height.',
      keywords: ['text', 'font', 'size', '5xl', 'typography'],
    },
    {
      type: 'co',
      name: 'text-6xl',
      description: 'Sets text to 6xl size and line height.',
      keywords: ['text', 'font', 'size', '6xl', 'typography'],
    },
    {
      type: 'co',
      name: 'text-7xl',
      description: 'Sets text to 7xl size and line height.',
      keywords: ['text', 'font', 'size', '7xl', 'typography'],
    },
    {
      type: 'co',
      name: 'text-8xl',
      description: 'Sets text to 8xl size and line height.',
      keywords: ['text', 'font', 'size', '8xl', 'typography'],
    },
    {
      type: 'co',
      name: 'text-9xl',
      description: 'Sets text to 9xl size and line height.',
      keywords: ['text', 'font', 'size', '9xl', 'typography'],
    },
    {
      type: 'cc',
      name: 'font-extrabold',
      description: 'Sets the font weight to extrabold (800).',
      keywords: ['font', 'weight', 'extrabold', 'bold', 'typography'],
    },
    {
      type: 'cc',
      name: 'font-extralight',
      description: 'Sets the font weight to extralight (200).',
      keywords: ['font', 'weight', 'extralight', 'light', 'typography'],
    },

    {
      type: 'cc',
      name: 'hyphens-none',
      description: 'Prevents words from being hyphenated.',
      keywords: ['hyphens', 'typography', 'none', 'text'],
    },
    {
      type: 'cc',
      name: 'hyphens-manual',
      description: 'Allows hyphenation only where characters like &shy; are manually inserted.',
      keywords: ['hyphens', 'typography', 'manual', 'text'],
    },
    {
      type: 'cc',
      name: 'hyphens-auto',
      description: 'Allows the browser to automatically hyphenate words based on language rules.',
      keywords: ['hyphens', 'typography', 'auto', 'text'],
    },
    {
      type: 'cc',
      name: 'wrap-break-word',
      description:
        'Sets overflow-wrap to break-word, breaking unbreakable words to prevent overflow.',
      keywords: ['wrap', 'word', 'break', 'overflow', 'text'],
    },
    {
      type: 'cc',
      name: 'wrap-anywhere',
      description:
        'Sets overflow-wrap to anywhere, allowing unbreakable words to break at any point.',
      keywords: ['wrap', 'anywhere', 'overflow', 'text'],
    },
    {
      type: 'cc',
      name: 'wrap-normal',
      description: 'Sets overflow-wrap to normal, preventing breaks within words.',
      keywords: ['wrap', 'normal', 'overflow', 'text'],
    },
    {
      type: 'cc',
      name: 'text-clip',
      description: 'Clips text that overflows its container.',
      keywords: ['text', 'overflow', 'clip', 'typography'],
    },
    {
      type: 'cc',
      name: 'text-wrap',
      description: 'Allows text to wrap onto multiple lines.',
      keywords: ['text', 'wrap', 'typography'],
    },
    {
      type: 'cc',
      name: 'text-nowrap',
      description: 'Prevents text from wrapping, forcing it onto a single line.',
      keywords: ['text', 'nowrap', 'wrap', 'typography'],
    },
    {
      type: 'cc',
      name: 'align-baseline',
      description: 'Aligns the baseline of the element with the baseline of its parent.',
      keywords: ['align', 'vertical', 'baseline', 'text'],
    },
    {
      type: 'cc',
      name: 'align-top',
      description:
        'Aligns the top of the element and its descendants with the top of the entire line.',
      keywords: ['align', 'vertical', 'top', 'text'],
    },
    {
      type: 'cc',
      name: 'align-middle',
      description:
        'Aligns the middle of the element with the baseline plus half the x-height of the parent.',
      keywords: ['align', 'vertical', 'middle', 'text'],
    },
    {
      type: 'cc',
      name: 'align-bottom',
      description:
        'Aligns the bottom of the element and its descendants with the bottom of the entire line.',
      keywords: ['align', 'vertical', 'bottom', 'text'],
    },
    {
      type: 'cc',
      name: 'align-text-top',
      description: "Aligns the top of the element with the top of the parent element's font.",
      keywords: ['align', 'vertical', 'text', 'top'],
    },
    {
      type: 'cc',
      name: 'align-text-bottom',
      description: "Aligns the bottom of the element with the bottom of the parent element's font.",
      keywords: ['align', 'vertical', 'text', 'bottom'],
    },
    {
      type: 'cc',
      name: 'align-sub',
      description: 'Aligns the baseline of the element with the subscript-baseline of its parent.',
      keywords: ['align', 'vertical', 'sub', 'subscript', 'text'],
    },
    {
      type: 'cc',
      name: 'align-super',
      description:
        'Aligns the baseline of the element with the superscript-baseline of its parent.',
      keywords: ['align', 'vertical', 'super', 'superscript', 'text'],
    },
    {
      type: 'cc',
      name: 'whitespace-normal',
      description: 'Collapses whitespace and allows text to wrap normally.',
      keywords: ['whitespace', 'space', 'normal', 'text', 'wrap'],
    },
    {
      type: 'cc',
      name: 'whitespace-pre-line',
      description: 'Collapses whitespace but preserves line breaks.',
      keywords: ['whitespace', 'space', 'pre', 'line', 'text'],
    },
    {
      type: 'cc',
      name: 'whitespace-break-spaces',
      description: 'Preserves whitespace sequences and allows wrapping at spaces.',
      keywords: ['whitespace', 'space', 'break', 'text'],
    },
    {
      type: 'cc',
      name: 'break-normal',
      description: 'Uses the default word break and overflow wrap rules.',
      keywords: ['break', 'word', 'normal', 'text', 'wrap'],
    },
    {
      type: 'cc',
      name: 'break-keep',
      description: 'Prevents breaking within words, typically used for CJK text.',
      keywords: ['break', 'word', 'keep', 'all', 'text'],
    },

    {
      type: 'cc',
      name: 'line-clamp-1',
      description:
        'Truncates text to a single line and hides overflow. Useful for titles, labels, and compact previews.',
      keywords: ['clamp', 'truncate', 'ellipsis', 'single-line', 'text'],
    },
    {
      type: 'cc',
      name: 'line-clamp-4',
      description:
        'Limits text to four visible lines and clips the rest. Good for cards and content previews.',
      keywords: ['clamp', 'truncate', 'multiline', 'preview', 'text'],
    },
    {
      type: 'cc',
      name: 'line-clamp-5',
      description:
        'Limits text to five visible lines and clips the rest. Good for cards and content previews.',
      keywords: ['clamp', 'truncate', 'multiline', 'preview', 'text'],
    },
    {
      type: 'cc',
      name: 'line-clamp-6',
      description:
        'Limits text to six visible lines and clips the rest. Good for cards and content previews.',
      keywords: ['clamp', 'truncate', 'multiline', 'preview', 'text'],
    },
    {
      type: 'cc',
      name: 'line-clamp-none',
      description: 'Removes line clamping and restores normal multiline text overflow.',
      keywords: ['clamp', 'reset', 'multiline', 'overflow', 'text'],
    },
    {
      type: 'vd',
      name: '[leading]',
      description:
        'Applies raw --leading directly to line-height. Use leading utilities for scaled text spacing when available.',
      keywords: ['line-height', 'leading', 'text-spacing', 'raw'],
    },

    {
      type: 'vd',
      name: 'list',
      description: 'Changes the bullet or number marker style for list items via list-style-type.',
      keywords: ['list', 'bullet', 'marker', 'ul', 'ol'],
    },
    {
      type: 'vd',
      name: 'list-image',
      description: 'Replaces the list marker with an image via list-style-image.',
      keywords: ['list', 'marker', 'image', 'bullet', 'typography'],
    },
    {
      type: 'vd',
      name: '[indent]',
      description: 'Applies raw --indent directly to text-indent. Indents the first line of text.',
      keywords: ['indent', 'text-indent', 'paragraph', 'typography', 'raw'],
    },

    {
      type: 'cc',
      name: 'text-start',
      description:
        'Aligns text to the logical start edge (left in LTR, right in RTL) via text-align.',
      keywords: ['text-align', 'typography', 'start', 'logical', 'rtl'],
    },
    {
      type: 'cc',
      name: 'text-end',
      description:
        'Aligns text to the logical end edge (right in LTR, left in RTL) via text-align.',
      keywords: ['text-align', 'typography', 'end', 'logical', 'rtl'],
    },
    {
      type: 'cc',
      name: 'subpixel-antialiased',
      description:
        "Sets font smoothing to the browser's default (auto) subpixel-antialiased rendering.",
      keywords: ['typography', 'font-smoothing', 'antialiased', 'subpixel', 'rendering'],
    },
    {
      type: 'cc',
      name: 'normal-nums',
      description:
        'Resets font-variant-numeric to normal, clearing any numeric font variant styling.',
      keywords: ['typography', 'font-variant-numeric', 'normal', 'numbers'],
    },
    {
      type: 'co',
      name: 'ordinal',
      description: 'Enables ordinal numeral glyphs (e.g. 1st, 2nd) via font-variant-numeric.',
      keywords: ['typography', 'font-variant-numeric', 'ordinal', 'numbers'],
    },
    {
      type: 'co',
      name: 'slashed-zero',
      description:
        'Enables a slashed zero glyph via font-variant-numeric, distinguishing zero from the letter O.',
      keywords: ['typography', 'font-variant-numeric', 'slashed-zero', 'numbers'],
    },
    {
      type: 'co',
      name: 'lining-nums',
      description: 'Enables lining figure numerals (uniform height) via font-variant-numeric.',
      keywords: ['typography', 'font-variant-numeric', 'lining-nums', 'numbers', 'figures'],
    },
    {
      type: 'co',
      name: 'oldstyle-nums',
      description:
        'Enables oldstyle figure numerals (varying height/depth) via font-variant-numeric.',
      keywords: ['typography', 'font-variant-numeric', 'oldstyle-nums', 'numbers', 'figures'],
    },
    {
      type: 'co',
      name: 'proportional-nums',
      description: 'Enables proportionally-spaced numeral glyphs via font-variant-numeric.',
      keywords: ['typography', 'font-variant-numeric', 'proportional-nums', 'numbers', 'spacing'],
    },
    {
      type: 'co',
      name: 'diagonal-fractions',
      description: 'Renders numeric fractions with diagonal styling via font-variant-numeric.',
      keywords: [
        'typography',
        'font-variant-numeric',
        'diagonal-fractions',
        'numbers',
        'fractions',
      ],
    },
    {
      type: 'co',
      name: 'stacked-fractions',
      description:
        'Renders numeric fractions with vertically stacked styling via font-variant-numeric.',
      keywords: ['typography', 'font-variant-numeric', 'stacked-fractions', 'numbers', 'fractions'],
    },
    {
      type: 'cc',
      name: 'list-image-none',
      description: 'Removes any custom list marker image by setting list-style-image to none.',
      keywords: ['typography', 'list-style-image', 'list', 'marker', 'none'],
    },
    {
      type: 'cc',
      name: 'decoration-inherit',
      description: 'Sets text-decoration-color to inherit from the parent element.',
      keywords: ['typography', 'text-decoration-color', 'decoration', 'inherit'],
    },
    {
      type: 'cc',
      name: 'decoration-current',
      description: 'Sets text-decoration-color to match the current text color (currentColor).',
      keywords: ['typography', 'text-decoration-color', 'decoration', 'current'],
    },
    {
      type: 'cc',
      name: 'decoration-transparent',
      description: "Sets text-decoration-color to transparent, hiding the decoration's color.",
      keywords: ['typography', 'text-decoration-color', 'decoration', 'transparent'],
    },
    {
      type: 'cc',
      name: 'decoration-double',
      description:
        'Sets text-decoration-style to double, rendering the decoration as two parallel lines.',
      keywords: ['typography', 'text-decoration-style', 'decoration', 'double'],
    },
    {
      type: 'cc',
      name: 'decoration-from-font',
      description:
        "Sets text-decoration-thickness to from-font, using the font's recommended thickness.",
      keywords: ['typography', 'text-decoration-thickness', 'decoration', 'from-font'],
    },
    {
      type: 'cc',
      name: 'decoration-auto',
      description: "Sets text-decoration-thickness to auto, using the browser's default thickness.",
      keywords: ['typography', 'text-decoration-thickness', 'decoration', 'auto'],
    },
    {
      type: 'cc',
      name: 'underline-offset-auto',
      description:
        "Sets text-underline-offset to auto, using the browser's default underline offset.",
      keywords: ['typography', 'text-underline-offset', 'underline', 'auto'],
    },
    {
      type: 'cc',
      name: 'content-none',
      description: 'Sets the content property to none, removing generated pseudo-element content.',
      keywords: ['typography', 'content', 'pseudo-element', 'none'],
    },
  ],
};
